### ISSUE TITLE
Failed building wheel for go-vncdriver

### ISSUE THREAD

**Issue by macura0** [openai/universe#106]
I am using the MacOS Sierra.
I have installed the Dock and Conda.
I have updated Xocde and "xcode-select --install"
When I use the "pip install -e .", I meet some red lines.
please help me.
 ----------------------------------------
  Failed building wheel for go-vncdriver
  Running setup.py clean for go-vncdriver
Failed to build go-vncdriver
Installing collected packages: go-vncdriver, pyglet, gym, zope.interface, constantly, twisted, ujson, universe
  Running setup.py install for go-vncdriver ... error
    Complete output from command /Users/dgy/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/8_/hzh87g5s6sd7x6hvx3_9whsh0000gn/T/pip-build-jvAyyv/go-vncdriver/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/8_/hzh87g5s6sd7x6hvx3_9whsh0000gn/T/pip-3HaSoU-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Running new build
    Could not build go_vncdriver: Could not find libjpeg. HINT: try 'sudo apt-get install libjpeg-turbo8-dev' on Ubuntu or 'brew install libjpeg-turbo' on OSX
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8_/hzh87g5s6sd7x6hvx3_9whsh0000gn/T/pip-build-jvAyyv/go-vncdriver/setup.py", line 75, in <module>
        install_requires=['numpy'],
      File "/Users/dgy/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/Users/dgy/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Users/dgy/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/dgy/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/install.py", line 61, in run
      File "/Users/dgy/anaconda/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/Users/dgy/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Users/dgy/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/8_/hzh87g5s6sd7x6hvx3_9whsh0000gn/T/pip-build-jvAyyv/go-vncdriver/setup.py", line 23, in run
        self.build()
      File "/private/var/folders/8_/hzh87g5s6sd7x6hvx3_9whsh0000gn/T/pip-build-jvAyyv/go-vncdriver/setup.py", line 61, in build
        build.build()
      File "build.py", line 57, in build
        raise BuildException("Could not find libjpeg. HINT: try 'sudo apt-get install libjpeg-turbo8-dev' on Ubuntu or 'brew install libjpeg-turbo' on OSX")
    build.BuildException: Could not find libjpeg. HINT: try 'sudo apt-get install libjpeg-turbo8-dev' on Ubuntu or 'brew install libjpeg-turbo' on OSX
    
    ----------------------------------------
Command "/Users/dgy/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/8_/hzh87g5s6sd7x6hvx3_9whsh0000gn/T/pip-build-jvAyyv/go-vncdriver/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/8_/hzh87g5s6sd7x6hvx3_9whsh0000gn/T/pip-3HaSoU-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/8_/hzh87g5s6sd7x6hvx3_9whsh0000gn/T/pip-build-jvAyyv/go-vncdriver/

**Comment by tlbtlbtlb** [comment]
And you ran `brew install libjpeg-turbo` like it suggested? Did that command give an error?

**Comment by macura0** [comment]
@tlbtlbtlb you are right! I don't install golang and turbo correctly!

**Comment by obadahomsi** [comment]
i have the same error eventhough i installed libjpeg-turbo and all whats listed in the question
