### ISSUE TITLE
Couldn't open /home/xvnc/.vnc/passwd for writing

### ISSUE THREAD

**Issue by discountbrandon** [openai/universe#11]
Having trouble running the VNC server in the docker container. Tried running it manually too, same issue.
Ubuntu 16.04 / python 2.7

[2016-12-05 10:10:08,009] Making new env: flashgames.DuskDrive-v0
[2016-12-05 10:10:08,840] Writing logs to file: /tmp/universe-12876.log
[2016-12-05 10:10:08,857] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.1. Run the same thing by hand as: docker run -p 5900:5900 -p 15900:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.1
[2016-12-05 10:10:09,113] Remote closed: address=localhost:15900
[2016-12-05 10:10:09,116] Remote closed: address=localhost:5900
[2016-12-05 10:10:09,116] At least one sockets was closed by the remote. Sleeping 1s...
universe-hGfDbl-0 | Setting VNC and rewarder password: openai
universe-hGfDbl-0 | Couldn't open /home/xvnc/.vnc/passwd for writing
universe-hGfDbl-0 | Traceback (most recent call last):
universe-hGfDbl-0 |   File "/app/universe-envs/flashgames/init", line 258, in <module>
universe-hGfDbl-0 |     sys.exit(main())
universe-hGfDbl-0 |   File "/app/universe-envs/flashgames/init", line 194, in main
universe-hGfDbl-0 |     subprocess.check_call(['/app/universe-envs/base/openai-setpassword'])
universe-hGfDbl-0 |   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
universe-hGfDbl-0 |     raise CalledProcessError(retcode, cmd)
universe-hGfDbl-0 | subprocess.CalledProcessError: Command '['/app/universe-envs/base/openai-setpassword']' returned non-zero exit status 1
[2016-12-05 10:10:10,117] Remote closed: address=localhost:5900
[2016-12-05 10:10:10,118] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.

**Comment by gdb** [comment]
I see that when my Docker daemon is out of space. You can test it by something like `docker run --rm --privileged ubuntu:16.04 df -h`. What does that show?

**Comment by discountbrandon** [comment]
That's what seems to be the issue, I will get this resolved. Huge thanks for the help and libraries

Filesystem      Size  Used Avail Use% Mounted on
none             15G   15G     0 100% /
tmpfs           2.4G     0  2.4G   0% /dev
tmpfs           2.4G     0  2.4G   0% /sys/fs/cgroup
/dev/sda1        15G   15G     0 100% /etc/hosts
shm              64M     0   64M   0% /dev/shm
