### ISSUE TITLE
can't import universe

### ISSUE THREAD

**Issue by kaifengzhang** [openai/universe#170]
Error is:
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    import universe
  File "/Users/apple/universe/universe/__init__.py", line 22, in <module>
    from universe import error, envs
  File "/Users/apple/universe/universe/envs/__init__.py", line 1, in <module>
    import universe.envs.vnc_env
  File "/Users/apple/universe/universe/envs/vnc_env.py", line 19, in <module>
    import go_vncdriver
ImportError: No module named 'go_vncdriver'

And I have installed the go_vncdriver in the same directory.
Meanwhile when I import go_vncdriver, it won't work either. And the hint is:
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    import go_vncdriver
ImportError: No module named 'go_vncdriver'

I think I have installed the go_vncdriver, which I used the codes like this:
cd go_vncdriver
pip3 install -e.
 
I didn't use the code "python3 build.py" owing to that code won't work successfully.The hint is:
Traceback (most recent call last):
  File "build.py", line 121, in <module>
    main()
  File "build.py", line 20, in main
    build()
  File "build.py", line 29, in build
    shutil.rmtree('.build')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 383, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 381, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [Errno 13] Permission denied: '.build/src/github.com/openai/go-vncdriver'

pls help me if you know how to solve this problem. thx

**Comment by kaifengzhang** [comment]
problem solved: install golang before install go-vncdriver
