### ISSUE TITLE
If this hangs, your docker container may not be able to communicate with Github

### ISSUE THREAD

**Issue by GoingMyWay** [openai/universe#180]
(First, please check https://github.com/openai/universe/wiki/Solutions-to-common-problems for solutions to many common problems)

### Expected behavior

Show the environment of  `flashgames.CoasterRacer-v0`

### Actual behavior
```
universe-s9o0EB-0 | [unpack-lfs] [2017-04-26 14:06:51,017] Fetching files: git lfs pull -I git-lfs/flashgames.CoasterRacer-v0.tar.gz
universe-s9o0EB-0 | [unpack-lfs] [2017-04-26 14:06:51,020] If this hangs, your docker container may not be able to communicate with Github
[2017-04-26 22:07:50,725] [0] Closing rewarder connection
Traceback (most recent call last):
  File "demo.py", line 97, in <module>
    main()
  File "demo.py", line 92, in main
    observation_n, reward_n, done_n, info = env.step(action_n)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 99, in step
    return self._step(action)
  File "/Users/qiuwei/AI/OpenAI/universe/universe/wrappers/timer.py", line 23, in _step
    observation_n, reward_n, done_n, info = self.env.step(action_n)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 99, in step
    return self._step(action)
  File "/Users/qiuwei/AI/OpenAI/universe/universe/wrappers/render.py", line 33, in _step
    observation_n, reward_n, done_n, info_n = self.env.step(action_n)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 99, in step
    return self._step(action)
  File "/Users/qiuwei/AI/OpenAI/universe/universe/wrappers/throttle.py", line 117, in _step
    universe-s9o0EB-0 | [nginx] 2017/04/26 14:07:50 [info] 63#63: *3 upstream timed out (110: Connection timed out) while proxying upgraded connection, client: 172.17.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:15901/", host: "localhost:15900"
observation_n, reward_n, done_n, info = self._substep(action_n)
universe-s9o0EB-0 | [nginx] 172.17.0.1 - openai [26/Apr/2017:14:07:50 +0000] "GET / HTTP/1.1" 101 3549 "-" "AutobahnPython/0.18.2"
universe-s9o0EB-0 | [2017-04-26 14:07:50,720] [INFO:universe.rewarder.remote] WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
universe-s9o0EB-0 | [2017-04-26 14:07:50,721] [INFO:universe.rewarder.remote] [Twisted] Active client disconnected (sent 11 messages). Still have 0 active clients left
universe-s9o0EB-0 | [tigervnc]
universe-s9o0EB-0 | [tigervnc] Wed Apr 26 14:07:50 2017
universe-s9o0EB-0 | [tigervnc]  Connections: closed: 172.17.0.1::34964 (Clean disconnection)
  File "/Users/qiuwei/AI/OpenAI/universe/universe/wrappers/throttle.py", line 132, in _substep
    observation_n, reward_n, done_n, info = self.env.step(action_n)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 99, in step
    return self._step(action)
  File "/Users/qiuwei/AI/OpenAI/universe/universe/envs/vnc_env.py", line 464, in _step
    self._handle_crashed_n(info_n)
universe-s9o0EB-0 | [tigervnc]  EncodeManager: Framebuffer updates: 24
  File "/Users/qiuwei/AI/OpenAI/universe/universe/envs/vnc_env.py", line 537, in _handle_crashed_n
    raise error.Error('{}/{} environments have crashed! Most recent error: {}'.format(len(self.crashed), self.n, errors))
universe.error.Error: 1/1 environments have crashed! Most recent error: {'0': 'Rewarder session failed: Lost connection: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake) (clean=False code=1006)'}
[2017-04-26 22:07:50,752] Killing and removing container: id=6dca801b9c79ad3a232fc2433a4b6239a308ad9cae6a2147aab8deb473cf5341
universe-s9o0EB-0 | [tigervnc]  EncodeManager:   Tight:
universe-s9o0EB-0 | [tigervnc]  EncodeManager:     Solid: 46 rects, 2.50204 Mpixels
universe-s9o0EB-0 | [tigervnc]  EncodeManager:            736 B (1:13598.8 ratio)
universe-s9o0EB-0 | [tigervnc]  EncodeManager:     Bitmap RLE: 9 rects, 88.416 kpixels
universe-s9o0EB-0 | [tigervnc]  EncodeManager:                 486 B (1:727.926 ratio)
universe-s9o0EB-0 | [tigervnc]  EncodeManager:     Indexed RLE: 27 rects, 243.1 kpixels
universe-s9o0EB-0 | [tigervnc]  EncodeManager:                  11.4365 KiB (1:83.0607 ratio)
universe-s9o0EB-0 | [tigervnc]  EncodeManager:   Tight (JPEG):
universe-s9o0EB-0 | [tigervnc]  EncodeManager:     Full Colour: 14 rects, 549.336 kpixels
universe-s9o0EB-0 | [tigervnc]  EncodeManager:                  107.31 KiB (1:19.9983 ratio)
universe-s9o0EB-0 | [tigervnc]  EncodeManager:   Total: 96 rects, 3.38289 Mpixels
universe-s9o0EB-0 | [tigervnc]  EncodeManager:          119.939 KiB (1:110.185 ratio)
```

### Versions
Please include the result of running
```
$ uname -a ; python --version; pip show universe gym tensorflow numpy go-vncdriver Pillow

Darwin qiuweis-MBP.lan 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
Python 2.7.10
Name: universe
Version: 0.21.5
Summary: Universe: a software platform for measuring and training an AI's general intelligence across the world's supply of games, websites and other applications.
Home-page: https://github.com/openai/universe
Author: OpenAI
Author-email: universe@openai.com
License: UNKNOWN
Location: /Users/qiuwei/AI/OpenAI/universe
Requires: autobahn, docker-py, docker-pycreds, fastzbarlight, go-vncdriver, gym, Pillow, PyYAML, six, twisted, ujson
---
Name: gym
Version: 0.8.1
Summary: The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.
Home-page: https://github.com/openai/gym
Author: OpenAI
Author-email: gym@openai.com
License: UNKNOWN
Location: /usr/local/lib/python2.7/site-packages
Requires: pyglet, numpy, six, requests
---
Name: tensorflow
Version: 1.0.1
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /Users/qiuwei/Library/Python/2.7/lib/python/site-packages
Requires: wheel, protobuf, six, numpy, mock
---
Name: numpy
Version: 1.12.1
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: NumPy Developers
Author-email: numpy-discussion@scipy.org
License: BSD
Location: /Users/qiuwei/Library/Python/2.7/lib/python/site-packages
Requires:
---
Name: go-vncdriver
Version: 0.4.19
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /Users/qiuwei/AI/OpenAI/go-vncdriver
Requires: numpy
---
Name: Pillow
Version: 4.1.0
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org
Author: Alex Clark (Fork Author)
Author-email: aclark@aclark.net
License: Standard PIL License
Location: /Users/qiuwei/Library/Python/2.7/lib/python/site-packages
Requires: olefile
```

I'm in China, are there any helpful ways to run it?

**Comment by tlbtlbtlb** [comment]
It seems that the docker container is unable to connect to github.com. You can debug by starting a shell inside the container (`docker exec -ti <container-id> bash`) and trying to telnet to www.github.com.
