### ISSUE TITLE
egg_info failed with error code 1 

### ISSUE THREAD

**Issue by toast216** [openai/universe#19]
raph@raph-VirtualBox:~/universe$ pip install -e .Obtaining file:///home/raph/universe
    Complete output from command python setup.py egg_info:
    running egg_info
    writing requirements to universe.egg-info/requires.txt
    writing universe.egg-info/PKG-INFO
    writing top-level names to universe.egg-info/top_level.txt
    writing dependency_links to universe.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/raph/universe/setup.py", line 26, in <module>
        'atari': 'gym[atari]',
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 186, in run
        self.find_sources()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 209, in find_sources
        mm.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 293, in run
        self.add_defaults()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 322, in add_defaults
        sdist.add_defaults(self)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/sdist.py", line 127, in add_defaults
        for _, src_dir, _, filenames in build_py.data_files:
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 65, in __getattr__
        self.data_files = self._get_data_files()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 79, in _get_data_files
        return list(map(self._get_pkg_data_files, self.packages or ()))
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 91, in _get_pkg_data_files
        for file in self.find_data_files(package, src_dir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 98, in find_data_files
        + self.package_data.get(package, []))
    TypeError: can only concatenate list (not "str") to list
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/raph/universe/

**Comment by jeremyschlatter** [comment]
@toast216 I think this is fixed in 9fa293bf89b54b40ea32b4814a21ba1f5b25b130. Can you try installing again?

**Comment by bartholomew91** [comment]
Can't confirm for @toast216, but the fix you just pushed @jeremyschlatter works for me. Thanks!
