### ISSUE TITLE
Error: Cannot re-register id

### ISSUE THREAD

**Issue by yash1998** [openai/universe#197]
(First, please check https://github.com/openai/universe/wiki/Solutions-to-common-problems for solutions to many common problems)

I ran this code ...
import gym
import universe  # register the universe environments

env = gym.make('flashgames.DuskDrive-v0')
env.configure(remotes=1)  # automatically creates a local docker container
observation_n = env.reset()

while True:
  action_n = [[('KeyEvent', 'ArrowUp', True)] for ob in observation_n]  # your agent here
  observation_n, reward_n, done_n, info = env.step(action_n)
  env.render()

##It is giving an error...
Reloaded modules: universe.scoreboard, universe.configuration, universe.error, universe.envs, universe.envs.vnc_env, universe.pyprofile, universe.rewarder, universe.rewarder.rewarder_session, universe.utils, universe.twisty, universe.rewarder.connection_timer, universe.rewarder.env_status, universe.rewarder.reward_buffer, universe.rewarder.merge, universe.rewarder.rewarder_client, universe.utils.display, universe.spaces, universe.spaces.hardcoded, universe.spaces.vnc_action_space, universe.vncdriver, universe.vncdriver.vnc_session, universe.vncdriver.screen, universe.vncdriver.screen.base, universe.vncdriver.screen.numpy_screen, universe.vncdriver.server_messages, universe.spaces.vnc_event, universe.vncdriver.constants, universe.vncdriver.screen.pyglet_screen, universe.vncdriver.screen.screen_buffer, universe.vncdriver.vnc_client, universe.vncdriver.auth, universe.vncdriver.vendor, universe.vncdriver.vendor.pydes, universe.vncdriver.error, universe.spaces.vnc_observation_space, universe.spaces.diagnostics, universe.vectorized, universe.vectorized.core, universe.vectorized.multiprocessing_env, universe.vectorized.vectorize_filter, universe.remotes, universe.remotes.hardcoded_addresses, universe.remotes.remote, universe.remotes.allocator_remote, universe.remotes.docker_remote, universe.remotes.healthcheck, universe.remotes.compose, universe.remotes.compose.container, universe.remotes.compose.log_printer, universe.remotes.compose.colors, universe.remotes.compose.utils, universe.remotes.compose.signals, universe.remotes.compose.progress_stream, universe.remotes.build, universe.envs.diagnostics, universe.runtimes, universe.runtimes.registration, universe.vncdriver.libvnc_session, universe.envs.vnc_core_env, universe.envs.vnc_core_env.vnc_core_env, universe.envs.vnc_core_env.translator, universe.envs.vnc_core_env.key, universe.envs.vnc_flashgames, universe.envs.vnc_internet, universe.envs.vnc_starcraft, universe.envs.vnc_gtav, universe.spaces.joystick_action_space, universe.spaces.joystick_event, universe.envs.vnc_wog, universe.envs.dummy_vnc_env
Traceback (most recent call last):

  File "<ipython-input-3-cb45e6d99cbd>", line 1, in <module>
    runfile('/home/yash/Desktop/mybot.py', wdir='/home/yash/Desktop')

  File "/home/yash/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "/home/yash/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/yash/Desktop/mybot.py", line 2, in <module>
    import universe  # register the universe environments

  File "/home/yash/universe/universe/__init__.py", line 125, in <module>
    trials=2,

  File "/home/yash/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 158, in register
    return registry.register(id, **kwargs)

  File "/home/yash/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 151, in register
    raise error.Error('Cannot re-register id: {}'.format(id))

Error: Cannot re-register id: gym-core.CartPoleLowDSync-v0

**Comment by yash1998** [comment]
Please Solve this error...
