### ISSUE TITLE
`TypeError: 'NoneType' object is not subscriptable` error during pytest

### ISSUE THREAD

**Issue by kensully** [openai/universe#208]
First of all I congratulate you on your awesome project. I am running Ubuntu 16.04 32 bit platform. I followed the instructions in readme page, but I got the below errors.

```
  uname -a ; python --version; pip show universe gym tensorflow numpy go-vncdriver Pillow
Linux kenn 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:34:49 UTC 2016 i686 i686 i686 GNU/Linux
Python 2.7.12
Name: universe
Version: 0.21.5
Summary: Universe: a software platform for measuring and training an AI's general intelligence across the world's supply of games, websites and other applications.
Home-page: https://github.com/openai/universe
Author: OpenAI
Author-email: universe@openai.com
License: UNKNOWN
Location: /home/trabzonspor/CODING-RELOADED/universe
Requires: autobahn, docker-py, docker-pycreds, fastzbarlight, go-vncdriver, gym, Pillow, PyYAML, six, twisted, ujson
---
Name: gym
Version: 0.9.3
Summary: The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.
Home-page: https://github.com/openai/gym
Author: OpenAI
Author-email: gym@openai.com
License: UNKNOWN
Location: /usr/local/lib/python3.5/dist-packages
Requires: six, numpy, pyglet, requests
---
Name: numpy
Version: 1.13.1
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: NumPy Developers
Author-email: numpy-discussion@python.org
License: BSD
Location: /usr/local/lib/python3.5/dist-packages
Requires: 
---
Name: go-vncdriver
Version: 0.4.19
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /usr/local/lib/python3.5/dist-packages
Requires: numpy
---
Name: Pillow
Version: 4.2.1
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org
Author: Alex Clark (Fork Author)
Author-email: aclark@aclark.net
License: Standard PIL License
Location: /usr/local/lib/python3.5/dist-packages
Requires: olefile

```

```
$ docker run --privileged --rm -e DOCKER_NET_HOST=172.17.0.1 -v /var/run/docker.sock:/var/run/docker.sock universe pytest
==================== 6 failed, 16 passed in 110.71 seconds =====================
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gym/utils/closer.py", line 67, in close
    closeable.close()
  File "/usr/local/lib/python3.5/dist-packages/gym/core.py", line 164, in close
    self.render(close=True)
  File "/usr/local/lib/python3.5/dist-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/usr/local/universe/universe/vectorized/multiprocessing_env.py", line 310, in _render
    return render_n(self.worker_n, mode=mode, close=close)
  File "/usr/local/universe/universe/vectorized/multiprocessing_env.py", line 230, in render_n
    worker_n = worker_n[0:]
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <bound method Env.__del__ of <universe.vectorized.multiprocessing_env.MultiprocessingEnv object at 0x82029bec>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gym/core.py", line 203, in __del__
    self.close()
  File "/usr/local/lib/python3.5/dist-packages/gym/core.py", line 164, in close
    self.render(close=True)
  File "/usr/local/lib/python3.5/dist-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/usr/local/universe/universe/vectorized/multiprocessing_env.py", line 310, in _render
    return render_n(self.worker_n, mode=mode, close=close)
  File "/usr/local/universe/universe/vectorized/multiprocessing_env.py", line 230, in render_n
    worker_n = worker_n[0:]
TypeError: 'NoneType' object is not subscriptable
```
Any help please.
Regards.
Kenn

**Comment by b623** [comment]
same error here,  I read that other got it too.  At first sight it seems worker_n[0:] is nonetype.  it is in close() function, so why not try   if nonetype skip the line that make the error, or assign to 0
