### ISSUE TITLE
a error when Running the DuskDrive demo

### ISSUE THREAD

**Issue by jhcknzzm** [openai/universe#215]
(First, please check https://github.com/openai/universe/wiki/Solutions-to-common-problems for solutions to many common problems)

### Expected behavior
import gym
import universe # register the universe environments
env = gym.make('flashgames.DuskDrive-v0')
env.configure(remotes=1) # automatically creates a local docker container
observation_n = env.reset()
while True:
 action_n = [[('KeyEvent', 'ArrowUp', True)] for ob in observation_n] # your agent here
 observation_n, reward_n, done_n, info = env.step(action_n)
 env.render()
### Actual behavior
[2017-11-10 21:57:02,085] Making new env: flashgames.DuskDrive-v0
[2017-11-10 21:57:02,143] Writing logs to file: /tmp/universe-12058.log
[2017-11-10 21:57:02,267] Ports used: dict_keys([])
[2017-11-10 21:57:02,268] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.28. Run the same thing by hand as: docker run -p 5900:5900 -p 15900:15900 --privileged --cap-add SYS_ADMIN --ipc host quay.io/openai/universe.flashgames:0.20.28
Traceback (most recent call last):
  File "/home/zzm/anaconda3/lib/python3.6/site-packages/docker/client.py", line 170, in _raise_for_status
500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.30/containers/98587bcd3d30175e3a6d8c1e94abe31d6bc98f570dee5c388f5e9fb41e68f76f/start
    response.raise_for_status()
  File "/home/zzm/anaconda3/lib/python3.6/site-packages/requests/models.py", line 845, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.30/containers/98587bcd3d30175e3a6d8c1e94abe31d6bc98f570dee5c388f5e9fb41e68f76f/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zzm/workspace/CV0/Test_A.py", line 5, in <module>
    env.configure(remotes=1)
  File "/home/zzm/universe/universe/wrappers/timer.py", line 14, in configure
    self.env.configure(**kwargs)
  File "/home/zzm/universe/universe/wrappers/render.py", line 21, in configure
    self.env.configure(**kwargs)
  File "/home/zzm/universe/universe/wrappers/throttle.py", line 32, in configure
    self.env.configure(**kwargs)
  File "/home/zzm/universe/universe/envs/vnc_env.py", line 199, in configure
    use_recorder_ports=record,
  File "/home/zzm/universe/universe/remotes/build.py", line 19, in build
    n=n,
  File "/home/zzm/universe/universe/remotes/docker_remote.py", line 55, in __init__
    self._start()
  File "/home/zzm/universe/universe/remotes/docker_remote.py", line 82, in _start
    [instance.start() for instance in self.instances]
  File "/home/zzm/universe/universe/remotes/docker_remote.py", line 82, in <listcomp>
    [instance.start() for instance in self.instances]
  File "/home/zzm/universe/universe/remotes/docker_remote.py", line 237, in start
    e = self._start()
  File "/home/zzm/universe/universe/remotes/docker_remote.py", line 324, in _start
    self.client.start(container=self._container_id)
  File "/home/zzm/anaconda3/lib/python3.6/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/zzm/anaconda3/lib/python3.6/site-packages/docker/api/container.py", line 383, in start
    self._raise_for_status(res)
  File "/home/zzm/anaconda3/lib/python3.6/site-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'{"message":"driver failed programming external connectivity on endpoint universe-smbsJG-0 (6534f42fdfd596d21454cd3c2eaa03190def5794939277415a8af8501f7d908b): Error starting userland proxy: listen tcp 0.0.0.0:5900: bind: address already in use"}'")
[2017-11-10 21:57:03,642] Killing and removing container: id=98587bcd3d30175e3a6d8c1e94abe31d6bc98f570dee5c388f5e9fb41e68f76f

**Comment by jhcknzzm** [comment]
How should this problem be solved?
