### ISSUE TITLE
Universe crash when running on Kubernetes 1.8,,,

### ISSUE THREAD

**Issue by ethilesen** [openai/universe#230]
Hi, I try to run the quay.io/openai/universe.flashgames:0.20.28 in kubernetes 1.8

It starts ok but as soon I a start the agent the play start and then crash.... When the agent are stoped I can run the game nice over vnc....
part to the k8s deployment:
spec:
      containers:
      - name: universe
        image: quay.io/openai/universe.flashgames:0.20.28
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME", "SYS_ADMIN"]
        ports:
        - containerPort: 5900
          containerPort: 15900

log:
root@aidev:/# more /tmp/universe-552.log
[2018-02-01 22:47:02,771] Using the golang VNC implementation
[2018-02-01 22:47:02,772] Using VNCSession arguments: {'encoding': 'tight', 'start_timeout': 7, 'fine_quality_level': 50, 'subsample_level': 2}. (Customize by 
running "env.configure(vnc_kwargs={...})"
[2018-02-01 22:47:02,792] [0] Connecting to environment: vnc://10.0.0.135:5900 password=openai. If desired, you can manually connect a VNC viewer, such as Turb
oVNC. Most environments provide a convenient in-browser VNC client: http://10.0.0.135:15900/viewer/?password=openai
[2018-02-01 22:47:02,792] [0] Connecting to environment details: vnc_address=10.0.0.135:5900 vnc_password=openai rewarder_address=10.0.0.135:15900 rewarder_pas
sword=openai
[2018-02-01 22:47:02,795] [0:10.0.0.135:5900] RewardBuffer advancing: masking until reset completes; setting current_episode_id=None
[2018-02-01 22:47:02,803] [0:10.0.0.135:5900] Rewarder TCP connection established
[2018-02-01 22:47:02,811] [0:10.0.0.135:5900] RewardBuffer: Creating new RewardState for episode_id=None
[2018-02-01 22:47:02,815] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:02,841] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:02,877] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:02,898] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:02,926] [0:10.0.0.135:5900] Websocket client successfully connected
[2018-02-01 22:47:02,926] [0:10.0.0.135:5900] Starting network calibration with ntpdate -q -p 8 10.0.0.135
[2018-02-01 22:47:02,956] [0:10.0.0.135:5900] Received payload: b'{"body":{"env_state":"running","fps":60,"env_id":"flashgames.NeonRace-v0"},"method":"v0.env.d
escribe","headers":{"sent_at":1517525222.9030151367,"message_id":0,"episode_id":"3"}}'
[2018-02-01 22:47:02,956] [0:10.0.0.135:5900] RewardBuffer: Creating new RewardState for episode_id=3
[2018-02-01 22:47:02,956] [0:10.0.0.135:5900] Received v0.env.describe: env_id=flashgames.NeonRace-v0 env_state=running episode_id=3
[2018-02-01 22:47:02,956] [0:10.0.0.135:5900] RewardBuffer: Initial env_state: running (env_id=flashgames.NeonRace-v0) (episode_id: 3, fps=60, masked=True, cur
rent_episode_id=None)
[2018-02-01 22:47:02,959] [0:10.0.0.135:5900] Could not determine clock skew with ntpdate; falling back to application-level ping: ['ntpdate', '-q', '-p', '8',
 '10.0.0.135'] failed with status 1: stderr=b'Upon execvpe /usr/sbin/ntpdate [b\'ntpdate\', b\'-q\', b\'-p\', b\'8\', b\'10.0.0.135\'] in environment id 140486
166914824\n:Traceback (most recent call last):\n  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/process.py", line 445, in _fork\n    environmen
t)\n  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/process.py", line 523, in _execChild\n    os.execvpe(executable, args, environment)\n  File
 "/usr/lib/python3.5/os.py", line 624, in execvpe\n    _execvpe(file, args, env)\n  File "/usr/lib/python3.5/os.py", line 639, in _execvpe\n    exec_func(file,
 *argrest)\nFileNotFoundError: [Errno 2] No such file or directory: \'/usr/sbin/ntpdate\'\n'
[2018-02-01 22:47:02,959] [0:10.0.0.135:5900] Measuring connection time (1/10)
[2018-02-01 22:47:02,965] [0:10.0.0.135:5900] Measuring connection time (2/10)
[2018-02-01 22:47:02,966] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:02,973] [0:10.0.0.135:5900] Measuring connection time (3/10)
[2018-02-01 22:47:02,976] [0:10.0.0.135:5900] Measuring connection time (4/10)
[2018-02-01 22:47:02,979] [0:10.0.0.135:5900] Measuring connection time (5/10)
[2018-02-01 22:47:02,986] [0:10.0.0.135:5900] Measuring connection time (6/10)
[2018-02-01 22:47:02,989] [0:10.0.0.135:5900] Measuring connection time (7/10)
[2018-02-01 22:47:02,989] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:02,992] [0:10.0.0.135:5900] Measuring connection time (8/10)
[2018-02-01 22:47:02,993] [0:10.0.0.135:5900] Measuring connection time (9/10)
[2018-02-01 22:47:02,993] [0:10.0.0.135:5900] Measuring connection time (10/10)
[2018-02-01 22:47:02,994] [0:10.0.0.135:5900] Issuing an application-level ping (1/10)
[2018-02-01 22:47:02,994] [0:10.0.0.135:5900] Sending message to rewarder: {'headers': {'sent_at': 1517525222.9946003, 'message_id': 0}, 'method': 'v0.control.
ping', 'body': {}}
[2018-02-01 22:47:03,010] [0:10.0.0.135:5900] Received payload: b'{"body":{},"method":"v0.reply.control.ping","headers":{"parent_message_id":0,"sent_at":151752
5223.005466938,"message_id":1}}'
[2018-02-01 22:47:03,011] [0:10.0.0.135:5900] Issuing an application-level ping (2/10)
[2018-02-01 22:47:03,011] [0:10.0.0.135:5900] Sending message to rewarder: {'headers': {'sent_at': 1517525223.0111368, 'message_id': 1}, 'method': 'v0.control.
ping', 'body': {}}
[2018-02-01 22:47:03,013] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:03,021] [0:10.0.0.135:5900] Received payload: b'{"body":{},"method":"v0.reply.control.ping","headers":{"parent_message_id":1,"sent_at":151752
5223.0163578987,"message_id":2}}'
[2018-02-01 22:47:03,021] [0:10.0.0.135:5900] Issuing an application-level ping (3/10)
[2018-02-01 22:47:03,022] [0:10.0.0.135:5900] Sending message to rewarder: {'headers': {'sent_at': 1517525223.022051, 'message_id': 2}, 'method': 'v0.control.p
ing', 'body': {}}
[2018-02-01 22:47:03,025] [0:10.0.0.135:5900] Received payload: b'{"body":{},"method":"v0.reply.control.ping","headers":{"parent_message_id":2,"sent_at":151752
5223.0241408348,"message_id":3}}'
[2018-02-01 22:47:03,025] [0:10.0.0.135:5900] Issuing an application-level ping (4/10)
[2018-02-01 22:47:03,025] [0:10.0.0.135:5900] Sending message to rewarder: {'headers': {'sent_at': 1517525223.0256922, 'message_id': 3}, 'method': 'v0.control.
ping', 'body': {}}
[2018-02-01 22:47:03,026] [0:10.0.0.135:5900] Received payload: b'{"body":{},"method":"v0.reply.control.ping","headers":{"parent_message_id":3,"sent_at":151752
5223.0262739658,"message_id":4}}'
[2018-02-01 22:47:03,027] [0:10.0.0.135:5900] Issuing an application-level ping (5/10)
[2018-02-01 22:47:03,027] [0:10.0.0.135:5900] Sending message to rewarder: {'headers': {'sent_at': 1517525223.0270755, 'message_id': 4}, 'method': 'v0.control.
ping', 'body': {}}
[2018-02-01 22:47:03,030] [0:10.0.0.135:5900] Received payload: b'{"body":{},"method":"v0.reply.control.ping","headers":{"parent_message_id":4,"sent_at":151752
5223.0294468403,"message_id":5}}'
[2018-02-01 22:47:03,030] [0:10.0.0.135:5900] Issuing an application-level ping (6/10)
[2018-02-01 22:47:03,030] [0:10.0.0.135:5900] Sending message to rewarder: {'headers': {'sent_at': 1517525223.0306249, 'message_id': 5}, 'method': 'v0.control.
ping', 'body': {}}
[2018-02-01 22:47:03,033] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:03,042] [0:10.0.0.135:5900] Received payload: b'{"body":{},"method":"v0.reply.control.ping","headers":{"parent_message_id":5,"sent_at":151752
5223.0420973301,"message_id":6}}'
[2018-02-01 22:47:03,042] [0:10.0.0.135:5900] Issuing an application-level ping (7/10)
[2018-02-01 22:47:03,042] [0:10.0.0.135:5900] Sending message to rewarder: {'headers': {'sent_at': 1517525223.042841, 'message_id': 6}, 'method': 'v0.control.p
ing', 'body': {}}
[2018-02-01 22:47:03,045] [0:10.0.0.135:5900] Received payload: b'{"body":{},"method":"v0.reply.control.ping","headers":{"parent_message_id":6,"sent_at":151752
5223.0441939831,"message_id":7}}'
[2018-02-01 22:47:03,045] [0:10.0.0.135:5900] Issuing an application-level ping (8/10)
[2018-02-01 22:47:03,045] [0:10.0.0.135:5900] Sending message to rewarder: {'headers': {'sent_at': 1517525223.0455158, 'message_id': 7}, 'method': 'v0.control.
ping', 'body': {}}
[2018-02-01 22:47:03,048] [0:10.0.0.135:5900] Received payload: b'{"body":{},"method":"v0.reply.control.ping","headers":{"parent_message_id":7,"sent_at":151752
5223.0476894379,"message_id":8}}'
[2018-02-01 22:47:03,048] [0:10.0.0.135:5900] Issuing an application-level ping (9/10)
[2018-02-01 22:47:03,048] [0:10.0.0.135:5900] Sending message to rewarder: {'headers': {'sent_at': 1517525223.0489438, 'message_id': 8}, 'method': 'v0.control.
ping', 'body': {}}
[2018-02-01 22:47:03,051] [0:10.0.0.135:5900] Received payload: b'{"body":{},"method":"v0.reply.control.ping","headers":{"parent_message_id":8,"sent_at":151752
5223.0495028496,"message_id":9}}'
[2018-02-01 22:47:03,051] [0:10.0.0.135:5900] Issuing an application-level ping (10/10)
[2018-02-01 22:47:03,051] [0:10.0.0.135:5900] Sending message to rewarder: {'headers': {'sent_at': 1517525223.0515587, 'message_id': 9}, 'method': 'v0.control.
ping', 'body': {}}
[2018-02-01 22:47:03,053] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:03,053] [0:10.0.0.135:5900] Received payload: b'{"body":{},"method":"v0.reply.control.ping","headers":{"parent_message_id":9,"sent_at":151752
5223.0520620346,"message_id":10}}'
[2018-02-01 22:47:03,058] [0:10.0.0.135:5900] Network calibration: ntpdate_clock_skew=None clock_skew=(-2.03ms±0.57ms, 3.72ms±1.32ms) connection_time=3.12ms±0.82m
s application_rtt=5.75ms±1.65ms request_overhead=0.00ms±0.00ms response_overhead=0.05ms±0.00ms
[2018-02-01 22:47:03,058] [0:10.0.0.135:5900] Network calibration complete
[2018-02-01 22:47:03,058] [0:10.0.0.135:5900] Sending reset for env_id=flashgames.NeonRace-v0 fps=60 episode_id=0
[2018-02-01 22:47:03,059] [0:10.0.0.135:5900] Sending message to rewarder: {'headers': {'sent_at': 1517525223.059489, 'episode_id': '0', 'message_id': 10}, 'me
thod': 'v0.env.reset', 'body': {'fps': 60, 'env_id': 'flashgames.NeonRace-v0', 'seed': None}}
[2018-02-01 22:47:03,069] [0:10.0.0.135:5900] Received payload: b'{"body":{"env_state":"resetting","fps":60,"env_id":"flashgames.NeonRace-v0"},"method":"v0.env
.describe","headers":{"sent_at":1517525223.0689272881,"message_id":11,"episode_id":"4"}}'
[2018-02-01 22:47:03,069] [0:10.0.0.135:5900] RewardBuffer: Creating new RewardState for episode_id=4
[2018-02-01 22:47:03,069] [0:10.0.0.135:5900] Received v0.env.describe: env_id=flashgames.NeonRace-v0 env_state=resetting episode_id=4
[2018-02-01 22:47:03,069] [0:10.0.0.135:5900] RewardBuffer changing env_state: running (env_id=flashgames.NeonRace-v0) -> resetting (env_id=flashgames.NeonRace
-v0) (episode_id: 3->4, fps=60, masked=True, current_episode_id=None)
[2018-02-01 22:47:03,073] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:03,095] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:03,114] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:03,141] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:03,162] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:03,183] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:03,201] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:03,222] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:03,243] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None
[2018-02-01 22:47:03,262] [0:10.0.0.135:5900] RewardState: popping reward 0.0 from episode_id None

**Comment by ethilesen** [comment]
Hi, solved this.. If anyone wonder..
Set the hostIPC: true and hostPID: true on the Deployment... then it runs ok..
## Deployment sample...
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: universe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: universe
    spec:
      hostIPC: true
      hostPID: true
      containers:
        - name: universe
          image: quay.io/openai/universe.flashgames:0.20.28
          ports:
            - containerPort: 5900
              hostPort: 5900
            - containerPort: 15900
              hostPort: 15900
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_ADMIN", "MAC_ADMIN", "IPC_OWNER"]
            allowPrivilegeEscalation: true
            runAsUser: 0
            privileged: true
