### ISSUE TITLE
Cant install Gym because of Mujoco-py error 

### ISSUE THREAD

**Issue by Emiougus** [openai/universe#233]
Ive been trying to install Open AI gym for the last 4 hours with no success I've tried all the fixs I could find with no success.

(universe) emiougus@P0ssie:~/gym$ pip install -e '.[all]'
Obtaining file:///home/emiougus/gym
Requirement already satisfied: numpy>=1.10.4 in /home/emiougus/anaconda3/envs/universe/lib/python2.7/site-packages (from gym==0.9.6)
Requirement already satisfied: requests>=2.0 in /home/emiougus/anaconda3/envs/universe/lib/python2.7/site-packages (from gym==0.9.6)
Requirement already satisfied: six in /home/emiougus/anaconda3/envs/universe/lib/python2.7/site-packages (from gym==0.9.6)
Requirement already satisfied: pyglet>=1.2.0 in /home/emiougus/anaconda3/envs/universe/lib/python2.7/site-packages (from gym==0.9.6)
Requirement already satisfied: Box2D-kengz in /home/emiougus/anaconda3/envs/universe/lib/python2.7/site-packages (from gym==0.9.6)
Requirement already satisfied: PyOpenGL in /home/emiougus/anaconda3/envs/universe/lib/python2.7/site-packages (from gym==0.9.6)
Requirement already satisfied: atari_py>=0.1.1 in /home/emiougus/anaconda3/envs/universe/lib/python2.7/site-packages (from gym==0.9.6)
Requirement already satisfied: Pillow in /home/emiougus/anaconda3/envs/universe/lib/python2.7/site-packages (from gym==0.9.6)
Collecting mujoco_py>=1.50 (from gym==0.9.6)
  Using cached mujoco-py-1.50.1.35.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jfA_3C/mujoco-py/setup.py", line 2, in <module>
        import importlib.util
    ImportError: No module named util
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jfA_3C/mujoco-py/

**Comment by jackmead515** [comment]
Same problem.

**Comment by soilad** [comment]
Identical error, here too.

**Comment by apsamuel** [comment]
+1

**Comment by kevindavenport** [comment]
Same problem - tried in fresh conda 2.7 env. I've never encountered such a convoluted install process as mujoco.

**Comment by unitedideas** [comment]
same:

SHANE2017iMac:gym shanecheek$ pip3 install -e .[all]
Obtaining file:///Users/shanecheek/gym
Requirement already satisfied: numpy>=1.10.4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gym==0.10.3)
Requirement already satisfied: requests>=2.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gym==0.10.3)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gym==0.10.3)
Requirement already satisfied: pyglet>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gym==0.10.3)
Collecting atari_py>=0.1.1 (from gym==0.10.3)
  Using cached atari-py-0.1.1.tar.gz
Collecting Pillow (from gym==0.10.3)
  Downloading Pillow-5.0.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.5MB)
    100% |████████████████████████████████| 3.5MB 553kB/s 
Collecting PyOpenGL (from gym==0.10.3)
  Using cached PyOpenGL-3.1.0.tar.gz
Collecting Box2D-kengz (from gym==0.10.3)
  Using cached Box2D-kengz-2.3.3.tar.gz
Collecting mujoco_py>=1.50 (from gym==0.10.3)
  Using cached mujoco-py-1.50.1.41.tar.gz
    Complete output from command python setup.py egg_info:
    _configtest.c:1:1: error: thread-local storage is not supported for the current target
    __thread int some_threadlocal_variable_42;
    ^
    1 error generated.
    
    Installed /private/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/pip-build-wwofnlln/mujoco-py/.eggs/cffi-1.11.5-py3.6-macosx-10.6-intel.egg
    Searching for imageio>=2.1.2
    Reading https://pypi.python.org/simple/imageio/
    Downloading https://pypi.python.org/packages/a0/4b/f68b2a2e3e98bc006f54ff6fee50f20c7ca4052ec6da68c58c299c7bedf5/imageio-2.2.0.tar.gz#md5=0fcd6f8aee6966837952fada03862a0a
    Best match: imageio 2.2.0
    Processing imageio-2.2.0.tar.gz
    Writing /var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/easy_install-nc44tnfh/imageio-2.2.0/setup.cfg
    Running imageio-2.2.0/setup.py -q bdist_egg --dist-dir /var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/easy_install-nc44tnfh/imageio-2.2.0/egg-dist-tmp-dk71b5ep
    Note: will not use '__thread' in the C code
    ***** The above error message can be safely ignored.
    
    zip_safe flag not set; analyzing archive contents...
    imageio.__pycache__.testing.cpython-36: module references __file__
    imageio.core.__pycache__.findlib.cpython-36: module references __file__
    imageio.core.__pycache__.util.cpython-36: module references __file__
    imageio.plugins.__pycache__.pillow_info.cpython-36: module references __file__
    creating /private/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/pip-build-wwofnlln/mujoco-py/.eggs/imageio-2.2.0-py3.6.egg
    Extracting imageio-2.2.0-py3.6.egg to /private/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/pip-build-wwofnlln/mujoco-py/.eggs
    
    Installed /private/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/pip-build-wwofnlln/mujoco-py/.eggs/imageio-2.2.0-py3.6.egg
    Searching for glfw>=1.4.0
    Reading https://pypi.python.org/simple/glfw/
    Downloading https://pypi.python.org/packages/84/59/5ddd23f55ccff106eec8d3bf34d1a6351bfd23d5c2cd357c2e9edc6f8e76/glfw-1.5.1.tar.gz#md5=4daeecebfba79a265617091f6beb6bfa
    Best match: glfw 1.5.1
    Processing glfw-1.5.1.tar.gz
    Writing /var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/easy_install-l94kn29d/glfw-1.5.1/setup.cfg
    Running glfw-1.5.1/setup.py -q bdist_egg --dist-dir /var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/easy_install-l94kn29d/glfw-1.5.1/egg-dist-tmp-0ge2025g
    zip_safe flag not set; analyzing archive contents...
    glfw.__pycache__.__init__.cpython-36: module references __file__
    creating /private/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/pip-build-wwofnlln/mujoco-py/.eggs/glfw-1.5.1-py3.6.egg
    Extracting glfw-1.5.1-py3.6.egg to /private/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/pip-build-wwofnlln/mujoco-py/.eggs
    
    Installed /private/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/pip-build-wwofnlln/mujoco-py/.eggs/glfw-1.5.1-py3.6.egg
    Searching for pycparser
    Reading https://pypi.python.org/simple/pycparser/
    Downloading https://pypi.python.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz#md5=72370da54358202a60130e223d488136
    Best match: pycparser 2.18
    Processing pycparser-2.18.tar.gz
    Writing /var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/easy_install-rnnk1xg6/pycparser-2.18/setup.cfg
    Running pycparser-2.18/setup.py -q bdist_egg --dist-dir /var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/easy_install-rnnk1xg6/pycparser-2.18/egg-dist-tmp-rr_vw3d5
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    pycparser.ply.__pycache__.lex.cpython-36: module references __file__
    pycparser.ply.__pycache__.lex.cpython-36: module MAY be using inspect.getsourcefile
    pycparser.ply.__pycache__.yacc.cpython-36: module references __file__
    pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.getsourcefile
    pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.stack
    pycparser.ply.__pycache__.ygen.cpython-36: module references __file__
    creating /private/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/pip-build-wwofnlln/mujoco-py/.eggs/pycparser-2.18-py3.6.egg
    Extracting pycparser-2.18-py3.6.egg to /private/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/pip-build-wwofnlln/mujoco-py/.eggs
    
    Installed /private/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/pip-build-wwofnlln/mujoco-py/.eggs/pycparser-2.18-py3.6.egg
    Searching for pillow
    Reading https://pypi.python.org/simple/pillow/
    Downloading https://pypi.python.org/packages/0f/57/25be1a4c2d487942c3ed360f6eee7f41c5b9196a09ca71c54d1a33c968d9/Pillow-5.0.0.tar.gz#md5=08094bc48aae6877c94f8db4b8ee8e52
    Best match: Pillow 5.0.0
    Processing Pillow-5.0.0.tar.gz
    Writing /var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/easy_install-m07jcy4r/Pillow-5.0.0/setup.cfg
    Running Pillow-5.0.0/setup.py -q bdist_egg --dist-dir /var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/easy_install-m07jcy4r/Pillow-5.0.0/egg-dist-tmp-zp7zni8j
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/easy_install-m07jcy4r/Pillow-5.0.0/setup.py", line 792, in <module>
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 161, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 147, in call_command
        self.run_command(cmdname)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
        self.build()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install_lib.py", line 107, in build
        self.run_command('build_ext')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/easy_install-m07jcy4r/Pillow-5.0.0/setup.py", line 580, in build_extensions
    __main__.RequiredDependencyException: jpeg
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
        return func()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/easy_install-m07jcy4r/Pillow-5.0.0/setup.py", line 804, in <module>
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/pip-build-wwofnlln/mujoco-py/setup.py", line 52, in <module>
        cmdclass={'build': Build},
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
        run_setup(setup_script, args)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 251, in run_setup
        raise
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
        return func()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/easy_install-m07jcy4r/Pillow-5.0.0/setup.py", line 804, in <module>
    setuptools.sandbox.UnpickleableException: RequiredDependencyException('\n\nThe headers or library files could not be found for jpeg,\na required dependency when compiling Pillow from source.\n\nPlease see the install instructions at:\n   https://pillow.readthedocs.io/en/latest/installation.html\n\n',)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/tg/_62mj7d56s908l1tbq8f2y9c0000gn/T/pip-build-wwofnlln/mujoco-py/

**Comment by Nichtmister** [comment]
Same problem in console here.
Gym seems to import in anaconda, but when I use an IDLE .py-script. It says:
```
import gym
ModuleNotFoundError: No module named 'gym'
```

**Comment by layssi** [comment]
+1

**Comment by Accessant** [comment]
You don't need mujoco for gym - it's only used by 1/3 of the environments(I don't have it installed). I wrote this earlier - let me know if it helps:

"This is a "the blind leading the blind" answer - to the extent I'm wrong PLEASE correct me.

First, I noticed that you used python 3.6 when universe only supports 3.5. Are you trying to learn to program AI? If so, I recommend...

1) A lot of OpenAI uses - if not Tensorflow - it uses the syntax of Tensorflow, Google's open source AI suite. The first two places to start is the [python programming language](https://developers.google.com/edu/python/introduction) if you need a crash course and then [Tensorflow](https://developers.google.com/machine-learning/crash-course/). Then install gym and baselines.

2) [This guide](https://alliseesolutions.wordpress.com/2017/05/20/set-up-a-machine-learning-workstation-w-anaconda-python/) helps set up gym and baselines. Be sure to use gym 9.5 if you're using universe. Honestly, I recommend not using universe for now. Universe seems to be a time-independent version of gym - if your program runs at 30 frames per second, gym expects to check in thirty times. Universe can roll without expecting that level of precision.

3) Install openai baselines. They're the AI suite. For example, copy `baselines/deepq/experiments/train_carpole.py` and `enjoy_carpole.py` to your coding directory. Use the first agent to train the AI quickly with the gui turned off, and the second agent to view what was trained. Congrats! You're using AI (with the cartpole environment).
