### ISSUE TITLE
Go-vnc fails to start Debian

### ISSUE THREAD

**Issue by szuszi2** [openai/universe#27]
When running the demo code everything works fine until it tries to connect to the vnc server, then everything crashes.
```
import gym
import universe 

env = gym.make('flashgames.DuskDrive-v0')
env.configure(remotes=1)
observation_n = env.reset()

while True:
  action_n = [[('KeyEvent', 'ArrowUp', True)] for ob in observation_n] 
  observation_n, reward_n, done_n, info = env.step(action_n)
  env.render()
```
The output:
```
[2016-12-06 13:18:32,101] Making new env: flashgames.DuskDrive-v0
[2016-12-06 13:18:32,103] Writing logs to file: /tmp/universe-11006.log
[2016-12-06 13:18:32,111] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.1. Run the same thing by hand as: docker run -p 5900:5900 -p 15900:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.1
[2016-12-06 13:18:32,910] Remote closed: address=localhost:5900
[2016-12-06 13:18:32,912] At least one sockets was closed by the remote. Sleeping 1s...
universe-tWuaTp-0 | Setting VNC and rewarder password: openai
universe-tWuaTp-0 | [Tue Dec  6 12:18:33 UTC 2016] Waiting for /tmp/.X11-unix/X0 to be created (try 1/10)
universe-tWuaTp-0 | [Tue Dec  6 12:18:33 UTC 2016] [/usr/local/bin/sudoable-env-setup] Disabling outbound network traffic for none
universe-tWuaTp-0 | [init] [2016-12-06 12:18:33,023] PID 53 launched with command ['sudo', '-H', '-u', 'nobody', 'DISPLAY=:0', 'DBUS_SESSION_BUS_ADDRESS=/dev/null', '/app/universe-envs/controlplane/bin/controlplane.py', '--rewarder-port=15901']
universe-tWuaTp-0 | [init] [2016-12-06 12:18:33,024] init detected end of child process 20 with exit code 0, not killed by signal
universe-tWuaTp-0 | WebSocket server settings:
universe-tWuaTp-0 |   - Listen on :5898
universe-tWuaTp-0 |   - Flash security policy server
universe-tWuaTp-0 |   - No SSL/TLS support (no cert file)
universe-tWuaTp-0 |   - proxying from :5898 to localhost:5900
universe-tWuaTp-0 | [2016-12-06 12:18:33,481] [INFO:root] Starting play_controlplane.py with the following: command=['/app/universe-envs/controlplane/bin/controlplane.py', '--rewarder-port=15901'] args=Namespace(bot_demonstration=False, demonstration=False, env_id=None, idle_timeout=None, integrator_mode=False, no_env=False, no_rewarder=False, no_scorer=False, no_vexpect=False, remotes='vnc://127.0.0.1:5900', rewarder_fps=60, rewarder_port=15901, verbosity=0) env=environ({'DBUS_SESSION_BUS_ADDRESS': '/dev/null', 'SUDO_GID': '0', 'HOSTNAME': '50631ace7f21', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin', 'USER': 'nobody', 'LOGNAME': 'nobody', 'DISPLAY': ':0', 'HOME': '/nonexistent', 'SHELL': '/usr/sbin/nologin', 'SUDO_USER': 'root', 'TERM': 'xterm', 'MAIL': '/var/mail/nobody', 'USERNAME': 'nobody', 'SUDO_COMMAND': '/app/universe-envs/controlplane/bin/controlplane.py --rewarder-port=15901', 'SUDO_UID': '0'})
universe-tWuaTp-0 | [2016-12-06 12:18:33,481] [INFO:root] [EnvStatus] Changing env_state: None (env_id=None) -> None (env_id=None) (episode_id: 0->0, fps=60)
universe-tWuaTp-0 | [2016-12-06 12:18:33,481] [INFO:universe.rewarder.remote] Starting Rewarder on port=15901
universe-tWuaTp-0 | [2016-12-06 12:18:33,484] [INFO:universe.extra.universe.wrappers.logger] Running VNC environments with Logger set to print_frequency=5. To change this, pass "print_frequency=k" or "print_frequency=None" to "env.configure".
universe-tWuaTp-0 | [2016-12-06 12:18:33,485] [INFO:universe.envs.vnc_env] Using the golang VNC implementation
universe-tWuaTp-0 | [2016-12-06 12:18:33,485] [INFO:universe.envs.vnc_env] Using VNCSession arguments: {'start_timeout': 7, 'encoding': 'zrle', 'fine_quality_level': 50, 'compress_level': 9, 'subsample_level': 2}. (Customize by running "env.configure(vnc_kwargs={...})"
universe-tWuaTp-0 | [2016-12-06 12:18:33,485] [INFO:universe.envs.vnc_env] Printed stats will ignore clock skew. (This usually makes sense only when the environment and agent are on the same machine.)
universe-tWuaTp-0 | [2016-12-06 12:18:33,487] [INFO:universe.envs.vnc_env] [0] Connecting to environment: vnc://127.0.0.1:5900 password=openai. Use the browser-based VNC client: http://None/viewer/?password=openai
universe-tWuaTp-0 | [2016-12-06 12:18:33,487] [INFO:universe.extra.universe.envs.vnc_env] [0] Connecting to environment details: vnc_address=127.0.0.1:5900 vnc_password=openai rewarder_address=None rewarder_password=openai
universe-tWuaTp-0 | 2016/12/06 12:18:33 I1206 12:18:33.487607 55 gymvnc.go:417] [0:127.0.0.1:5900] opening connection to VNC server
universe-tWuaTp-0 | [2016-12-06 12:18:33,487] [INFO:root] [EnvStatus] Changing env_state: None (env_id=None) -> resetting (env_id=None) (episode_id: 0->1, fps=60)
universe-tWuaTp-0 | [2016-12-06 12:18:33,487] [INFO:root] [MainThread] Env state: env_id=None episode_id=1
universe-tWuaTp-0 | 2016/12/06 12:18:33 I1206 12:18:33.492326 55 gymvnc.go:550] [0:127.0.0.1:5900] connection established
universe-tWuaTp-0 | [Tue Dec  6 12:18:33 UTC 2016] [/usr/local/bin/sudoable-env-setup] Disabling outbound network traffic for none
universe-tWuaTp-0 | [2016-12-06 12:18:33,500] [INFO:gym_flashgames.launcher] [MainThread] Launching new Chrome process (attempt 0/10)
universe-tWuaTp-0 | [2016-12-06 12:18:33,500] [INFO:root] Replacing selenium_wrapper_server since we currently do it at every episode boundary
universe-tWuaTp-0 | [2016-12-06 12:18:33,605] [selenium_wrapper_server] Calling webdriver.Chrome()
[2016-12-06 13:18:33,915] Remote closed: address=localhost:5900
[2016-12-06 13:18:33,915] Remote closed: address=localhost:15900
[2016-12-06 13:18:33,916] At least one sockets was closed by the remote. Sleeping 1s...
universe-tWuaTp-0 | [2016-12-06 12:18:33,920] [INFO:universe.rewarder.remote] Client connecting: peer=tcp4:127.0.0.1:48346 observer=True
universe-tWuaTp-0 | [2016-12-06 12:18:33,920] [INFO:universe.rewarder.remote] WebSocket connection established
universe-tWuaTp-0 | [init] [2016-12-06 12:18:34,007] init detected end of child process 17 with exit code 0, not killed by signal
universe-tWuaTp-0 | [init] [2016-12-06 12:18:34,679] init detected end of child process 107 with exit code 0, not killed by signal
universe-tWuaTp-0 | [init] [2016-12-06 12:18:34,679] init detected end of child process 106 with exit code 0, not killed by signal
[2016-12-06 13:18:34,917] Using the golang VNC implementation
[2016-12-06 13:18:34,918] Using VNCSession arguments: {'subsample_level': 2, 'start_timeout': 7, 'fine_quality_level': 50, 'encoding': 'tight'}. (Customize by running "env.configure(vnc_kwargs={...})"
[2016-12-06 13:18:34,921] [0] Connecting to environment: vnc://localhost:5900 password=openai. Use the browser-based VNC client: http://localhost:15900/viewer/?password=openai
2016/12/06 13:18:34 I1206 13:18:34.922135 11006 gymvnc.go:417] [0:localhost:5900] opening connection to VNC server
2016/12/06 13:18:34 I1206 13:18:34.92497 11006 gymvnc.go:550] [0:localhost:5900] connection established
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f3130eaceb0 pc=0x7f3130eaceb0]

runtime stack:
runtime.throw(0x7f31724358df, 0x2a)
	/usr/lib/go-1.7/src/runtime/panic.go:566 +0x97
runtime.sigpanic()
	/usr/lib/go-1.7/src/runtime/sigpanic_unix.go:12 +0x2d0

goroutine 17 [syscall, locked to thread]:
runtime.cgocall(0x7f317241e09a, 0xc420040bc0, 0xc400000000)
	/usr/lib/go-1.7/src/runtime/cgocall.go:131 +0x116 fp=0xc420040b78 sp=0xc420040b38
github.com/openai/go-vncdriver/vendor/github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwCreateWindow(0x30000000400, 0x562236267a10, 0x0, 0x0, 0x0)
	??:0 +0x50 fp=0xc420040bc0 sp=0xc420040b78
github.com/openai/go-vncdriver/vendor/github.com/go-gl/glfw/v3.2/glfw.CreateWindow(0x400, 0x300, 0xc42009c0c0, 0x25, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/vendor/github.com/go-gl/glfw/v3.2/glfw/window.go:272 +0x1ad fp=0xc420040c48 sp=0xc420040bc0
github.com/openai/go-vncdriver/vncgl.(*VNCGL).Init(0xc4205ae0c0, 0x7f3103000400, 0xc42009c0c0, 0x25, 0xc4200f0000, 0xc0000, 0xc0000, 0xc420012b80, 0xc42059a114)
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/vncgl/vncgl.go:58 +0x6f fp=0xc420040cb8 sp=0xc420040c48
github.com/openai/go-vncdriver/gymvnc.(*VNCSession).Render(0xc420092140, 0xc420014c00, 0xc42059a114, 0x1)
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/gymvnc/gymvnc.go:244 +0x285 fp=0xc420040d50 sp=0xc420040cb8
github.com/openai/go-vncdriver/gymvnc.(*VNCBatch).Render(0xc4200300a8, 0xc42059a114, 0x1, 0x0, 0x0, 0x7f31726ee880)
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/gymvnc/gymvnc.go:655 +0x7a fp=0xc420040db8 sp=0xc420040d50
main.GoVNCDriver_VNCSession_render(0x7f3166b73b90, 0x7f3165865910, 0x0, 0x0)
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/main.go:412 +0x2c9 fp=0xc420040e50 sp=0xc420040db8
main._cgoexpwrap_f4a5df30d895_GoVNCDriver_VNCSession_render(0x7f3166b73b90, 0x7f3165865910, 0x0, 0x0)
	??:0 +0x74 fp=0xc420040e80 sp=0xc420040e50
runtime.call32(0x0, 0x7ffe501fab98, 0x7ffe501fac50, 0x20)
	/usr/lib/go-1.7/src/runtime/asm_amd64.s:479 +0x4e fp=0xc420040eb0 sp=0xc420040e80
runtime.cgocallbackg1(0x0)
	/usr/lib/go-1.7/src/runtime/cgocall.go:283 +0x1a1 fp=0xc420040f28 sp=0xc420040eb0
runtime.cgocallbackg(0x0)
	/usr/lib/go-1.7/src/runtime/cgocall.go:170 +0x86 fp=0xc420040f90 sp=0xc420040f28
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.7/src/runtime/asm_amd64.s:728 +0x71 fp=0xc420040fb0 sp=0xc420040f90
runtime.goexit()
	/usr/lib/go-1.7/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420040fb8 sp=0xc420040fb0

goroutine 5 [select]:
github.com/openai/go-vncdriver/gymvnc.(*VNCSession).connect(0xc420092140, 0xc42001a540, 0x0, 0x0)
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/gymvnc/gymvnc.go:566 +0x1137
github.com/openai/go-vncdriver/gymvnc.(*VNCSession).start.func1(0xc420092140, 0xc42001a540)
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/gymvnc/gymvnc.go:149 +0x37
created by github.com/openai/go-vncdriver/gymvnc.(*VNCSession).start
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/gymvnc/gymvnc.go:157 +0x8f

goroutine 18 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.7/src/runtime/asm_amd64.s:2086 +0x1

goroutine 6 [chan receive]:
github.com/openai/go-vncdriver/gymvnc.(*VNCSession).start.func2(0xc420092140)
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/gymvnc/gymvnc.go:160 +0x61
created by github.com/openai/go-vncdriver/gymvnc.(*VNCSession).start
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/gymvnc/gymvnc.go:165 +0xb1

goroutine 20 [IO wait]:
net.runtime_pollWait(0x7f316400ff00, 0x72, 0x8)
	/usr/lib/go-1.7/src/runtime/netpoll.go:160 +0x5b
net.(*pollDesc).wait(0xc4200ca1b0, 0x72, 0xc4203449f8, 0xc420012300)
	/usr/lib/go-1.7/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).waitRead(0xc4200ca1b0, 0x7f31728416c0, 0xc420012300)
	/usr/lib/go-1.7/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc4200ca150, 0xc4203343f8, 0x1, 0x8, 0x0, 0x7f31728416c0, 0xc420012300)
	/usr/lib/go-1.7/src/net/fd_unix.go:243 +0x1a3
net.(*conn).Read(0xc4200d6020, 0xc4203343f8, 0x1, 0x8, 0x0, 0x0, 0x0)
	/usr/lib/go-1.7/src/net/net.go:173 +0x72
io.ReadAtLeast(0x7f316400ffc0, 0xc4200d6020, 0xc4203343f8, 0x1, 0x8, 0x1, 0x7f3172706440, 0x1, 0xc4203343f8)
	/usr/lib/go-1.7/src/io/io.go:307 +0xa6
io.ReadFull(0x7f316400ffc0, 0xc4200d6020, 0xc4203343f8, 0x1, 0x8, 0xc420334022, 0xc4203343a0, 0x7f31727665a0)
	/usr/lib/go-1.7/src/io/io.go:325 +0x5a
encoding/binary.Read(0x7f316400ffc0, 0xc4200d6020, 0x7f3172843ce0, 0x7f3172873670, 0x7f31726f7b80, 0xc4203343f0, 0x0, 0x0)
	/usr/lib/go-1.7/src/encoding/binary/binary.go:168 +0x122
github.com/openai/go-vncdriver/vncclient.(*ClientConn).mainLoop(0xc4200ea000)
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/vncclient/client.go:567 +0x46c
created by github.com/openai/go-vncdriver/vncclient.Client
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/vncclient/client.go:115 +0x18a

goroutine 21 [select]:
github.com/openai/go-vncdriver/gymvnc.(*VNCSession).connect.func2(0xc4200d4060, 0xc420092140)
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/gymvnc/gymvnc.go:472 +0x21f
created by github.com/openai/go-vncdriver/gymvnc.(*VNCSession).connect
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/gymvnc/gymvnc.go:477 +0x6b9

goroutine 7 [select]:
github.com/openai/go-vncdriver/gymvnc.(*VNCSession).maintainFrameBuffer(0xc420092140, 0xc42001a540, 0x0, 0x0)
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/gymvnc/gymvnc.go:359 +0x61d
github.com/openai/go-vncdriver/gymvnc.(*VNCSession).connect.func3(0xc420092140, 0xc42001a540)
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/gymvnc/gymvnc.go:555 +0x37
created by github.com/openai/go-vncdriver/gymvnc.(*VNCSession).connect
	/tmp/pip-build-ma4U7r/go-vncdriver/.build/src/github.com/openai/go-vncdriver/gymvnc/gymvnc.go:563 +0xc63
Aborted

```

**Comment by jeremyschlatter** [comment]
Woah, interesting. Quick Google search suggests this might be a Go bug:

https://github.com/golang/go/issues/16331

Are you on Go 1.7.4? If not, mind upgrading and checking if that solves the problem?

I'll see if we can track down where it's coming from and work around it.

**Comment by szuszi2** [comment]
I installed Go 1.7.4
```
go version
go version go1.7.4 linux/amd64

```

Still gives the same error :(
