### ISSUE TITLE
environment crash

### ISSUE THREAD

**Issue by jjkke88** [openai/universe#31]
` sudo docker run -p 5901:5900 -p 15901:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.1`
And then I use vnc to connect to the docker image. 
```
 update queue max of 60 reached; pausing further updates
[unpack-lfs] [2016-12-07 03:30:30,215] Finished running git lfs pull
[unpack-lfs] [2016-12-07 03:30:30,216] git lfs pull failed; detected from contents. stdout=b'\rGit LFS: (0 of 1 files) 0 B / 9.52 MB                                          \n' stderr=b'http: Post https://api.github.com/lfs/openai/universe-flashgames-build/objects/batch: net/http: TLS handshake timeout\n'
[unpack-lfs] [2016-12-07 03:30:30,286] unpack failed
Traceback (most recent call last):
  File "/app/universe-envs/controlplane/bin/controlplane.py", line 732, in <module>
    sys.exit(main())
  File "/app/universe-envs/controlplane/bin/controlplane.py", line 724, in main
    error_buffer.blocking_check(timeout=60)
  File "/app/universe/universe/utils/__init__.py", line 56, in blocking_check
    self.check(timeout)
  File "/app/universe/universe/utils/__init__.py", line 48, in check
    raise error
universe.error.Error: Traceback (most recent call last):
  File "/app/universe-envs/controlplane/bin/controlplane.py", line 90, in run
    self.do_run()
  File "/app/universe-envs/controlplane/bin/controlplane.py", line 96, in do_run
    self.process_control_messages()
  File "/app/universe-envs/controlplane/bin/controlplane.py", line 137, in process_control_messages
    self.process_rpc(context, message)
  File "/app/universe-envs/controlplane/bin/controlplane.py", line 202, in process_rpc
    self.reset()
  File "/app/universe-envs/controlplane/bin/controlplane.py", line 243, in reset
    self.env_launcher.reset()
  File "/app/universe-envs/flashgames/gym_flashgames/launcher.py", line 38, in reset
    self._git_lfs_pull()
  File "/app/universe-envs/flashgames/gym_flashgames/launcher.py", line 69, in _git_lfs_pull
    subprocess.check_call(['sudo', '/usr/local/bin/sudoable-env-setup', 'git-lfs', self.controlplane_spec.id])
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/usr/local/bin/sudoable-env-setup', 'git-lfs', 'flashgames.DuskDrive-v0']' returned non-zero exit status 1
[init] [2016-12-07 03:30:30,463] init detected end of child process 55 with exit code 1, not killed by signal

```

**Comment by gdb** [comment]
Looks like you weren't able to fetch the SWFs from Github: ```https://api.github.com/lfs/openai/universe-flashgames-build/objects/batch: net/http: TLS handshake timeout```.

Are you behind a firewall that blocks traffic to the Github API? Can you `curl` that URL? Is the error persistent?

**Comment by gdb** [comment]
(Closing this for now.)
