### ISSUE TITLE
go_vncdriver crashes on Ubuntu 16 default installation

### ISSUE THREAD

**Issue by kler** [openai/universe#35]
When executing the code from section [Run your first agent](https://github.com/openai/universe#run-your-first-agent) universe crashes
_(sounds more horrible than it actually is! ☺)_

Problem is with go_vncdriver which sais:

`go_vncdriver was installed without OpenGL support. See https://github.com/openai/go-vncdriver for details on how debug.`

I tried to follow the instruction in the link provided by go_vncdriver, but it builds without errors.
I believe that I followed the install instruction correctly, and I'm on Ubuntu 16 inside VirtualBox.

`Linux ubuntu-16 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Log attached:
[go-vncdriver-problem-log.txt](https://github.com/openai/universe/files/636641/go-vncdriver-problem-log.txt)

**Comment by TriRpi** [comment]
I used the following to solve this:

    sudo apt-get install libx11-dev libxcursor-dev libxrandr-dev \
      libxinerama-dev libxi-dev libxxf86vm-dev libgl1-mesa-dev \
      mesa-common-dev

Then reinstalling everything (or only reinstalling go_vncdriver).

**Comment by vivekpatani** [comment]
I got the same issue as @kler maybe?

Log:
```
Terminal Output:

 flipswitch@devcenter  ~/junkyard/universe-example  python script.py                                              
[2016-12-07 16:24:55,538] Making new env: flashgames.DuskDrive-v0
[2016-12-07 16:24:55,543] Writing logs to file: /tmp/universe-29987.log
[2016-12-07 16:24:55,561] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.3. Run the same thing by hand as: docker run -p 5900:5900 -p 15900:15900 --ipc host --privileged --cap-add SYS_ADMIN quay.io/openai/universe.flashgames:0.20.3
[2016-12-07 16:24:55,811] Remote closed: address=localhost:5900
[2016-12-07 16:24:55,812] At least one sockets was closed by the remote. Sleeping 1s...
universe-5p1mSD-0 | Setting VNC and rewarder password: openai
universe-5p1mSD-0 | [Wed Dec  7 21:24:55 UTC 2016] Waiting for /tmp/.X11-unix/X0 to be created (try 1/10)
universe-5p1mSD-0 | [Wed Dec  7 21:24:55 UTC 2016] [/usr/local/bin/sudoable-env-setup] Disabling outbound network traffic for none
universe-5p1mSD-0 | [init] [2016-12-07 21:24:55,937] PID 54 launched with command ['sudo', '-H', '-u', 'nobody', 'DISPLAY=:0', 'DBUS_SESSION_BUS_ADDRESS=/dev/null', '/app/universe-envs/controlplane/bin/controlplane.py', '--rewarder-port=15901']
universe-5p1mSD-0 | [init] [2016-12-07 21:24:55,937] init detected end of child process 22 with exit code 0, not killed by signal
universe-5p1mSD-0 | WebSocket server settings:
universe-5p1mSD-0 |   - Listen on :5898
universe-5p1mSD-0 |   - Flash security policy server
universe-5p1mSD-0 |   - No SSL/TLS support (no cert file)
universe-5p1mSD-0 |   - proxying from :5898 to localhost:5900
universe-5p1mSD-0 | [2016-12-07 21:24:56,481] [INFO:root] Starting play_controlplane.py with the following: command=['/app/universe-envs/controlplane/bin/controlplane.py', '--rewarder-port=15901'] args=Namespace(bot_demonstration=False, demonstration=False, env_id=None, idle_timeout=None, integrator_mode=False, no_env=False, no_rewarder=False, no_scorer=False, no_vexpect=False, remotes='vnc://127.0.0.1:5900', rewarder_fps=60, rewarder_port=15901, verbosity=0) env=environ({'USER': 'nobody', 'SUDO_UID': '0', 'HOME': '/nonexistent', 'DISPLAY': ':0', 'SUDO_COMMAND': '/app/universe-envs/controlplane/bin/controlplane.py --rewarder-port=15901', 'DBUS_SESSION_BUS_ADDRESS': '/dev/null', 'MAIL': '/var/mail/nobody', 'SUDO_USER': 'root', 'SUDO_GID': '0', 'LOGNAME': 'nobody', 'HOSTNAME': '90e87f486fc3', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin', 'TERM': 'xterm', 'SHELL': '/usr/sbin/nologin', 'USERNAME': 'nobody'})
universe-5p1mSD-0 | [2016-12-07 21:24:56,481] [INFO:root] [EnvStatus] Changing env_state: None (env_id=None) -> None (env_id=None) (episode_id: 0->0, fps=60)
universe-5p1mSD-0 | [2016-12-07 21:24:56,481] [INFO:universe.rewarder.remote] Starting Rewarder on port=15901
universe-5p1mSD-0 | [2016-12-07 21:24:56,484] [INFO:universe.extra.universe.wrappers.logger] Running VNC environments with Logger set to print_frequency=5. To change this, pass "print_frequency=k" or "print_frequency=None" to "env.configure".
universe-5p1mSD-0 | [2016-12-07 21:24:56,487] [INFO:universe.envs.vnc_env] Using the golang VNC implementation
universe-5p1mSD-0 | [2016-12-07 21:24:56,488] [INFO:universe.envs.vnc_env] Using VNCSession arguments: {'subsample_level': 2, 'encoding': 'zrle', 'fine_quality_level': 50, 'compress_level': 9, 'start_timeout': 7}. (Customize by running "env.configure(vnc_kwargs={...})"
universe-5p1mSD-0 | [2016-12-07 21:24:56,488] [INFO:universe.envs.vnc_env] Printed stats will ignore clock skew. (This usually makes sense only when the environment and agent are on the same machine.)
universe-5p1mSD-0 | [2016-12-07 21:24:56,490] [INFO:universe.envs.vnc_env] [0] Connecting to environment: vnc://127.0.0.1:5900 password=openai. Use the browser-based VNC client: http://None/viewer/?password=openai
universe-5p1mSD-0 | [2016-12-07 21:24:56,491] [INFO:universe.extra.universe.envs.vnc_env] [0] Connecting to environment details: vnc_address=127.0.0.1:5900 vnc_password=openai rewarder_address=None rewarder_password=openai
universe-5p1mSD-0 | 2016/12/07 21:24:56 I1207 21:24:56.491213 55 gymvnc.go:417] [0:127.0.0.1:5900] opening connection to VNC server
universe-5p1mSD-0 | [2016-12-07 21:24:56,491] [INFO:root] [EnvStatus] Changing env_state: None (env_id=None) -> resetting (env_id=None) (episode_id: 0->1, fps=60)
universe-5p1mSD-0 | [2016-12-07 21:24:56,491] [INFO:root] [MainThread] Env state: env_id=None episode_id=1
universe-5p1mSD-0 | 2016/12/07 21:24:56 I1207 21:24:56.499314 55 gymvnc.go:550] [0:127.0.0.1:5900] connection established
universe-5p1mSD-0 | [Wed Dec  7 21:24:56 UTC 2016] [/usr/local/bin/sudoable-env-setup] Disabling outbound network traffic for none
universe-5p1mSD-0 | [2016-12-07 21:24:56,521] [INFO:gym_flashgames.launcher] [MainThread] Launching new Chrome process (attempt 0/10)
universe-5p1mSD-0 | [2016-12-07 21:24:56,521] [INFO:root] Replacing selenium_wrapper_server since we currently do it at every episode boundary
universe-5p1mSD-0 | [2016-12-07 21:24:56,628] [selenium_wrapper_server] Calling webdriver.Chrome()
[2016-12-07 16:24:56,813] Remote closed: address=localhost:5900
[2016-12-07 16:24:56,814] Remote closed: address=localhost:15900
[2016-12-07 16:24:56,814] At least one sockets was closed by the remote. Sleeping 1s...
universe-5p1mSD-0 | [2016-12-07 21:24:56,816] [INFO:universe.rewarder.remote] Client connecting: peer=tcp4:127.0.0.1:36806 observer=True
universe-5p1mSD-0 | [2016-12-07 21:24:56,817] [INFO:universe.rewarder.remote] WebSocket connection established
universe-5p1mSD-0 | [init] [2016-12-07 21:24:56,879] init detected end of child process 16 with exit code 0, not killed by signal
[2016-12-07 16:24:57,816] Using the golang VNC implementation
[2016-12-07 16:24:57,816] Using VNCSession arguments: {'subsample_level': 2, 'encoding': 'tight', 'start_timeout': 7, 'fine_quality_level': 50}. (Customize by running "env.configure(vnc_kwargs={...})"
universe-5p1mSD-0 | [2016-12-07 21:24:57,817] [INFO:universe.rewarder.remote] WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
[2016-12-07 16:24:57,846] [0] Connecting to environment: vnc://localhost:5900 password=openai. Use the browser-based VNC client: http://localhost:15900/viewer/?password=openai
2016/12/07 16:24:57 I1207 16:24:57.847261 29987 gymvnc.go:417] [0:localhost:5900] opening connection to VNC server
2016/12/07 16:24:57 I1207 16:24:57.863795 29987 gymvnc.go:550] [0:localhost:5900] connection established
universe-5p1mSD-0 | [2016-12-07 21:24:57,890] [INFO:universe.rewarder.remote] Client connecting: peer=tcp4:127.0.0.1:36852 observer=False
universe-5p1mSD-0 | [2016-12-07 21:24:57,890] [INFO:universe.rewarder.remote] WebSocket connection established
Traceback (most recent call last):
  File "script.py", line 11, in <module>
    env.render()
  File "/opt/anaconda3/lib/python3.5/site-packages/gym/core.py", line 192, in render
    return self._render(mode=mode, close=close)
  File "/opt/anaconda3/lib/python3.5/site-packages/gym/core.py", line 342, in _render
    return self.env.render(mode, close)
  File "/opt/anaconda3/lib/python3.5/site-packages/gym/core.py", line 192, in render
    return self._render(mode=mode, close=close)
  File "/home/flipswitch/junkyard/universe/universe/wrappers/render.py", line 49, in _render
    return self.env.render(mode=mode, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.5/site-packages/gym/core.py", line 192, in render
    return self._render(mode=mode, close=close)
  File "/opt/anaconda3/lib/python3.5/site-packages/gym/core.py", line 342, in _render
    return self.env.render(mode, close)
  File "/opt/anaconda3/lib/python3.5/site-packages/gym/core.py", line 192, in render
    return self._render(mode=mode, close=close)
  File "/home/flipswitch/junkyard/universe/universe/envs/vnc_env.py", line 533, in _render
    self.vnc_session.render(self.connection_names[0])
go_vncdriver.Error: /tmp/pip-build-ft2ong1q/go-vncdriver/.build/src/github.com/openai/go-vncdriver/main.go:387: go_vncdriver was installed without OpenGL support. See https://github.com/openai/go-vncdriver for details on how debug.
universe-5p1mSD-0 | [2016-12-07 21:24:57,993] [selenium_wrapper_server] Call to webdriver.Chrome() completed: 1.36s
universe-5p1mSD-0 | [2016-12-07 21:24:57,993] [INFO:gym_flashgames.launcher] [MainThread] Navigating browser to url=http://localhost
[2016-12-07 16:24:58,039] Killing and removing container: id=90e87f486fc35c283385eef7bcffcd2ee803c0495563632fb2f054ccede18456. (If this command errors, you can always kill all automanaged environments on this Docker daemon via: docker rm -f $(docker ps -q -a -f 'label=com.openai.automanaged=true')


Log file:

[2016-12-07 16:24:55,561] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.3. Run the same thing by hand as: docker run -p 5900:5900 -p 15900:15900 --ipc host --privileged --cap-add SYS_ADMIN quay.io/openai/universe.flashgames:0.20.3
[2016-12-07 16:24:55,811] Remote closed: address=localhost:5900
[2016-12-07 16:24:55,812] At least one sockets was closed by the remote. Sleeping 1s...
[2016-12-07 16:24:56,813] Remote closed: address=localhost:5900
[2016-12-07 16:24:56,814] Remote closed: address=localhost:15900
[2016-12-07 16:24:56,814] At least one sockets was closed by the remote. Sleeping 1s...
[2016-12-07 16:24:57,816] Using the golang VNC implementation
[2016-12-07 16:24:57,816] Using VNCSession arguments: {'subsample_level': 2, 'encoding': 'tight', 'start_timeout': 7, 'fine_quality_level': 50}. (Customize by running "env.configure(vnc_kwargs={...})"
[2016-12-07 16:24:57,846] [0] Connecting to environment: vnc://localhost:5900 password=openai. Use the browser-based VNC client: http://localhost:15900/viewer/?password=openai
[2016-12-07 16:24:57,846] [0] Connecting to environment details: vnc_address=localhost:5900 vnc_password=openai rewarder_address=localhost:15900 rewarder_password=openai
[2016-12-07 16:24:57,855] [0:localhost:5900] RewardBuffer advancing: masking until reset completes; setting current_episode_id=None
[2016-12-07 16:24:57,864] [0:localhost:5900] RewardBuffer: Creating new RewardState for episode_id=None
[2016-12-07 16:24:57,864] [0:localhost:5900] RewardState: popping reward 0.0 from episode_id None
[2016-12-07 16:24:57,888] [0:localhost:5900] Rewarder TCP connection established
[2016-12-07 16:24:57,897] [0:localhost:5900] Websocket client successfully connected
[2016-12-07 16:24:57,897] [0:localhost:5900] Starting network calibration with ntpdate -q -p 8 localhost
[2016-12-07 16:24:57,907] [0:localhost:5900] Received payload: b'{"headers":{"message_id":0,"episode_id":"1","sent_at":1481145897.8908731937},"body":{"fps":60,"env_state":"resetting","env_id":null},"method":"v0.env.describe"}'
[2016-12-07 16:24:57,908] [0:localhost:5900] RewardBuffer: Creating new RewardState for episode_id=1
[2016-12-07 16:24:57,909] [0:localhost:5900] Received v0.env.describe: env_id=None env_state=resetting episode_id=1
[2016-12-07 16:24:57,913] [0:localhost:5900] RewardBuffer: Initial env_state: resetting (env_id=None) (episode_id: 1, fps=60, masked=True, current_episode_id=None)
[2016-12-07 16:24:58,039] Killing and removing container: id=90e87f486fc35c283385eef7bcffcd2ee803c0495563632fb2f054ccede18456. (If this command errors, you can always kill all automanaged environments on this Docker daemon via: docker rm -f $(docker ps -q -a -f 'label=com.openai.automanaged=true')
[2016-12-07 16:24:58,049] [0:localhost:5900] Received error for connection which has not been fully initialized: Lost connection: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake) (clean=False code=1006)
[2016-12-07 16:24:58,050] [0:localhost:5900] Recording fatal error for connection: Lost connection: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake) (clean=False code=1006)
```

Solution provided by @TriRpi did not work for me.

**Comment by kler** [comment]
Actually @TriRpi was right.

Besides the installation of the libgl, go-vncdriver needs to be built and installed using pip pointing to the directory where it was built.

**Solution**
```
# Install deps
sudo apt-get install libx11-dev libxcursor-dev libxrandr-dev \
  libxinerama-dev libxi-dev libxxf86vm-dev libgl1-mesa-dev \
  mesa-common-dev

# Fetch go-vncdriver source
git clone https://github.com/openai/go-vncdriver.git

# Step into dir
cd go-vncdriver

# Build
./build.py

# Install 
sudo -H pip install --upgrade --no-deps --force-reinstall -e ./
```

**Comment by vivekpatani** [comment]
That worked for me, thanks!
