### ISSUE TITLE
ubuntu 14.04  environments  crashed!

### ISSUE THREAD

**Issue by kernel8liang** [openai/universe#36]
on ubuntu 14.04 default installed.  run example guide by "get start", the widow has poped up, but wait for a 
while, it crashed.

```python

Traceback (most recent call last):
  File "first.py", line 10, in <module>
    observation_n, reward_n, done_n, info = env.step(action_n)
  File "/home/liang/anaconda2/lib/python2.7/site-packages/gym/core.py", line 122, in step
    observation, reward, done, info = self._step(action)
  File "/home/liang/workspace/universe/universe/wrappers/timer.py", line 20, in _step
    observation_n, reward_n, done_n, info = self.env.step(action_n)
  File "/home/liang/anaconda2/lib/python2.7/site-packages/gym/core.py", line 122, in step
    observation, reward, done, info = self._step(action)
  File "/home/liang/workspace/universe/universe/wrappers/render.py", line 30, in _step
    observation_n, reward_n, done_n, info_n = self.env.step(action_n)
  File "/home/liang/anaconda2/lib/python2.7/site-packages/gym/core.py", line 122, in step
    observation, reward, done, info = self._step(action)
  File "/home/liang/workspace/universe/universe/wrappers/throttle.py", line 117, in _step
    observation_n, reward_n, done_n, info = self._substep(action_n)
  File "/home/liang/workspace/universe/universe/wrappers/throttle.py", line 132, in _substep
    observation_n, reward_n, done_n, info = self.env.step(action_n)
  File "/home/liang/anaconda2/lib/python2.7/site-packages/gym/core.py", line 122, in step
    observation, reward, done, info = self._step(action)
  File "/home/liang/workspace/universe/universe/envs/vnc_env.py", line 447, in _step
    self._handle_crashed_n(info_n)
  File "/home/liang/workspace/universe/universe/envs/vnc_env.py", line 518, in _handle_crashed_n
    raise error.Error('{}/{} environments have crashed! Most recent error: {}'.format(len(self.crashed), self.n, errors))
universe.error.Error: 1/1 environments have crashed! Most recent error: {'0': 'Rewarder session failed: Lost connection: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake) (clean=False code=1006)'}


```

did i do anything wrong?

**Comment by Baschdl** [comment]
Maybe duplicate to #6

**Comment by kernel8liang** [comment]
ok, I am watching #6.
