### ISSUE TITLE
json: cannot unmarshal bool into Go value of type docker.APIErrors

### ISSUE THREAD

**Issue by Supernerd11** [openai/universe#4]
I cannot get universe to start. I get the following error

```
jonathan@ouran-high-school-host-club ~/P/p/universe-test> python test.py                 
[2016-12-05 13:22:27,398] Making new env: flashgames.DuskDrive-v0
[2016-12-05 13:22:27,402] Writing logs to file: /tmp/universe-583.log
[2016-12-05 13:22:27,413] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.1. Run the same thing by hand as: docker run -p 5900:5900 -p 15900:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.1
[2016-12-05 13:22:27,417] Image quay.io/openai/universe.flashgames:0.20.1 not present locally; pulling
Trying to pull repository quay.io/openai/universe.flashgames ... 
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    env.configure(remotes=1) # automatically creates a local docker container
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "/home/jonathan/Programming/python3/universe/universe/vectorized/core.py", line 57, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 350, in _configure
    return self.env.configure(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "/home/jonathan/Programming/python3/universe/universe/wrappers/render.py", line 18, in _configure
    super(Render, self)._configure(**kwargs)
  File "/home/jonathan/Programming/python3/universe/universe/vectorized/core.py", line 57, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 350, in _configure
    return self.env.configure(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "/home/jonathan/Programming/python3/universe/universe/wrappers/throttle.py", line 27, in _configure
    super(Throttle, self)._configure(**kwargs)
  File "/home/jonathan/Programming/python3/universe/universe/vectorized/core.py", line 57, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 350, in _configure
    return self.env.configure(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "/home/jonathan/Programming/python3/universe/universe/envs/vnc_env.py", line 192, in _configure
    api_key=api_key,
  File "/home/jonathan/Programming/python3/universe/universe/remotes/build.py", line 19, in build
    n=n,
  File "/home/jonathan/Programming/python3/universe/universe/remotes/docker_remote.py", line 54, in __init__
    self._start()
  File "/home/jonathan/Programming/python3/universe/universe/remotes/docker_remote.py", line 81, in _start
    [instance.start() for instance in self.instances]
  File "/home/jonathan/Programming/python3/universe/universe/remotes/docker_remote.py", line 219, in start
    self._spawn()
  File "/home/jonathan/Programming/python3/universe/universe/remotes/docker_remote.py", line 249, in _spawn
    self._pull_image()
  File "/home/jonathan/Programming/python3/universe/universe/remotes/docker_remote.py", line 258, in _pull_image
    progress_stream.stream_output(output, sys.stdout))
  File "/home/jonathan/Programming/python3/universe/universe/remotes/compose/progress_stream.py", line 23, in stream_output
    print_output_event(event, stream, is_terminal)
  File "/home/jonathan/Programming/python3/universe/universe/remotes/compose/progress_stream.py", line 58, in print_output_event
    raise StreamOutputError(event['errorDetail']['message'])
universe.remotes.compose.progress_stream.StreamOutputError: json: cannot unmarshal bool into Go value of type docker.APIErrors
```

**Comment by gdb** [comment]
Interesting. Can you try running the Docker and Python process in separate window? So:

```docker run -p 5900:5900 -p 15900:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.1```

And then something like this:

```import gym
import universe

env = gym.make('flashgames.DuskDrive-v0')
env.configure(remotes='vnc://localhost:5900+15900')
observation_n = env.reset()

while True:
  # your agent generates action_n at 60 frames per second
  action_n = [[('KeyEvent', 'ArrowUp', True)] for ob in observation_n]
  observation_n, reward_n, done_n, info = env.step(action_n)
  env.render()
```

Does the above work?

This looks like a potential issue with your local Docker daemon. What's the output of `docker version`?

**Comment by Supernerd11** [comment]
It seems to be docker failing to pull the ```quay.io/openai/universe.flashgames``` repo. I canät start the docker server with error:
 ```
/usr/bin/docker-current: json: cannot unmarshal bool into Go value of type docker.APIErrors.
See '/usr/bin/docker-current run --help'.
```

**Comment by gdb** [comment]
Ok, good to know. That seems like a Docker issue — we're probably not the best to help with it. Perhaps try Googling around, or upgrading Docker?
