### ISSUE TITLE
ubuntu 16.04 runtime.yml  error

### ISSUE THREAD

**Issue by prakashyadav008** [openai/universe#41]
i have all the packages for universe but it is having some errors when i try to import it.
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/universe/__init__.py", line 21, in <module>
    from universe import error, envs
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/universe/envs/__init__.py", line 1, in <module>
    import universe.envs.vnc_env
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/universe/envs/vnc_env.py", line 20, in <module>
    from universe.runtimes import registration
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/universe/runtimes/__init__.py", line 6, in <module>
    with open(os.path.join(os.path.dirname(__file__), '../../runtimes.yml')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/prakash/anaconda3/lib/python3.5/site-packages/universe/runtimes/../../runtimes.yml'
`

**Comment by hmate9** [comment]
I have the same problem.

**Comment by hmate9** [comment]
Issue solved by doing the following:

```
pip uninstall universe
git clone https://github.com/openai/universe.git
cd universe
pip install -e .
```

**Comment by jeremyschlatter** [comment]
I just fixed the PyPI package. `pip install universe` should now work, as well.
