### ISSUE TITLE
'Run your first agent' example not work~~

### ISSUE THREAD

**Issue by jomyhuang** [openai/universe#48]
I try lot times run demo code, but only 1 time success.
may fetch timeout?
universe-ezK9kg-0 | [unpack-lfs] [2016-12-10 03:48:27,396] Fetching files: git lfs pull -I git-lfs/flashgames.DuskDrive-v0.tar.gz

--
(vml) universe $ python train.py
[2016-12-10 11:48:10,041] Making new env: flashgames.DuskDrive-v0
[2016-12-10 11:48:10,043] Writing logs to file: /tmp/universe-2533.log
[2016-12-10 11:48:10,079] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.7. Run the same thing by hand as: docker run -p 5900:5900 -p 15900:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.7
[2016-12-10 11:48:10,763] Remote closed: address=localhost:5900
[2016-12-10 11:48:10,764] At least one sockets was closed by the remote. Sleeping 1s...
universe-ezK9kg-0 | Setting VNC and rewarder password: openai
universe-ezK9kg-0 | [Sat Dec 10 03:48:10 UTC 2016] Waiting for /tmp/.X11-unix/X0 to be created (try 1/10)
universe-ezK9kg-0 | [Sat Dec 10 03:48:10 UTC 2016] [/usr/local/bin/sudoable-env-setup] Disabling outbound network traffic for none
universe-ezK9kg-0 | [init] [2016-12-10 03:48:10,989] PID 60 launched with command ['sudo', '-H', '-u', 'nobody', 'DISPLAY=:0', 'DBUS_SESSION_BUS_ADDRESS=/dev/null', '/app/universe-envs/controlplane/bin/controlplane.py', '--rewarder-port=15901']
universe-ezK9kg-0 | [init] [2016-12-10 03:48:10,989] init detected end of child process 18 with exit code 0, not killed by signal
universe-ezK9kg-0 | WebSocket server settings:
universe-ezK9kg-0 |   - Listen on :5898
universe-ezK9kg-0 |   - Flash security policy server
universe-ezK9kg-0 |   - No SSL/TLS support (no cert file)
universe-ezK9kg-0 |   - proxying from :5898 to localhost:5900
universe-ezK9kg-0 | [2016-12-10 03:48:11,501] [INFO:root] Starting play_controlplane.py with the following: command=['/app/universe-envs/controlplane/bin/controlplane.py', '--rewarder-port=15901'] args=Namespace(bot_demonstration=False, demonstration=False, env_id=None, idle_timeout=None, integrator_mode=False, no_env=False, no_rewarder=False, no_scorer=False, no_vexpect=False, remotes='vnc://127.0.0.1:5900', rewarder_fps=60, rewarder_port=15901, verbosity=0) env=environ({'HOME': '/nonexistent', 'SHELL': '/usr/sbin/nologin', 'SUDO_COMMAND': '/app/universe-envs/controlplane/bin/controlplane.py --rewarder-port=15901', 'SUDO_GID': '0', 'MAIL': '/var/mail/nobody', 'DBUS_SESSION_BUS_ADDRESS': '/dev/null', 'HOSTNAME': 'f0778947a8ed', 'SUDO_USER': 'root', 'USER': 'nobody', 'SUDO_UID': '0', 'LOGNAME': 'nobody', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin', 'USERNAME': 'nobody', 'DISPLAY': ':0', 'TERM': 'xterm'})
universe-ezK9kg-0 | [2016-12-10 03:48:11,501] [INFO:root] [EnvStatus] Changing env_state: None (env_id=None) -> None (env_id=None) (episode_id: 0->0, fps=60)
universe-ezK9kg-0 | [2016-12-10 03:48:11,502] [INFO:universe.rewarder.remote] Starting Rewarder on port=15901
universe-ezK9kg-0 | [2016-12-10 03:48:11,507] [INFO:universe.extra.universe.wrappers.logger] Running VNC environments with Logger set to print_frequency=5. To change this, pass "print_frequency=k" or "print_frequency=None" to "env.configure".
universe-ezK9kg-0 | [2016-12-10 03:48:11,508] [INFO:universe.envs.vnc_env] Using the golang VNC implementation
universe-ezK9kg-0 | [2016-12-10 03:48:11,509] [INFO:universe.envs.vnc_env] Using VNCSession arguments: {'start_timeout': 7, 'compress_level': 9, 'encoding': 'zrle', 'fine_quality_level': 50, 'subsample_level': 2}. (Customize by running "env.configure(vnc_kwargs={...})"
universe-ezK9kg-0 | [2016-12-10 03:48:11,509] [INFO:universe.envs.vnc_env] Printed stats will ignore clock skew. (This usually makes sense only when the environment and agent are on the same machine.)
universe-ezK9kg-0 | [2016-12-10 03:48:11,515] [INFO:universe.envs.vnc_env] [0] Connecting to environment: vnc://127.0.0.1:5900 password=openai. Use the browser-based VNC client: http://None/viewer/?password=openai
universe-ezK9kg-0 | [2016-12-10 03:48:11,515] [INFO:universe.extra.universe.envs.vnc_env] [0] Connecting to environment details: vnc_address=127.0.0.1:5900 vnc_password=openai rewarder_address=None rewarder_password=openai
universe-ezK9kg-0 | 2016/12/10 03:48:11 I1210 03:48:11.516274 61 gymvnc.go:417] [0:127.0.0.1:5900] opening connection to VNC server
universe-ezK9kg-0 | [2016-12-10 03:48:11,517] [INFO:root] [EnvStatus] Changing env_state: None (env_id=None) -> resetting (env_id=None) (episode_id: 0->1, fps=60)
universe-ezK9kg-0 | [2016-12-10 03:48:11,517] [INFO:root] [MainThread] Env state: env_id=None episode_id=1
universe-ezK9kg-0 | 2016/12/10 03:48:11 I1210 03:48:11.523695 61 gymvnc.go:550] [0:127.0.0.1:5900] connection established
universe-ezK9kg-0 | [Sat Dec 10 03:48:11 UTC 2016] [/usr/local/bin/sudoable-env-setup] Disabling outbound network traffic for none
universe-ezK9kg-0 | [2016-12-10 03:48:11,568] [INFO:gym_flashgames.launcher] [MainThread] Launching new Chrome process (attempt 0/10)
universe-ezK9kg-0 | [2016-12-10 03:48:11,569] [INFO:root] Replacing selenium_wrapper_server since we currently do it at every episode boundary
universe-ezK9kg-0 | [2016-12-10 03:48:11,673] [selenium_wrapper_server] Calling webdriver.Chrome()
[2016-12-10 11:48:11,769] Remote closed: address=localhost:5900
[2016-12-10 11:48:11,770] Remote closed: address=localhost:15900
[2016-12-10 11:48:11,771] At least one sockets was closed by the remote. Sleeping 1s...
universe-ezK9kg-0 | [2016-12-10 03:48:11,779] [INFO:universe.rewarder.remote] Client connecting: peer=tcp4:127.0.0.1:35970 observer=True
universe-ezK9kg-0 | [2016-12-10 03:48:11,779] [INFO:universe.rewarder.remote] WebSocket connection established
universe-ezK9kg-0 | [init] [2016-12-10 03:48:11,873] init detected end of child process 15 with exit code 0, not killed by signal
[2016-12-10 11:48:12,773] Using the golang VNC implementation
[2016-12-10 11:48:12,773] Using VNCSession arguments: {'subsample_level': 2, 'fine_quality_level': 50, 'start_timeout': 7, 'encoding': 'tight'}. (Customize by running "env.configure(vnc_kwargs={...})"
[2016-12-10 11:48:12,776] [0] Connecting to environment: vnc://localhost:5900 password=openai. Use the browser-based VNC client: http://localhost:15900/viewer/?password=openai
universe-ezK9kg-0 | [2016-12-10 03:48:12,775] [INFO:universe.rewarder.remote] WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
2016/12/10 11:48:12 I1210 11:48:12.777538 2533 gymvnc.go:417] [0:localhost:5900] opening connection to VNC server
universe-ezK9kg-0 | [2016-12-10 03:48:12,776] [INFO:universe.rewarder.remote] [Twisted] Non-active client disconnected
2016/12/10 11:48:12 I1210 11:48:12.782913 2533 gymvnc.go:550] [0:localhost:5900] connection established
universe-ezK9kg-0 | [2016-12-10 03:48:12,793] [INFO:universe.rewarder.remote] Client connecting: peer=tcp4:127.0.0.1:35998 observer=False
universe-ezK9kg-0 | [2016-12-10 03:48:12,793] [INFO:universe.rewarder.remote] WebSocket connection established
universe-ezK9kg-0 | [2016-12-10 03:48:13,240] [selenium_wrapper_server] Call to webdriver.Chrome() completed: 1.57s
universe-ezK9kg-0 | [2016-12-10 03:48:13,240] [INFO:gym_flashgames.launcher] [MainThread] Navigating browser to url=http://localhost
universe-ezK9kg-0 | [2016-12-10 03:48:13,705] [INFO:root] [EnvStatus] Changing env_state: resetting (env_id=None) -> running (env_id=None) (episode_id: 1->1, fps=60)
universe-ezK9kg-0 | Manhole[1481341693.7412]: Patched <built-in function fork> and <built-in function fork>.
universe-ezK9kg-0 | Manhole[1481341693.7441]: Manhole UDS path: /tmp/manhole-61
universe-ezK9kg-0 | Manhole[1481341693.7443]: Waiting for new connection (in pid:61) ...
universe-ezK9kg-0 | [2016-12-10 03:48:16,525] [INFO:universe.wrappers.logger] Stats for the past 5.01s: vnc_updates_ps=3.2 n=1 reaction_time=None observation_lag=None action_lag=None reward_ps=0.0 reward_total=0.0 vnc_bytes_ps[total]=516144.6 vnc_pixels_ps[total]=500615.0 reward_lag=None rewarder_message_lag=None fps=33
universe-ezK9kg-0 | [2016-12-10 03:48:18,725] [INFO:universe.pyprofile] [pyprofile] period=5.00s timers={"rewarder.compute_reward": {"mean": "507.66us", "std": "1.06ms", "calls": 301}, "rewarder.frame": {"mean": "17.63ms", "std": "501.02us", "calls": 300}, "rewarder.sleep": {"mean": "15.15ms", "std": "505.62us", "calls": 299}, "vnc_env.VNCEnv.vnc_session.step": {"mean": "240.73us", "std": "818.94us", "calls": 301}, "rewarder.sleep.missed": {"mean": "1.91ms", "std": "0.00us", "calls": 1}} counters={} gauges={} (export_time=203.85us)
universe-ezK9kg-0 | [2016-12-10 03:48:18,725] [INFO:universe.rewarder.remote] [Rewarder] Over past 5.00s, sent 1 reward messages to agent: reward=0 reward_min=0 reward_max=0 done=False info={'rewarder.vnc.updates.bytes': None, 'rewarder.vnc.updates.n': None, 'rewarder.profile': '<706 bytes>', 'rewarder.vnc.updates.pixels': None}
universe-ezK9kg-0 | [2016-12-10 03:48:21,541] [INFO:universe.wrappers.logger] Stats for the past 5.01s: vnc_updates_ps=0.0 n=1 reaction_time=None observation_lag=None action_lag=None reward_ps=0.0 reward_total=0.0 vnc_bytes_ps[total]=0.0 vnc_pixels_ps[total]=0.0 reward_lag=None rewarder_message_lag=None fps=60
universe-ezK9kg-0 | [2016-12-10 03:48:23,725] [INFO:universe.pyprofile] [pyprofile] period=5.00s timers={"rewarder.compute_reward": {"mean": "447.89us", "std": "560.56us", "calls": 300}, "rewarder.frame": {"mean": "17.67ms", "std": "474.88us", "calls": 300}, "rewarder.sleep": {"mean": "15.11ms", "std": "751.25us", "calls": 300}, "vnc_env.VNCEnv.vnc_session.step": {"mean": "206.79us", "std": "547.51us", "calls": 300}} counters={"agent_conn.reward": {"mean": 0.0, "calls": 1, "std": 0}} gauges={} (export_time=127.55us)
universe-ezK9kg-0 | [2016-12-10 03:48:23,725] [INFO:universe.rewarder.remote] [Rewarder] Over past 5.00s, sent 1 reward messages to agent: reward=0 reward_min=0 reward_max=0 done=False info={'rewarder.vnc.updates.bytes': None, 'rewarder.vnc.updates.n': None, 'rewarder.profile': '<681 bytes>', 'rewarder.vnc.updates.pixels': None}
universe-ezK9kg-0 | [2016-12-10 03:48:26,766] [INFO:universe.wrappers.logger] Stats for the past 5.22s: vnc_updates_ps=0.0 n=1 reaction_time=None observation_lag=None action_lag=None reward_ps=0.0 reward_total=0.0 vnc_bytes_ps[total]=0.0 vnc_pixels_ps[total]=0.0 reward_lag=None rewarder_message_lag=None fps=52
universe-ezK9kg-0 | [2016-12-10 03:48:26,767] [INFO:root] [Rewarder] Rewarder fell behind by 0.6443941593170166s from target; losing 38 frames
universe-ezK9kg-0 | [2016-12-10 03:48:27,148] [INFO:universe.rewarder.remote] CONNECTION STATUS: Marking connection as active: observer=False peer=tcp4:127.0.0.1:35998 total_conns=1
[2016-12-10 11:48:27,175] [0:localhost:5900] Sending reset for env_id=flashgames.DuskDrive-v0 fps=60 episode_id=0
universe-ezK9kg-0 | [2016-12-10 03:48:27,178] [INFO:universe.rewarder.remote] Received reset message: {'headers': {'episode_id': '0', 'sent_at': 1481341707.176003, 'message_id': 10}, 'body': {'env_id': 'flashgames.DuskDrive-v0', 'seed': None, 'fps': 60}, 'method': 'v0.env.reset'}
universe-ezK9kg-0 | [2016-12-10 03:48:27,186] [INFO:root] [EnvStatus] Changing env_state: running (env_id=None) -> resetting (env_id=flashgames.DuskDrive-v0) (episode_id: 1->2, fps=60)
universe-ezK9kg-0 | [2016-12-10 03:48:27,186] [ERROR:root] Closing server (via subprocess.close()) and all chromes (via pkill chromedriver || :; pkill chrome || :)
universe-ezK9kg-0 | [2016-12-10 03:48:27,186] [INFO:root] [Rewarder] Blocking until env finishes resetting
universe-ezK9kg-0 | [init] [2016-12-10 03:48:27,200] init detected end of child process 103 with exit code 0, killed by SIGTERM: 15
universe-ezK9kg-0 | [init] [2016-12-10 03:48:27,204] init detected end of child process 118 with exit code 0, not killed by signal
universe-ezK9kg-0 | [2016-12-10 03:48:27,206] [INFO:root] [EnvController] RESET CAUSE: changing out environments due to v0.env.reset (with episode_id=0): flashgames.DuskDrive-v0 -> flashgames.DuskDrive-v0 (new episode_id=2 fps=60)
universe-ezK9kg-0 | [2016-12-10 03:48:27,206] [INFO:root] [EnvController] Env state: env_id=flashgames.DuskDrive-v0 episode_id=2
universe-ezK9kg-0 | [init] [2016-12-10 03:48:27,214] init detected end of child process 325 with exit code 0, killed by SIGTERM: 15
universe-ezK9kg-0 | [init] [2016-12-10 03:48:27,215] init detected end of child process 339 with exit code 0, killed by SIGTERM: 15
universe-ezK9kg-0 | [Sat Dec 10 03:48:27 UTC 2016] [/usr/local/bin/sudoable-env-setup] Allowing outbound network traffic to non-private IPs for git-lfs. (Going to fetch files via git lfs.)
universe-ezK9kg-0 | [init] [2016-12-10 03:48:27,309] init detected end of child process 117 with exit code 0, killed by SIGTERM: 15
universe-ezK9kg-0 | [init] [2016-12-10 03:48:27,313] init detected end of child process 115 with exit code 0, not killed by signal
universe-ezK9kg-0 | [init] [2016-12-10 03:48:27,314] init detected end of child process 114 with exit code 0, not killed by signal
universe-ezK9kg-0 | [init] [2016-12-10 03:48:27,314] init detected end of child process 106 with exit code 0, not killed by signal
universe-ezK9kg-0 | [unpack-lfs] [2016-12-10 03:48:27,396] Fetching files: git lfs pull -I git-lfs/flashgames.DuskDrive-v0.tar.gz
[2016-12-10 11:49:27,200] [0] Closing rewarder connection
universe-ezK9kg-0 | [2016-12-10 03:49:27,199] [INFO:universe.rewarder.remote] WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
Traceback (most recent call last):
  File "train.py", line 14, in <module>
universe-ezK9kg-0 | [2016-12-10 03:49:27,200] [INFO:universe.rewarder.remote] [Twisted] Active client disconnected (sent 11 messages). Still have 0 active clients left
universe-ezK9kg-0 | [tigervnc]
universe-ezK9kg-0 | [tigervnc] Xvnc TigerVNC 1.7.0 - built Sep  8 2016 10:39:22
universe-ezK9kg-0 | [tigervnc] Copyright (C) 1999-2016 TigerVNC Team and many others (see README.txt)
    observation_n, reward_n, done_n, info = env.step(action_n)
  File "/Users/jomyhuang/Desktop/PyProject/gym/gym/core.py", line 122, in step
universe-ezK9kg-0 | [tigervnc] See http://www.tigervnc.org for information on TigerVNC.
universe-ezK9kg-0 | [tigervnc] Underlying X server release 11400000, The X.Org Foundation
universe-ezK9kg-0 | [tigervnc]
    observation, reward, done, info = self._step(action)
  File "/Users/jomyhuang/Desktop/PyProject/gym/gym/core.py", line 334, in _step
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension VNC-EXTENSION
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension Generic Event Extension
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension SHAPE
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension MIT-SHM
    return self.env.step(action)
  File "/Users/jomyhuang/Desktop/PyProject/gym/gym/core.py", line 122, in step
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension XInputExtension
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension XTEST
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension BIG-REQUESTS
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension SYNC
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension XKEYBOARD
    observation, reward, done, info = self._step(action)
  File "/Users/jomyhuang/Desktop/PyProject/universe/universe/wrappers/timer.py", line 20, in _step
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension XC-MISC
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension XINERAMA
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension XFIXES
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension RENDER
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension RANDR
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension COMPOSITE
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension DAMAGE
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension MIT-SCREEN-SAVER
    observation_n, reward_n, done_n, info = self.env.step(action_n)
  File "/Users/jomyhuang/Desktop/PyProject/gym/gym/core.py", line 122, in step
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension DOUBLE-BUFFER
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension RECORD
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension DPMS
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension X-Resource
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension XVideo
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension XVideo-MotionCompensation
    observation, reward, done, info = self._step(action)
universe-ezK9kg-0 | [tigervnc] Initializing built-in extension GLX
  File "/Users/jomyhuang/Desktop/PyProject/universe/universe/wrappers/render.py", line 30, in _step
universe-ezK9kg-0 | [tigervnc]
universe-ezK9kg-0 | [tigervnc] Sat Dec 10 03:48:10 2016
universe-ezK9kg-0 | [tigervnc]  vncext:      VNC extension running!
universe-ezK9kg-0 | [tigervnc]  vncext:      Listening for VNC connections on all interface(s), port 5900
universe-ezK9kg-0 | [tigervnc]  vncext:      created VNC server for screen 0
universe-ezK9kg-0 | [tigervnc] [dix] Could not init font path element /usr/share/fonts/X11/Type1/, removing from list!
universe-ezK9kg-0 | [tigervnc] [dix] Could not init font path element /usr/share/fonts/X11/75dpi/, removing from list!
universe-ezK9kg-0 | [tigervnc] [dix] Could not init font path element /usr/share/fonts/X11/100dpi/, removing from list!
universe-ezK9kg-0 | [tigervnc]
    observation_n, reward_n, done_n, info_n = self.env.step(action_n)
  File "/Users/jomyhuang/Desktop/PyProject/gym/gym/core.py", line 122, in step
universe-ezK9kg-0 | [tigervnc] Sat Dec 10 03:48:11 2016
universe-ezK9kg-0 | [tigervnc]  Connections: accepted: 127.0.0.1::58804
    observation, reward, done, info = self._step(action)
  File "/Users/jomyhuang/Desktop/PyProject/universe/universe/wrappers/throttle.py", line 117, in _step
universe-ezK9kg-0 | [tigervnc]  SConnection: Client needs protocol version 3.8
universe-ezK9kg-0 | [tigervnc]  SConnection: Client requests security type VncAuth(2)
universe-ezK9kg-0 | [tigervnc]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
universe-ezK9kg-0 | [tigervnc]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
universe-ezK9kg-0 | [tigervnc]  Connections: accepted: 172.17.0.1::36260
universe-ezK9kg-0 | [tigervnc]
universe-ezK9kg-0 | [tigervnc] Sat Dec 10 03:48:12 2016
universe-ezK9kg-0 | [tigervnc]  Connections: closed: 172.17.0.1::36260 (Clean disconnection)
universe-ezK9kg-0 | [tigervnc]  EncodeManager: Framebuffer updates: 0
universe-ezK9kg-0 | [tigervnc]  EncodeManager:   Total: 0 rects, 0 pixels
universe-ezK9kg-0 | [tigervnc]  EncodeManager:          0 B (1:-nan ratio)
universe-ezK9kg-0 | [tigervnc]  Connections: accepted: 172.17.0.1::36288
universe-ezK9kg-0 | [tigervnc]  SConnection: Client needs protocol version 3.8
universe-ezK9kg-0 | [tigervnc]  SConnection: Client requests security type VncAuth(2)
universe-ezK9kg-0 | [tigervnc]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
    observation_n, reward_n, done_n, info = self._substep(action_n)
  File "/Users/jomyhuang/Desktop/PyProject/universe/universe/wrappers/throttle.py", line 132, in _substep
universe-ezK9kg-0 | [tigervnc]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
universe-ezK9kg-0 | [tigervnc]
universe-ezK9kg-0 | [tigervnc] Sat Dec 10 03:49:27 2016
universe-ezK9kg-0 | [tigervnc]  Connections: closed: 172.17.0.1::36288 (Clean disconnection)
    observation_n, reward_n, done_n, info = self.env.step(action_n)
  File "/Users/jomyhuang/Desktop/PyProject/gym/gym/core.py", line 122, in step
universe-ezK9kg-0 | [tigervnc]  EncodeManager: Framebuffer updates: 19
universe-ezK9kg-0 | [tigervnc]  EncodeManager:   Tight:
universe-ezK9kg-0 | [tigervnc]  EncodeManager:     Solid: 34 rects, 2.1579 Mpixels
universe-ezK9kg-0 | [tigervnc]  EncodeManager:            544 B (1:15867.6 ratio)
universe-ezK9kg-0 | [tigervnc]  EncodeManager:     Bitmap RLE: 3 rects, 32.8 kpixels
universe-ezK9kg-0 | [tigervnc]  EncodeManager:                 238 B (1:551.412 ratio)
universe-ezK9kg-0 | [tigervnc]  EncodeManager:     Indexed RLE: 24 rects, 262.324 kpixels
universe-ezK9kg-0 | [tigervnc]  EncodeManager:                  11.0791 KiB (1:92.5151 ratio)
universe-ezK9kg-0 | [tigervnc]  EncodeManager:   Tight (JPEG):
    observation, reward, done, info = self._step(action)
  File "/Users/jomyhuang/Desktop/PyProject/universe/universe/envs/vnc_env.py", line 447, in _step
universe-ezK9kg-0 | [tigervnc]  EncodeManager:     Full Colour: 17 rects, 812.888 kpixels
universe-ezK9kg-0 | [tigervnc]  EncodeManager:                  116.543 KiB (1:27.2478 ratio)
universe-ezK9kg-0 | [tigervnc]  EncodeManager:   Total: 78 rects, 3.26591 Mpixels
    self._handle_crashed_n(info_n)
  File "/Users/jomyhuang/Desktop/PyProject/universe/universe/envs/vnc_env.py", line 518, in _handle_crashed_n
    raise error.Error('{}/{} environments have crashed! Most recent error: {}'.format(len(self.crashed), self.n, errors))
universe.error.Error: 1/1 environments have crashed! Most recent error: {'0': 'Rewarder session failed: Lost connection: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake) (clean=False code=1006)'}
[2016-12-10 11:49:27,249] Killing and removing container: id=f0778947a8eddf04192aae3c7cf58f3fd6c7f8d4bf11624e90448018c8491a7b. (If this command errors, you can always kill all automanaged environments on this Docker daemon via: docker rm -f $(docker ps -q -a -f 'label=com.openai.automanaged=true')
universe-ezK9kg-0 | [tigervnc]  EncodeManager:

**Comment by Baschdl** [comment]
Duplicate to #6

**Comment by jomyhuang** [comment]
thank you, after update quay.io/openai/universe.flashgames:20.0.07 is work!
