### ISSUE TITLE
In flashgames.DuskDrive-v0 mouse jumps for some time and then environment crashes

### ISSUE THREAD

**Issue by iaroslav-ai** [openai/universe#5]
I seem to have been able to install all the dependencies and run the following code:

```
import gym
import universe # register the universe environments

env = gym.make('flashgames.DuskDrive-v0')
env.configure(remotes=1) # automatically creates a local docker container
observation_n = env.reset()

while True:
  action_n = [[('KeyEvent', 'ArrowUp', True)] for ob in observation_n] # your agent here
  observation_n, reward_n, done_n, info = env.step(action_n)
  env.render()
```

however the result that I see is that the mouse pointer jumps in the rendered environment, and after some time the environment crashes: 

https://www.youtube.com/watch?v=8WDDzbGVJ3o

the output that I get in console is as follows:

```
[2016-12-05 13:48:17,797] Making new env: flashgames.DuskDrive-v0
[2016-12-05 13:48:17,800] Writing logs to file: /tmp/universe-4612.log
[2016-12-05 13:48:17,809] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.1. Run the same thing by hand as: docker run -p 5900:5900 -p 15900:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.1
[2016-12-05 13:48:18,060] Remote closed: address=localhost:5900
[2016-12-05 13:48:18,062] At least one sockets was closed by the remote. Sleeping 1s...
universe-psnd10-0 | Setting VNC and rewarder password: openai
universe-psnd10-0 | [Mon Dec  5 12:48:18 UTC 2016] Waiting for /tmp/.X11-unix/X0 to be created (try 1/10)
universe-psnd10-0 | [Mon Dec  5 12:48:18 UTC 2016] [/usr/local/bin/sudoable-env-setup] Disabling outbound network traffic for none
universe-psnd10-0 | [init] [2016-12-05 12:48:18,155] PID 55 launched with command ['sudo', '-H', '-u', 'nobody', 'DISPLAY=:0', 'DBUS_SESSION_BUS_ADDRESS=/dev/null', '/app/universe-envs/controlplane/bin/controlplane.py', '--rewarder-port=15901']
universe-psnd10-0 | [init] [2016-12-05 12:48:18,156] init detected end of child process 23 with exit code 0, not killed by signal
universe-psnd10-0 | WebSocket server settings:
universe-psnd10-0 |   - Listen on :5898
universe-psnd10-0 |   - Flash security policy server
universe-psnd10-0 |   - No SSL/TLS support (no cert file)
universe-psnd10-0 |   - proxying from :5898 to localhost:5900
universe-psnd10-0 | [2016-12-05 12:48:18,710] [INFO:root] Starting play_controlplane.py with the following: command=['/app/universe-envs/controlplane/bin/controlplane.py', '--rewarder-port=15901'] args=Namespace(bot_demonstration=False, demonstration=False, env_id=None, idle_timeout=None, integrator_mode=False, no_env=False, no_rewarder=False, no_scorer=False, no_vexpect=False, remotes='vnc://127.0.0.1:5900', rewarder_fps=60, rewarder_port=15901, verbosity=0) env=environ({'SUDO_USER': 'root', 'DBUS_SESSION_BUS_ADDRESS': '/dev/null', 'USER': 'nobody', 'USERNAME': 'nobody', 'SUDO_COMMAND': '/app/universe-envs/controlplane/bin/controlplane.py --rewarder-port=15901', 'TERM': 'xterm', 'SHELL': '/usr/sbin/nologin', 'HOME': '/nonexistent', 'LOGNAME': 'nobody', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin', 'SUDO_UID': '0', 'HOSTNAME': '657c3c28301b', 'SUDO_GID': '0', 'MAIL': '/var/mail/nobody', 'DISPLAY': ':0'})
universe-psnd10-0 | [2016-12-05 12:48:18,710] [INFO:root] [EnvStatus] Changing env_state: None (env_id=None) -> None (env_id=None) (episode_id: 0->0, fps=60)
universe-psnd10-0 | [2016-12-05 12:48:18,710] [INFO:universe.rewarder.remote] Starting Rewarder on port=15901
universe-psnd10-0 | [2016-12-05 12:48:18,713] [INFO:universe.extra.universe.wrappers.logger] Running VNC environments with Logger set to print_frequency=5. To change this, pass "print_frequency=k" or "print_frequency=None" to "env.configure".
universe-psnd10-0 | [2016-12-05 12:48:18,715] [INFO:universe.envs.vnc_env] Using the golang VNC implementation
universe-psnd10-0 | [2016-12-05 12:48:18,715] [INFO:universe.envs.vnc_env] Using VNCSession arguments: {'encoding': 'zrle', 'start_timeout': 7, 'fine_quality_level': 50, 'subsample_level': 2, 'compress_level': 9}. (Customize by running "env.configure(vnc_kwargs={...})"
universe-psnd10-0 | [2016-12-05 12:48:18,716] [INFO:universe.envs.vnc_env] Printed stats will ignore clock skew. (This usually makes sense only when the environment and agent are on the same machine.)
universe-psnd10-0 | [2016-12-05 12:48:18,719] [INFO:universe.envs.vnc_env] [0] Connecting to environment: vnc://127.0.0.1:5900 password=openai. Use the browser-based VNC client: http://None/viewer/?password=openai
universe-psnd10-0 | [2016-12-05 12:48:18,720] [INFO:universe.extra.universe.envs.vnc_env] [0] Connecting to environment details: vnc_address=127.0.0.1:5900 vnc_password=openai rewarder_address=None rewarder_password=openai
universe-psnd10-0 | 2016/12/05 12:48:18 I1205 12:48:18.720314 56 gymvnc.go:417] [0:127.0.0.1:5900] opening connection to VNC server
universe-psnd10-0 | [2016-12-05 12:48:18,720] [INFO:root] [EnvStatus] Changing env_state: None (env_id=None) -> resetting (env_id=None) (episode_id: 0->1, fps=60)
universe-psnd10-0 | [2016-12-05 12:48:18,720] [INFO:root] [MainThread] Env state: env_id=None episode_id=1
universe-psnd10-0 | 2016/12/05 12:48:18 I1205 12:48:18.724959 56 gymvnc.go:550] [0:127.0.0.1:5900] connection established
universe-psnd10-0 | [Mon Dec  5 12:48:18 UTC 2016] [/usr/local/bin/sudoable-env-setup] Disabling outbound network traffic for none
universe-psnd10-0 | [2016-12-05 12:48:18,745] [INFO:gym_flashgames.launcher] [MainThread] Launching new Chrome process (attempt 0/10)
universe-psnd10-0 | [2016-12-05 12:48:18,746] [INFO:root] Replacing selenium_wrapper_server since we currently do it at every episode boundary
universe-psnd10-0 | [2016-12-05 12:48:18,857] [selenium_wrapper_server] Calling webdriver.Chrome()
[2016-12-05 13:48:19,064] Remote closed: address=localhost:5900
[2016-12-05 13:48:19,064] Remote closed: address=localhost:15900
[2016-12-05 13:48:19,064] At least one sockets was closed by the remote. Sleeping 1s...
universe-psnd10-0 | [2016-12-05 12:48:19,067] [INFO:universe.rewarder.remote] Client connecting: peer=tcp4:127.0.0.1:60428 observer=True
universe-psnd10-0 | [2016-12-05 12:48:19,067] [INFO:universe.rewarder.remote] WebSocket connection established
universe-psnd10-0 | [init] [2016-12-05 12:48:19,129] init detected end of child process 17 with exit code 0, not killed by signal
[2016-12-05 13:48:20,065] Using the golang VNC implementation
[2016-12-05 13:48:20,065] Using VNCSession arguments: {'subsample_level': 2, 'start_timeout': 7, 'fine_quality_level': 50, 'encoding': 'tight'}. (Customize by running "env.configure(vnc_kwargs={...})"
[2016-12-05 13:48:20,068] [0] Connecting to environment: vnc://localhost:5900 password=openai. Use the browser-based VNC client: http://localhost:15900/viewer/?password=openai
2016/12/05 13:48:20 I1205 13:48:20.069146 4612 gymvnc.go:417] [0:localhost:5900] opening connection to VNC server
2016/12/05 13:48:20 I1205 13:48:20.071467 4612 gymvnc.go:550] [0:localhost:5900] connection established
universe-psnd10-0 | [2016-12-05 12:48:20,066] [INFO:universe.rewarder.remote] WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
universe-psnd10-0 | [2016-12-05 12:48:20,080] [INFO:universe.rewarder.remote] Client connecting: peer=tcp4:127.0.0.1:60468 observer=False
universe-psnd10-0 | [2016-12-05 12:48:20,080] [INFO:universe.rewarder.remote] WebSocket connection established
universe-psnd10-0 | [2016-12-05 12:48:20,131] [selenium_wrapper_server] Call to webdriver.Chrome() completed: 1.27s
universe-psnd10-0 | [2016-12-05 12:48:20,131] [INFO:gym_flashgames.launcher] [MainThread] Navigating browser to url=http://localhost
universe-psnd10-0 | [2016-12-05 12:48:20,375] [INFO:root] [EnvStatus] Changing env_state: resetting (env_id=None) -> running (env_id=None) (episode_id: 1->1, fps=60)
universe-psnd10-0 | Manhole[1480942100.3775]: Patched <built-in function fork> and <built-in function fork>.
universe-psnd10-0 | Manhole[1480942100.3777]: Manhole UDS path: /tmp/manhole-56
universe-psnd10-0 | Manhole[1480942100.3778]: Waiting for new connection (in pid:56) ...
universe-psnd10-0 | [2016-12-05 12:48:23,727] [INFO:universe.wrappers.logger] Stats for the past 5.01s: vnc_updates_ps=2.2 n=1 reaction_time=None observation_lag=None action_lag=None reward_ps=0.0 reward_total=0.0 vnc_bytes_ps[total]=359679.6 vnc_pixels_ps[total]=532589.2 reward_lag=None rewarder_message_lag=None fps=40
universe-psnd10-0 | [2016-12-05 12:48:25,377] [INFO:universe.pyprofile] [pyprofile] period=5.00s timers={"rewarder.compute_reward": {"mean": "214.29us", "calls": 301, "std": "284.49us"}, "vnc_env.VNCEnv.vnc_session.step": {"mean": "86.38us", "calls": 301, "std": "82.80us"}, "rewarder.frame": {"mean": "16.77ms", "calls": 300, "std": "35.17us"}, "rewarder.sleep": {"mean": "16.30ms", "calls": 300, "std": "283.67us"}} counters={} gauges={} (export_time=92.27us)
universe-psnd10-0 | [2016-12-05 12:48:25,377] [INFO:universe.rewarder.remote] [Rewarder] Over past 5.00s, sent 1 reward messages to agent: reward=0 reward_min=0 reward_max=0 done=False info={'rewarder.vnc.updates.n': None, 'rewarder.vnc.updates.pixels': None, 'rewarder.profile': '<606 bytes>', 'rewarder.vnc.updates.bytes': None}
universe-psnd10-0 | [2016-12-05 12:48:28,744] [INFO:universe.wrappers.logger] Stats for the past 5.02s: vnc_updates_ps=0.0 n=1 reaction_time=None observation_lag=None action_lag=None reward_ps=0.0 reward_total=0.0 vnc_bytes_ps[total]=0.0 vnc_pixels_ps[total]=0.0 reward_lag=None rewarder_message_lag=None fps=60
universe-psnd10-0 | [2016-12-05 12:48:30,393] [INFO:universe.pyprofile] [pyprofile] period=5.02s timers={"rewarder.compute_reward": {"mean": "195.87us", "calls": 301, "std": "64.43us"}, "vnc_env.VNCEnv.vnc_session.step": {"mean": "81.01us", "calls": 301, "std": "31.80us"}, "rewarder.frame": {"mean": "16.76ms", "calls": 301, "std": "34.13us"}, "rewarder.sleep": {"mean": "16.32ms", "calls": 301, "std": "93.57us"}} counters={"agent_conn.reward": {"std": 0, "calls": 1, "mean": 0.0}} gauges={} (export_time=93.46us)
universe-psnd10-0 | [2016-12-05 12:48:30,393] [INFO:universe.rewarder.remote] [Rewarder] Over past 5.02s, sent 1 reward messages to agent: reward=0 reward_min=0 reward_max=0 done=False info={'rewarder.vnc.updates.n': None, 'rewarder.vnc.updates.pixels': None, 'rewarder.profile': '<677 bytes>', 'rewarder.vnc.updates.bytes': None}
universe-psnd10-0 | [2016-12-05 12:48:33,760] [INFO:universe.wrappers.logger] Stats for the past 5.02s: vnc_updates_ps=0.0 n=1 reaction_time=None observation_lag=None action_lag=None reward_ps=0.0 reward_total=0.0 vnc_bytes_ps[total]=0.0 vnc_pixels_ps[total]=0.0 reward_lag=None rewarder_message_lag=None fps=60
universe-psnd10-0 | [2016-12-05 12:48:35,393] [INFO:universe.pyprofile] [pyprofile] period=5.00s timers={"rewarder.compute_reward": {"mean": "187.30us", "calls": 300, "std": "60.73us"}, "vnc_env.VNCEnv.vnc_session.step": {"mean": "77.51us", "calls": 300, "std": "30.43us"}, "rewarder.frame": {"mean": "16.76ms", "calls": 300, "std": "32.75us"}, "rewarder.sleep": {"mean": "16.34ms", "calls": 300, "std": "85.00us"}} counters={"agent_conn.reward": {"std": 0, "calls": 1, "mean": 0.0}} gauges={} (export_time=87.98us)
universe-psnd10-0 | [2016-12-05 12:48:35,393] [INFO:universe.rewarder.remote] [Rewarder] Over past 5.00s, sent 1 reward messages to agent: reward=0 reward_min=0 reward_max=0 done=False info={'rewarder.vnc.updates.n': None, 'rewarder.vnc.updates.pixels': None, 'rewarder.profile': '<673 bytes>', 'rewarder.vnc.updates.bytes': None}
universe-psnd10-0 | [2016-12-05 12:48:38,777] [INFO:universe.wrappers.logger] Stats for the past 5.02s: vnc_updates_ps=0.0 n=1 reaction_time=None observation_lag=None action_lag=None reward_ps=0.0 reward_total=0.0 vnc_bytes_ps[total]=0.0 vnc_pixels_ps[total]=0.0 reward_lag=None rewarder_message_lag=None fps=60
[2016-12-05 13:48:40,089] [0:localhost:5900] ntpdate -q -p 8 localhost call timed out after 20.0s; killing the subprocess. This is ok, but you could have more accurate timings by enabling UDP port 123 traffic to your env. (Alternatively, you can try increasing the timeout by setting environment variable UNIVERSE_NTPDATE_TIMEOUT=10.)
[2016-12-05 13:48:40,109] [0:localhost:5900] Sending reset for env_id=flashgames.DuskDrive-v0 fps=60 episode_id=0
universe-psnd10-0 | [2016-12-05 12:48:40,098] [INFO:universe.rewarder.remote] CONNECTION STATUS: Marking connection as active: observer=False peer=tcp4:127.0.0.1:60468 total_conns=1
universe-psnd10-0 | [2016-12-05 12:48:40,109] [INFO:universe.rewarder.remote] Received reset message: {'body': {'seed': None, 'env_id': 'flashgames.DuskDrive-v0', 'fps': 60}, 'method': 'v0.env.reset', 'headers': {'sent_at': 1480942120.109446, 'message_id': 10, 'episode_id': '0'}}
universe-psnd10-0 | [2016-12-05 12:48:40,117] [INFO:root] [EnvStatus] Changing env_state: running (env_id=None) -> resetting (env_id=flashgames.DuskDrive-v0) (episode_id: 1->2, fps=60)
universe-psnd10-0 | [2016-12-05 12:48:40,117] [ERROR:root] Closing server (via subprocess.close()) and all chromes (via pkill chromedriver || :; pkill chrome || :)
universe-psnd10-0 | [2016-12-05 12:48:40,126] [INFO:root] [Rewarder] Blocking until env finishes resetting
universe-psnd10-0 | [init] [2016-12-05 12:48:40,128] init detected end of child process 96 with exit code 0, killed by SIGTERM: 15
universe-psnd10-0 | [2016-12-05 12:48:40,129] [INFO:root] [EnvController] RESET CAUSE: changing out environments due to v0.env.reset (with episode_id=0): flashgames.DuskDrive-v0 -> flashgames.DuskDrive-v0 (new episode_id=2 fps=60)
universe-psnd10-0 | [2016-12-05 12:48:40,130] [INFO:root] [EnvController] Env state: env_id=flashgames.DuskDrive-v0 episode_id=2
universe-psnd10-0 | [Mon Dec  5 12:48:40 UTC 2016] [/usr/local/bin/sudoable-env-setup] Allowing outbound network traffic to non-private IPs for git-lfs. (Going to fetch files via git lfs.)
universe-psnd10-0 | [init] [2016-12-05 12:48:40,163] init detected end of child process 99 with exit code 0, not killed by signal
universe-psnd10-0 | [init] [2016-12-05 12:48:40,163] init detected end of child process 107 with exit code 0, not killed by signal
universe-psnd10-0 | [init] [2016-12-05 12:48:40,163] init detected end of child process 108 with exit code 0, not killed by signal
universe-psnd10-0 | [unpack-lfs] [2016-12-05 12:48:40,231] Fetching files: git lfs pull -I git-lfs/flashgames.DuskDrive-v0.tar.gz
universe-psnd10-0 | [unpack-lfs] [2016-12-05 12:48:46,921] Finished running git lfs pull
universe-psnd10-0 | [unpack-lfs] [2016-12-05 12:48:46,922] git-lfs fetch succeeded
universe-psnd10-0 | [unpack-lfs] [2016-12-05 12:48:46,922] Unpacking files for flashgames.DuskDrive-v0
universe-psnd10-0 | [unpack-lfs] [2016-12-05 12:48:46,985] Merged 5 files from /tmp/flashgames.DuskDrive-v0/public -> /app/universe-envs/flashgames/build/public/flashgames.DuskDrive-v0
universe-psnd10-0 | [unpack-lfs] [2016-12-05 12:48:46,987] Merged 20 files from /tmp/flashgames.DuskDrive-v0/private -> /app/universe-envs/flashgames/build/private/flashgames.DuskDrive-v0
universe-psnd10-0 | [unpack-lfs] [2016-12-05 12:48:46,987] Completed unpack for flashgames.DuskDrive-v0 in 6.756s
universe-psnd10-0 | [Mon Dec  5 12:48:47 UTC 2016] [/usr/local/bin/sudoable-env-setup] [debug] unpack-lfs completed with status code: 0. Created completion file: /usr/local/openai/git-lfs/flashgames.DuskDrive-v0
universe-psnd10-0 | [Mon Dec  5 12:48:47 UTC 2016] [/usr/local/bin/sudoable-env-setup] Disabling outbound network traffic for flashgames.DuskDrive-v0
universe-psnd10-0 | [2016-12-05 12:48:47,085] [INFO:gym_flashgames.launcher] [EnvController] Launching new Chrome process (attempt 0/10)
universe-psnd10-0 | [2016-12-05 12:48:47,085] [INFO:root] Replacing selenium_wrapper_server since we currently do it at every episode boundary
universe-psnd10-0 | [2016-12-05 12:48:47,202] [selenium_wrapper_server] Calling webdriver.Chrome()
universe-psnd10-0 | [2016-12-05 12:48:48,497] [selenium_wrapper_server] Call to webdriver.Chrome() completed: 1.29s
universe-psnd10-0 | [2016-12-05 12:48:48,497] [INFO:gym_flashgames.launcher] [EnvController] Navigating browser to url=http://localhost/flashgames.DuskDrive-v0
universe-psnd10-0 | [2016-12-05 12:48:48,521] [INFO:root] [EnvController] Running command: /app/universe-envs/controlplane/bin/play_vexpect -e flashgames.DuskDrive-v0 -r vnc://127.0.0.1:5900 -d
universe-psnd10-0 | [2016-12-05 12:48:49,096] [play_vexpect] Using the golang VNC implementation
universe-psnd10-0 | [2016-12-05 12:48:49,096] [play_vexpect] Using VNCSession arguments: {'encoding': 'zrle', 'start_timeout': 7, 'subsample_level': 2, 'compress_level': 0, 'fine_quality_level': 50}. (Customize by running "env.configure(vnc_kwargs={...})"
universe-psnd10-0 | [2016-12-05 12:48:49,096] [play_vexpect] Printed stats will ignore clock skew. (This usually makes sense only when the environment and agent are on the same machine.)
universe-psnd10-0 | [2016-12-05 12:48:49,099] [play_vexpect] [0] Connecting to environment: vnc://127.0.0.1:5900 password=openai. Use the browser-based VNC client: http://None/viewer/?password=openai
universe-psnd10-0 | [2016-12-05 12:48:49,099] [play_vexpect] [0] Connecting to environment details: vnc_address=127.0.0.1:5900 vnc_password=openai rewarder_address=None rewarder_password=openai
universe-psnd10-0 | 2016/12/05 12:48:49 I1205 12:48:49.099818 711 gymvnc.go:417] [0:127.0.0.1:5900] opening connection to VNC server
universe-psnd10-0 | 2016/12/05 12:48:49 I1205 12:48:49.101615 711 gymvnc.go:550] [0:127.0.0.1:5900] connection established
universe-psnd10-0 | [2016-12-05 12:48:49,555] [play_vexpect] Waiting for any of [MaskState<initializing0>] to activate
universe-psnd10-0 | 2016/12/05 12:48:55 I1205 12:48:55.444911 56 gymvnc.go:374] [0:127.0.0.1:5900] update queue max of 60 reached; pausing further updates
[2016-12-05 13:49:40,151] [0:localhost:5900] Attached to running environment without reset
universe-psnd10-0 | [2016-12-05 12:49:40,150] [INFO:universe.rewarder.remote] WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
[2016-12-05 13:49:40,163] [0] Closing rewarder connection
Traceback (most recent call last):
  File "utest.py", line 10, in <module>
    observation_n, reward_n, done_n, info = env.step(action_n)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 122, in step
    observation, reward, done, info = self._step(action)
  File "/home/iaroslav/universe/universe/wrappers/timer.py", line 20, in _step
    observation_n, reward_n, done_n, info = self.env.step(action_n)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 122, in step
    observation, reward, done, info = self._step(action)
  File "/home/iaroslav/universe/universe/wrappers/render.py", line 30, in _step
    observation_n, reward_n, done_n, info_n = self.env.step(action_n)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 122, in step
    observation, reward, done, info = self._step(action)
  File "/home/iaroslav/universe/universe/wrappers/throttle.py", line 117, in _step
    observation_n, reward_n, done_n, info = self._substep(action_n)
  File "/home/iaroslav/universe/universe/wrappers/throttle.py", line 132, in _substep
    observation_n, reward_n, done_n, info = self.env.step(action_n)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 122, in step
    observation, reward, done, info = self._step(action)
  File "/home/iaroslav/universe/universe/envs/vnc_env.py", line 447, in _step
    self._handle_crashed_n(info_n)
  File "/home/iaroslav/universe/universe/envs/vnc_env.py", line 518, in _handle_crashed_n
    raise error.Error('{}/{} environments have crashed! Most recent error: {}'.format(len(self.crashed), self.n, errors))
universe.error.Error: 1/1 environments have crashed! Most recent error: {'0': 'Rewarder session failed: Lost connection: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake) (clean=False code=1006)'}
universe-psnd10-0 | [tigervnc] 
universe-psnd10-0 | [tigervnc] Xvnc TigerVNC 1.7.0 - built Sep  8 2016 10:39:22
universe-psnd10-0 | [tigervnc] Copyright (C) 1999-2016 TigerVNC Team and many others (see README.txt)
universe-psnd10-0 | [tigervnc] See http://www.tigervnc.org for information on TigerVNC.
universe-psnd10-0 | [tigervnc] Underlying X server release 11400000, The X.Org Foundation
universe-psnd10-0 | [tigervnc] 
universe-psnd10-0 | [tigervnc] Initializing built-in extension VNC-EXTENSION
universe-psnd10-0 | [tigervnc] Initializing built-in extension Generic Event Extension
universe-psnd10-0 | [tigervnc] Initializing built-in extension SHAPE
universe-psnd10-0 | [tigervnc] Initializing built-in extension MIT-SHM
universe-psnd10-0 | [tigervnc] Initializing built-in extension XInputExtension
universe-psnd10-0 | [tigervnc] Initializing built-in extension XTEST
universe-psnd10-0 | [tigervnc] Initializing built-in extension BIG-REQUESTS
universe-psnd10-0 | [tigervnc] Initializing built-in extension SYNC
universe-psnd10-0 | [tigervnc] Initializing built-in extension XKEYBOARD
universe-psnd10-0 | [tigervnc] Initializing built-in extension XC-MISC
universe-psnd10-0 | [tigervnc] Initializing built-in extension XINERAMA
universe-psnd10-0 | [tigervnc] Initializing built-in extension XFIXES
universe-psnd10-0 | [tigervnc] Initializing built-in extension RENDER
universe-psnd10-0 | [tigervnc] Initializing built-in extension RANDR
universe-psnd10-0 | [tigervnc] Initializing built-in extension COMPOSITE
universe-psnd10-0 | [tigervnc] Initializing built-in extension DAMAGE
universe-psnd10-0 | [tigervnc] Initializing built-in extension MIT-SCREEN-SAVER
universe-psnd10-0 | [tigervnc] Initializing built-in extension DOUBLE-BUFFER
universe-psnd10-0 | [tigervnc] Initializing built-in extension RECORD
universe-psnd10-0 | [tigervnc] Initializing built-in extension DPMS
universe-psnd10-0 | [tigervnc] Initializing built-in extension X-Resource
universe-psnd10-0 | [tigervnc] Initializing built-in extension XVideo
universe-psnd10-0 | [tigervnc] Initializing built-in extension XVideo-MotionCompensation
universe-psnd10-0 | [tigervnc] Initializing built-in extension GLX
universe-psnd10-0 | [tigervnc] 
universe-psnd10-0 | [tigervnc] Mon Dec  5 12:48:18 2016
universe-psnd10-0 | [tigervnc]  vncext:      VNC extension running!
universe-psnd10-0 | [tigervnc]  vncext:      Listening for VNC connections on all interface(s), port 5900
universe-psnd10-0 | [tigervnc]  vncext:      created VNC server for screen 0
universe-psnd10-0 | [tigervnc] [dix] Could not init font path element /usr/share/fonts/X11/Type1/, removing from list!
universe-psnd10-0 | [tigervnc] [dix] Could not init font path element /usr/share/fonts/X11/75dpi/, removing from list!
universe-psnd10-0 | [tigervnc] [dix] Could not init font path element /usr/share/fonts/X11/100dpi/, removing from list!
universe-psnd10-0 | [tigervnc]  Connections: accepted: 127.0.0.1::48030
universe-psnd10-0 | [tigervnc]  SConnection: Client needs protocol version 3.8
universe-psnd10-0 | [tigervnc]  SConnection: Client requests security type VncAuth(2)
universe-psnd10-0 | [tigervnc]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
universe-psnd10-0 | [tigervnc]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
universe-psnd10-0 | [tigervnc] 
universe-psnd10-0 | [tigervnc] Mon Dec  5 12:48:19 2016
universe-psnd10-0 | [tigervnc]  Connections: accepted: 172.17.0.1::36246
universe-psnd10-0 | [tigervnc] 
universe-psnd10-0 | [tigervnc] Mon Dec  5 12:48:20 2016
universe-psnd10-0 | [tigervnc]  Connections: closed: 172.17.0.1::36246 (Clean disconnection)
universe-psnd10-0 | [tigervnc]  EncodeManager: Framebuffer updates: 0
universe-psnd10-0 | [tigervnc]  EncodeManager:   Total: 0 rects, 0 pixels
universe-psnd10-0 | [tigervnc]  EncodeManager:          0 B (1:-nan ratio)
universe-psnd10-0 | [tigervnc]  Connections: accepted: 172.17.0.1::36286
universe-psnd10-0 | [tigervnc]  SConnection: Client needs protocol version 3.8
universe-psnd10-0 | [tigervnc]  SConnection: Client requests security type VncAuth(2)
universe-psnd10-0 | [tigervnc]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
universe-psnd10-0 | [tigervnc]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
universe-psnd10-0 | [tigervnc] 
universe-psnd10-0 | [tigervnc] Mon Dec  5 12:48:49 2016
universe-psnd10-0 | [tigervnc]  Connections: accepted: 127.0.0.1::48294
universe-psnd10-0 | [tigervnc]  SConnection: Client needs protocol version 3.8
universe-psnd10-0 | [tigervnc]  SConnection: Client requests security type VncAuth(2)
universe-psnd10-0 | [tigervnc]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
universe-psnd10-0 | [tigervnc]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
universe-psnd10-0 | [tigervnc] 
universe-psnd10-0 | [tigervnc] Mon Dec  5 12:49:40 2016
universe-psnd10-0 | [tigervnc]  Connections: closed: 172.17.0.1::36286 (Clean disconnection)
universe-psnd10-0 | [tigervnc]  EncodeManager: Framebuffer updates: 516
universe-psnd10-0 | [tigervnc]  EncodeManager:   Tight:
universe-psnd10-0 | [tigervnc]  EncodeManager:     Solid: 61 rects, 3.26606 Mpixels
universe-psnd10-0 | [tigervnc]  EncodeManager:            976 B (1:13386.2 ratio)
universe-psnd10-0 | [tigervnc]  EncodeManager:     Bitmap RLE: 261 rects, 3.17045 Mpixels
universe-psnd10-0 | [tigervnc]  EncodeManager:                 43.0459 KiB (1:287.777 ratio)
[2016-12-05 13:49:40,324] Killing and removing container: id=657c3c28301b3a75e90606a12b29025229d8eed7b516874c2c5a69e655f3ad55. (If this command errors, you can always kill all automanaged environments on this Docker daemon via: docker rm -f $(docker ps -q -a -f 'label=com.openai.automanaged=true')
```
There seem to be some exceptions thrown by the code.

My system is Ubuntu 16.04, running with 8 core cpu, 16 gb of ram, and Titan GPU. 

Do you know what could cause such behavior? Is there something I am missing?

**Comment by gdb** [comment]
This looks like the same issue as https://github.com/openai/universe/issues/6#issuecomment-264947599. Can you follow the instructions there, and paste me the output? I'll close this one as a dupe.
