### ISSUE TITLE
[Docker] Error fetching server API

### ISSUE THREAD

**Issue by HaydnAnderson** [openai/universe#52]
When I run this script, it comes up with the error, but when I remove the ` observation_n = env.reset()` it works fine
```
import gym
import universe  # register the universe environments

env = gym.make('flashgames.CoasterRacer-v0')
observation_n = env.reset()
```

The observation_n error:
```
Traceback (most recent call last):
  File "/home/ubuntu/workspace/gim.py", line 5, in <module>
    observation_n = env.reset()
  File "/home/ubuntu/workspace/gym/gym/core.py", line 137, in reset
    self.configure()
  File "/home/ubuntu/workspace/gym/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "/home/ubuntu/workspace/universe/universe/vectorized/core.py", line 57, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/home/ubuntu/workspace/gym/gym/core.py", line 350, in _configure
    return self.env.configure(*args, **kwargs)
  File "/home/ubuntu/workspace/gym/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "/home/ubuntu/workspace/universe/universe/wrappers/render.py", line 18, in _configure
    super(Render, self)._configure(**kwargs)
  File "/home/ubuntu/workspace/universe/universe/vectorized/core.py", line 57, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/home/ubuntu/workspace/gym/gym/core.py", line 350, in _configure
    return self.env.configure(*args, **kwargs)
  File "/home/ubuntu/workspace/gym/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "/home/ubuntu/workspace/universe/universe/wrappers/throttle.py", line 27, in _configure
    super(Throttle, self)._configure(**kwargs)
  File "/home/ubuntu/workspace/universe/universe/vectorized/core.py", line 57, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/home/ubuntu/workspace/gym/gym/core.py", line 350, in _configure
    return self.env.configure(*args, **kwargs)
  File "/home/ubuntu/workspace/gym/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "/home/ubuntu/workspace/universe/universe/envs/vnc_env.py", line 192, in _configure
    api_key=api_key,
  File "/home/ubuntu/workspace/universe/universe/remotes/build.py", line 19, in build
    n=n,
  File "/home/ubuntu/workspace/universe/universe/remotes/docker_remote.py", line 43, in __init__
    self._assigner = PortAssigner(reuse=reuse)
  File "/home/ubuntu/workspace/universe/universe/remotes/docker_remote.py", line 149, in __init__
    self.client, self.info = get_client()
  File "/home/ubuntu/workspace/universe/universe/remotes/docker_remote.py", line 143, in get_client
    return docker.Client(base_url=host, version=client_api_version), info
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 99, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 124, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
```

**Comment by jderehag** [comment]
I suspect you either dont have the docker service up and running, or you are not running your program with docker access rights.
try "sudo python gim.py"
You can choose whether become part of the docker group, or run any docker commands using sudo.
Have a look at https://docs.docker.com/engine/installation/linux/ubuntulinux/

**Comment by KristianHolsheimer** [comment]
To help out others who might run into the same issues ...

1. Check if the docker service is running. On ubuntu linux, this is done by:
```
$ service docker status
```
This should show you something like:
>     ● docker.service - Docker Application Container Engine
>        Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: e
>        Active: active (running) since za 2017-10-21 12:37:51 CEST; 12min ago
>          Docs: https://docs.docker.com
>      Main PID: 6543 (dockerd)
>         Tasks: 52
>        Memory: 1.9G
>           CPU: 58.025s
>        CGroup: /system.slice/docker.service
>                ├─6543 /usr/bin/dockerd -H fd://
>                ├─6553 docker-containerd -l unix:///var/run/docker/libcontainerd/dock
>                ├─9442 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 1
>                ├─9455 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 5
>                └─9462 docker-containerd-shim 9c5b8a8963e3ee3a4fe9140c00e368d3ac78c0e


If docker is install but it's inactive, you'll see:
>     ● docker.service - Docker Application Container Engine
>        Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: e
>        Active: inactive (dead) since za 2017-10-21 12:56:15 CEST; 3s ago
>          Docs: https://docs.docker.com
>       Process: 6543 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=0/SUCCE
>      Main PID: 6543 (code=exited, status=0/SUCCESS)

In which case you'll need to start it manually:
```
$ sudo service docker start
```
Otherwise, you may need to install docker (see link in @jderehag's comment)
2. Check to see if the docker group exists (if not, install docker):
```
$ cat /etc/group | grep docker
docker:x:999:
```
Add your own username to the docker group:
```
$ sudo adduser $USER docker
```
For this to take effect, you must log out and log back in (see [this post](https://unix.stackexchange.com/questions/149533/id-command-doesnt-show-all-users-groups)).
Check to see if your username is correctly added to the docker group (my username is `kris`):
```
$ cat /etc/group | grep docker
docker:x:999:kris
$ id
uid=1000(kris) gid=1000(kris) groups=1000(kris),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),113(lpadmin),128(sambashare),999(docker)
```
