### ISSUE TITLE
 Failed building wheel for fastzbarlight. Mac OS X.

### ISSUE THREAD

**Issue by bogomazov** [openai/universe#66]
Mac OS X. Cannot install dependencies `pip install -e .` in particular `fastzbarlight`. I tried to install it independently, `brew install zbar` and `zbarlight` wrapper, still same issue on this dependency. What could be the problem? 
```
Obtaining file:///Users/andrey/Documents/workspace/ml/universe
Requirement already satisfied: autobahn in /Library/Python/2.7/site-packages (from universe==0.20.4)
Requirement already satisfied: docker-py==1.10.3 in /Library/Python/2.7/site-packages (from universe==0.20.4)
Requirement already satisfied: docker-pycreds==0.2.1 in /Library/Python/2.7/site-packages (from universe==0.20.4)
Collecting fastzbarlight>=0.0.13 (from universe==0.20.4)
  Using cached fastzbarlight-0.0.14.tar.gz
Collecting go-vncdriver>=0.4.8 (from universe==0.20.4)
  Using cached go_vncdriver-0.4.19.tar.gz
Collecting gym>=0.5.7 (from universe==0.20.4)
Requirement already satisfied: Pillow in /Library/Python/2.7/site-packages (from universe==0.20.4)
Requirement already satisfied: PyYAML in /lib/python2.7/site-packages (from universe==0.20.4)
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from universe==0.20.4)
Collecting twisted (from universe==0.20.4)
Collecting ujson (from universe==0.20.4)
Requirement already satisfied: txaio>=2.5.2 in /Library/Python/2.7/site-packages (from autobahn->universe==0.20.4)
Requirement already satisfied: websocket-client>=0.32.0 in /Library/Python/2.7/site-packages (from docker-py==1.10.3->universe==0.20.4)
Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /Library/Python/2.7/site-packages (from docker-py==1.10.3->universe==0.20.4)
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /Library/Python/2.7/site-packages (from docker-py==1.10.3->universe==0.20.4)
Requirement already satisfied: requests<2.11,>=2.5.2 in /Library/Python/2.7/site-packages (from docker-py==1.10.3->universe==0.20.4)
Requirement already satisfied: numpy in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from go-vncdriver>=0.4.8->universe==0.20.4)
Collecting pyglet>=1.2.0 (from gym>=0.5.7->universe==0.20.4)
  Using cached pyglet-1.2.4-py2-none-any.whl
Collecting constantly>=15.1 (from twisted->universe==0.20.4)
  Using cached constantly-15.1.0-py2.py3-none-any.whl
Requirement already satisfied: incremental>=16.10.1 in /Library/Python/2.7/site-packages (from twisted->universe==0.20.4)
Requirement already satisfied: zope.interface>=3.6.0 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from twisted->universe==0.20.4)
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from zope.interface>=3.6.0->twisted->universe==0.20.4)
Building wheels for collected packages: fastzbarlight, go-vncdriver
  Running setup.py bdist_wheel for fastzbarlight ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/g4/k9l5yf9s3j5232twsrnynhhr0000gn/T/pip-build-pRccj4/fastzbarlight/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/g4/k9l5yf9s3j5232twsrnynhhr0000gn/T/tmpxkno2Jpip-wheel- --python-tag cp27:
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'optional'
    warnings.warn(msg)
  running bdist_wheel
  running build
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... config/install-sh -c -d
  checking for gawk... no
  checking for mawk... no
  checking for nawk... no
  checking for awk... awk
  checking whether make sets $(MAKE)... yes
  checking build system type... i386-apple-darwin15.6.0
  checking host system type... i386-apple-darwin15.6.0
  checking for style of include used by make... GNU
  checking for gcc... gcc
  checking for C compiler default output file name... a.out
  checking whether the C compiler works... yes
  checking whether we are cross compiling... no
  checking for suffix of executables...
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking dependency style of gcc... none
  checking for a sed that does not truncate output... /usr/bin/sed
  checking for grep that handles long lines and -e... /usr/bin/grep
  checking for egrep... /usr/bin/grep -E
  checking for fgrep... /usr/bin/grep -F
  checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
  checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
  checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
  checking the name lister (/usr/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 196608
  checking whether the shell understands some XSI constructs... yes
  checking whether the shell understands "+="... yes
  checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
  checking for objdump... no
  checking how to recognize dependent libraries... pass_all
  checking for ar... ar
  checking for strip... strip
  checking for ranlib... ranlib
  checking command to parse /usr/bin/nm -B output from gcc object... ok
  checking for dsymutil... dsymutil
  checking for nmedit... nmedit
  checking for lipo... lipo
  checking for otool... otool
  checking for otool64... no
  checking for -single_module linker flag... yes
  checking for -exported_symbols_list linker flag... yes
  checking how to run the C preprocessor... gcc -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... yes
  checking for gcc option to produce PIC... -fno-common -DPIC
  checking if gcc PIC flag -fno-common -DPIC works... yes
  checking if gcc static flag -static works... no
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
  checking dynamic linker characteristics... darwin15.6.0 dyld
  checking how to hardcode library paths into programs... immediate
  checking for dlopen in -ldl... yes
  checking whether a program can dlopen itself... yes
  checking whether a statically linked program can dlopen itself... yes
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... yes
  checking whether to build static libraries... yes
  checking for windres... no
  checking host system type... (cached) i386-apple-darwin15.6.0
  checking for gcc... (cached) gcc
  checking whether we are using the GNU C compiler... (cached) yes
  checking whether gcc accepts -g... (cached) yes
  checking for gcc option to accept ISO C89... (cached) none needed
  checking dependency style of gcc... (cached) none
  checking whether gcc and cc understand -c and -o together... yes
  checking for g++... g++
  checking whether we are using the GNU C++ compiler... yes
  checking whether g++ accepts -g... yes
  checking dependency style of g++... none
  checking whether we are using the GNU C++ compiler... (cached) yes
  checking whether g++ accepts -g... (cached) yes
  checking dependency style of g++... (cached) none
  checking how to run the C++ preprocessor... g++ -E
  checking for ld used by g++... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
  checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
  checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
  checking for g++ option to produce PIC... -fno-common -DPIC
  checking if g++ PIC flag -fno-common -DPIC works... yes
  checking if g++ static flag -static works... no
  checking if g++ supports -c -o file.o... yes
  checking if g++ supports -c -o file.o... (cached) yes
  checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
  checking dynamic linker characteristics... darwin15.6.0 dyld
  checking how to hardcode library paths into programs... immediate
  checking for pkg-config... /usr/local/bin/pkg-config
  checking pkg-config is at least version 0.9.0... yes
  checking for xmlto... no
  checking whether to build EAN symbologies... yes
  checking whether to build Code 128 symbology... yes
  checking whether to build Code 39 symbology... yes
  checking whether to build PDF417 symbology... no
  checking whether to build Interleaved 2 of 5 symbology... yes
  checking whether to build QR Code... yes
  checking for library containing clock_gettime... no
  checking for ld used by GCC... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
  checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
  checking for shared library run path origin... done
  checking for iconv... yes
  checking for working iconv... yes
  checking how to link with libiconv... -liconv
  checking for iconv declaration...
           extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
  checking poll.h usability... yes
  checking poll.h presence... yes
  checking for poll.h... yes
  checking pthread.h usability... yes
  checking pthread.h presence... yes
  checking for pthread.h... yes
  checking for pthread_create in -lpthread... yes
  checking for X... disabled
  checking for X11/extensions/XShm.h... yes
  checking for XShmQueryVersion in -lXext... no
  configure: error: in `/private/var/folders/g4/k9l5yf9s3j5232twsrnynhhr0000gn/T/pip-build-pRccj4/fastzbarlight/src/fastzbarlight/vendor/zbar-0.10':
  configure: error: unable to find XShmQueryVersion in -lXext!
  specify XSHM_LIBS or configure --without-xshm to disable the extension
  See `config.log' for more details.
  Could not build fastzbarlight: Command '['./configure', '--disable-dependency-tracking', '--without-python', '--without-qt', '--disable-video', '--without-gtk', '--without-imagemagick', '--with-x=no', 'CFLAGS=-Wall -Wno-parentheses -D_FORTIFY_SOURCE=0 -O3 -fPIC']' returned non-zero exit status 1.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/g4/k9l5yf9s3j5232twsrnynhhr0000gn/T/pip-build-pRccj4/fastzbarlight/setup.py", line 98, in <module>
      cmdclass={'build': Build},
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Library/Python/2.7/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/g4/k9l5yf9s3j5232twsrnynhhr0000gn/T/pip-build-pRccj4/fastzbarlight/setup.py", line 31, in run
      subprocess.check_call(cmd, cwd=zbar)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['./configure', '--disable-dependency-tracking', '--without-python', '--without-qt', '--disable-video', '--without-gtk', '--without-imagemagick', '--with-x=no', 'CFLAGS=-Wall -Wno-parentheses -D_FORTIFY_SOURCE=0 -O3 -fPIC']' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for fastzbarlight
  Running setup.py clean for fastzbarlight
  Running setup.py bdist_wheel for go-vncdriver ... done
  Stored in directory: /Users/andrey/Library/Caches/pip/wheels/13/24/dc/91144da4ef4bc1c2b2f01338c79a9361edbf574d3362c7192d
Successfully built go-vncdriver
Failed to build fastzbarlight
Installing collected packages: fastzbarlight, go-vncdriver, pyglet, gym, constantly, twisted, ujson, universe
  Running setup.py install for fastzbarlight ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/g4/k9l5yf9s3j5232twsrnynhhr0000gn/T/pip-build-pRccj4/fastzbarlight/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/g4/k9l5yf9s3j5232twsrnynhhr0000gn/T/pip-z1JH8m-record/install-record.txt --single-version-externally-managed --compile:
    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'optional'
      warnings.warn(msg)
    running install
    running build
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... config/install-sh -c -d
    checking for gawk... no
    checking for mawk... no
    checking for nawk... no
    checking for awk... awk
    checking whether make sets $(MAKE)... yes
    checking build system type... i386-apple-darwin15.6.0
    checking host system type... i386-apple-darwin15.6.0
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking for C compiler default output file name... a.out
    checking whether the C compiler works... yes
    checking whether we are cross compiling... no
    checking for suffix of executables...
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking dependency style of gcc... none
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
    checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 196608
    checking whether the shell understands some XSI constructs... yes
    checking whether the shell understands "+="... yes
    checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
    checking for objdump... no
    checking how to recognize dependent libraries... pass_all
    checking for ar... ar
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for dsymutil... dsymutil
    checking for nmedit... nmedit
    checking for lipo... lipo
    checking for otool... otool
    checking for otool64... no
    checking for -single_module linker flag... yes
    checking for -exported_symbols_list linker flag... yes
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... yes
    checking for gcc option to produce PIC... -fno-common -DPIC
    checking if gcc PIC flag -fno-common -DPIC works... yes
    checking if gcc static flag -static works... no
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
    checking dynamic linker characteristics... darwin15.6.0 dyld
    checking how to hardcode library paths into programs... immediate
    checking for dlopen in -ldl... yes
    checking whether a program can dlopen itself... yes
    checking whether a statically linked program can dlopen itself... yes
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking for windres... no
    checking host system type... (cached) i386-apple-darwin15.6.0
    checking for gcc... (cached) gcc
    checking whether we are using the GNU C compiler... (cached) yes
    checking whether gcc accepts -g... (cached) yes
    checking for gcc option to accept ISO C89... (cached) none needed
    checking dependency style of gcc... (cached) none
    checking whether gcc and cc understand -c and -o together... yes
    checking for g++... g++
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking dependency style of g++... none
    checking whether we are using the GNU C++ compiler... (cached) yes
    checking whether g++ accepts -g... (cached) yes
    checking dependency style of g++... (cached) none
    checking how to run the C++ preprocessor... g++ -E
    checking for ld used by g++... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
    checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
    checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
    checking for g++ option to produce PIC... -fno-common -DPIC
    checking if g++ PIC flag -fno-common -DPIC works... yes
    checking if g++ static flag -static works... no
    checking if g++ supports -c -o file.o... yes
    checking if g++ supports -c -o file.o... (cached) yes
    checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
    checking dynamic linker characteristics... darwin15.6.0 dyld
    checking how to hardcode library paths into programs... immediate
    checking for pkg-config... /usr/local/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for xmlto... no
    checking whether to build EAN symbologies... yes
    checking whether to build Code 128 symbology... yes
    checking whether to build Code 39 symbology... yes
    checking whether to build PDF417 symbology... no
    checking whether to build Interleaved 2 of 5 symbology... yes
    checking whether to build QR Code... yes
    checking for library containing clock_gettime... no
    checking for ld used by GCC... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
    checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
    checking for shared library run path origin... done
    checking for iconv... yes
    checking for working iconv... yes
    checking how to link with libiconv... -liconv
    checking for iconv declaration...
             extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
    checking poll.h usability... yes
    checking poll.h presence... yes
    checking for poll.h... yes
    checking pthread.h usability... yes
    checking pthread.h presence... yes
    checking for pthread.h... yes
    checking for pthread_create in -lpthread... yes
    checking for X... disabled
    checking for X11/extensions/XShm.h... yes
    checking for XShmQueryVersion in -lXext... no
    configure: error: in `/private/var/folders/g4/k9l5yf9s3j5232twsrnynhhr0000gn/T/pip-build-pRccj4/fastzbarlight/src/fastzbarlight/vendor/zbar-0.10':
    configure: error: unable to find XShmQueryVersion in -lXext!
    specify XSHM_LIBS or configure --without-xshm to disable the extension
    See `config.log' for more details.
    Could not build fastzbarlight: Command '['./configure', '--disable-dependency-tracking', '--without-python', '--without-qt', '--disable-video', '--without-gtk', '--without-imagemagick', '--with-x=no', 'CFLAGS=-Wall -Wno-parentheses -D_FORTIFY_SOURCE=0 -O3 -fPIC']' returned non-zero exit status 1.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/g4/k9l5yf9s3j5232twsrnynhhr0000gn/T/pip-build-pRccj4/fastzbarlight/setup.py", line 98, in <module>
        cmdclass={'build': Build},
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 53, in run
        return _install.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
        self.run_command('build')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/g4/k9l5yf9s3j5232twsrnynhhr0000gn/T/pip-build-pRccj4/fastzbarlight/setup.py", line 31, in run
        subprocess.check_call(cmd, cwd=zbar)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['./configure', '--disable-dependency-tracking', '--without-python', '--without-qt', '--disable-video', '--without-gtk', '--without-imagemagick', '--with-x=no', 'CFLAGS=-Wall -Wno-parentheses -D_FORTIFY_SOURCE=0 -O3 -fPIC']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/g4/k9l5yf9s3j5232twsrnynhhr0000gn/T/pip-build-pRccj4/fastzbarlight/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/g4/k9l5yf9s3j5232twsrnynhhr0000gn/T/pip-z1JH8m-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/g4/k9l5yf9s3j5232twsrnynhhr0000gn/T/pip-build-pRccj4/fastzbarlight/

```

**Comment by tlbtlbtlb** [comment]
Do you have XQuartz installed? If not, `brew install Caskroom/cask/xquartz` and try again.

If it still doesn't work, can you include the `config.log` file mentioned in the error message?

**Comment by dgobaud** [comment]
also getting an error but only with pip3 - installing with pip worked.

```
Installing collected packages: fastzbarlight, go-vncdriver, gym, Pillow, twisted, ujson, universe, txaio, pyglet, zope.interface, constantly
  Running setup.py install for fastzbarlight
    error: Permission denied
    Complete output from command /usr/local/Cellar/python3/3.3.3/bin/python3 -c "import setuptools;__file__='/private/tmp/pip_build_root/fastzbarlight/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-92es7s-record/install-record.txt --single-version-externally-managed:
    running install

running build

error: Permission denied

----------------------------------------
Cleaning up...
Command /usr/local/Cellar/python3/3.3.3/bin/python3 -c "import setuptools;__file__='/private/tmp/pip_build_root/fastzbarlight/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-92es7s-record/install-record.txt --single-version-externally-managed failed with error code 1 in /private/tmp/pip_build_root/fastzbarlight
```

**Comment by bogomazov** [comment]
I checked that `xquartz` is intalled and up to date. I also couldn't find `config.log` around
`/private/var/folders/g4/k9l5yf9s3j5232twsrnynhhr0000gn/T/pip-build-pRccj4/fastzbarlight/src/fastzbarlight/vendor/zbar-0.10`
because apparently `/private/var/folders/g4/k9l5yf9s3j5232twsrnynhhr0000gn/T/pip-build-*` is temporary. I assume it is better to use docker for now.

**Comment by Dexdev08** [comment]
@bogomazov  i encountered the same problem, would be able to share what was the solution?
