### ISSUE TITLE
[Docker] Unable to fetch docker image 

### ISSUE THREAD

**Issue by traw1234** [openai/universe#70]
I think the issue is the Tegra architecture, once again, (Jetson TX1, Ubuntu 16.04). When I attempt to run the sample code provided by OpenAI, I get this error: 

> sudo python uni.py 
[2016-12-20 21:10:19,499] Making new env: flashgames.DuskDrive-v0
[2016-12-20 21:10:19,509] Writing logs to file: /tmp/universe-14093.log
[2016-12-20 21:10:19,637] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.9. Run the same thing by hand as: docker run -p 5900:5900 -p 15900:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.9
[2016-12-20 21:10:21,464] Remote closed: address=localhost:15900
[2016-12-20 21:10:21,470] Remote closed: address=localhost:5900
[2016-12-20 21:10:21,472] At least one sockets was closed by the remote. Sleeping 1s...
universe-dRjMt2-0 | write pipe: bad file descriptor
[2016-12-20 21:10:22,474] Remote closed: address=localhost:5900
[2016-12-20 21:10:22,474] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:23,475] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:24,477] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:25,479] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:26,481] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:27,482] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:28,484] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:29,485] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:30,487] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:31,489] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:32,491] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:33,492] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:34,494] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:35,496] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:36,498] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:37,500] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:38,502] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:39,503] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:40,505] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:41,507] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:42,509] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:43,511] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:44,513] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:45,515] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:46,516] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:47,518] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:48,520] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:49,522] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:50,524] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-20 21:10:51,525] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
Traceback (most recent call last):
  File "uni.py", line 5, in <module>
    env.configure(remotes=1)  # automatically creates a local docker container
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "/home/ubuntu/git/universe/universe/vectorized/core.py", line 57, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 350, in _configure
    return self.env.configure(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "/home/ubuntu/git/universe/universe/wrappers/render.py", line 18, in _configure
    super(Render, self)._configure(**kwargs)
  File "/home/ubuntu/git/universe/universe/vectorized/core.py", line 57, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 350, in _configure
    return self.env.configure(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "/home/ubuntu/git/universe/universe/wrappers/throttle.py", line 27, in _configure
    super(Throttle, self)._configure(**kwargs)
  File "/home/ubuntu/git/universe/universe/vectorized/core.py", line 57, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 350, in _configure
    return self.env.configure(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "/home/ubuntu/git/universe/universe/envs/vnc_env.py", line 194, in _configure
    api_key=api_key,
  File "/home/ubuntu/git/universe/universe/remotes/build.py", line 19, in build
    n=n,
  File "/home/ubuntu/git/universe/universe/remotes/docker_remote.py", line 54, in __init__
    self._start()
  File "/home/ubuntu/git/universe/universe/remotes/docker_remote.py", line 83, in _start
    self.healthcheck(self.instances)
  File "/home/ubuntu/git/universe/universe/remotes/docker_remote.py", line 108, in healthcheck
    start_timeout=30,
  File "/home/ubuntu/git/universe/universe/remotes/healthcheck.py", line 14, in run
    healthcheck.run()
  File "/home/ubuntu/git/universe/universe/remotes/healthcheck.py", line 131, in run
    self._register_vnc(address)
  File "/home/ubuntu/git/universe/universe/remotes/healthcheck.py", line 63, in _register_vnc
    raise error.Error('VNC server {} did not come up within {}s'.format(address, self.start_timeout))
universe.error.Error: VNC server localhost:5900 did not come up within 30s
[2016-12-20 21:10:52,528] Killing and removing container: id=98a5918e6619f65093d5e6fecf122e4688ac41f2caf3143b5274f522d99d420f. (If this command errors, you can always kill all automanaged environments on this Docker daemon via: docker rm -f $(docker ps -q -a -f 'label=com.openai.automanaged=true')

I think the issue is Docker, so I tried to run `sudo docker run -p 5900:5900 -p 15900:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.9` as described in the error, but I just get `write pipe: bad file descriptor`. I previously got this error when attempting to run `hello-world`, but I solved that by using `sudo docker run aarch64/hello-world`. I'm not sure about a similar fix for the flashgames container.

**Comment by tlbtlbtlb** [comment]
The container image is built for x86-64 so it won't run on ARM.

Are you planning to run on large numbers of ARMs? Could you run the container half of the system on Intel boxes instead? The container image itself doesn't benefit from the Tegra GPU integration, it's just a web browser + X11 + Flash. 

To run the container image on a regular x86-64 server while running the agent on Tegra, set up a Docker machine on an X86-64 box and run `$ export DOCKER_HOST=my-x86-host` before running  your agent code.

**Comment by traw1234** [comment]
So the agent could be running on the Tegra with just the VNC viewer running on my x86-64 machine? Any way you could give a bit more detail on how to go about this? How exactly would the two machines be connected? Need to be the same OS? Thanks for the tip, ita greatly appreciated.

**Comment by tlbtlbtlb** [comment]
They don't need to be the same OS or architecture. Your python code with `import universe` connects to TCP ports on the container, and exchanges data in an architecture-neutral way. 

The easiest way to run it is,
```
x86-64-machine$  docker run -p 5900:5900 -p 15900:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.9
tegra-machine$ python uni.py --remotes vnc://x86-64-machine:5900+15900
```

**Comment by traw1234** [comment]
I followed everything you said (create docker-machine on x86-64, setup to be DOCKER_HOST, ran the said `docker run` command on x86-64, then ran the uni.py on the Tegra machine as said) though I'm still getting the same errors. The --remotes flag doesn't seem to be doing anything, as I am getting the exact same error as when I ran it without it. I've tried the IP to my x86-64 machine, my docker-machine (with and without the port), still nothing.

**Comment by tlbtlbtlb** [comment]
Does your uni.py script pass the `--remotes` argument to `env.configure` the [same way universe-starter-agent does](https://github.com/openai/universe-starter-agent/blob/5fcb23cf897cbd8b12c2ed512b0b56d12c061a4b/envs.py#L46)?

**Comment by traw1234** [comment]
I don't believe so, its just the default test script given by Universe.

    import gym
    import universe  # register the universe environments
    
    env = gym.make('flashgames.DuskDrive-v0')
    env.configure(remotes=1)  # automatically creates a local docker container
    observation_n = env.reset()

    while True:
      action_n = [[('KeyEvent', 'ArrowUp', True)] for ob in observation_n]  # your agent here
      observation_n, reward_n, done_n, info = env.step(action_n)
      env.render()

**Comment by tlbtlbtlb** [comment]
Ah, you need
```
   env.configure(remotes='vnc://x86-machine.local:5900+15900')
```

**Comment by traw1234** [comment]
Ok that makes more sense. Am I using the x86-64 machine's IP or the docker-machine's IP (with or without the port)? When I tried both, I get this error now:

    sudo python uni.py 
    [2016-12-21 17:24:44,394] Making new env: flashgames.DuskDrive-v0
    [2016-12-21 17:24:44,406] Writing logs to file: /tmp/universe-10429.log
    [2016-12-21 17:24:44,409] Using the golang VNC implementation
    [2016-12-21 17:24:44,410] Using VNCSession arguments: {'subsample_level': 2, 'start_timeout': 7, 'fine_quality_level': 50, 'encoding': 'tight'}. (Customize by running "env.configure(vnc_kwargs={...})"
    [2016-12-21 17:24:44,414] [0] Connecting to environment: vnc://192.168.0.18:5900 password=openai.          Use the browser-based VNC client: http://192.168.0.18:15900/viewer/?password=openai
    2016/12/21 17:24:44 I1221 17:24:44.415638 10429 gymvnc.go:417] [0:192.168.0.18:5900] opening connection to VNC server
    Traceback (most recent call last):
      File "uni.py", line 10, in <module>
        observation_n, reward_n, done_n, info = env.step(action_n)
      File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 122, in step
        observation, reward, done, info = self._step(action)
      File "/home/ubuntu/git/universe/universe/wrappers/timer.py", line 20, in _step
        observation_n, reward_n, done_n, info = self.env.step(action_n)
      File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 122, in step
        observation, reward, done, info = self._step(action)
      File "/home/ubuntu/git/universe/universe/wrappers/render.py", line 30, in _step
        observation_n, reward_n, done_n, info_n = self.env.step(action_n)
      File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 122, in step
        observation, reward, done, info = self._step(action)
      File "/home/ubuntu/git/universe/universe/wrappers/throttle.py", line 51, in _step
        accum_observation_n, accum_reward_n, accum_done_n, accum_info = self._substep(action_n)
      File "/home/ubuntu/git/universe/universe/wrappers/throttle.py", line 132, in _substep
        observation_n, reward_n, done_n, info = self.env.step(action_n)
      File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 122, in step
        observation, reward, done, info = self._step(action)
      File "/home/ubuntu/git/universe/universe/envs/vnc_env.py", line 406, in _step
        action_n, peek_d = self._compile_actions(action_n)
      File "/home/ubuntu/git/universe/universe/envs/vnc_env.py", line 391, in _compile_actions
        raise error.Error('Could not compile actions. Original error: {} ({}). action_n={}'.format(e, type(e), action_n))
    universe.error.Error: Could not compile actions. Original error: 'str' object has no attribute 'compile' (<type 'exceptions.AttributeError'>). action_n=[['KeyEvent', 'ArrowUp', True]]

**Comment by tlbtlbtlb** [comment]
The action is wrong (see at the end: `action_n=[['KeyEvent', 'ArrowUp', True]]`). There should be a tuple wrapping the event, so  `[[('KeyEvent', 'ArrowUp', True)]]`. But your uni.py script pasted above looks like it has the correct tuple nesting. 

I can reproduce the same error if I remove the parenthesis. Are you sure your uni.py didn't lose some parentheses in copy-pasting?

If it's not a copy-paste error, you should be able to run the  debugger on it, `python -m pdb uni.py` and get a breakpoint where the error happens, and look up the stack trace to see where the tuple wrapping disappeared.

**Comment by traw1234** [comment]
Yeah, I copied that directly from the Universe repo, seemed to solve the issue. What IP should I be using? My docker-machine or just the x86-64 machine's IP? Because the docker-machine has its own port (instead of 5900+15900).

**Comment by tlbtlbtlb** [comment]
Try adding `--network host` to the `docker run` command. That should make it use the host's IP address instead of a local one. (We should add some documentation about this).

You can tell whether it's working by telnetting to port 5900. If it works, you'll see a version string `RFB 003.008`. From the agent machine:
```
$ telnet 192.168.0.18 5900
Escape character is '^]'.
RFB 003.008
^]
telnet> quit
Connection closed.
```

**Comment by traw1234** [comment]
I get RFB `003.889`. Some resources say this is fine, but it still gives the same error when I run the script.

**Comment by tlbtlbtlb** [comment]
Ah, sounds like you're running the container on Docker for Mac rather than a Linux host. The agent is connecting to the Mac's VNC server, not the container's internal one.

I don't think Docker for Mac has an option to let containers listen on external ports. Lots of detail at https://docs.docker.com/engine/userguide/networking/.

It'd be a lot easier to run the agent on the Mac. But if you really want to run on the Tegra, you could try using ssh to forward ports. Like this, in a separate terminal window:

```
tegra-machine$ ssh -L 5900:localhost:5900 -L 15900:localhost:15900 mac-machine
```

and leave it running. Then change the remotes string to `vnc://localhost:5900+15900`.

You should install, on the Tegra box, a vnc viewer like [TurboVNC](http://turbovnc.org/). And try opening `localhost:5900`. If it's working, you'll see an X11 desktop with a Firefox browser open to a page with a long bulleted list of environments.

**Comment by traw1234** [comment]
I ran the x86-64 machine off Arch instead of macOS, got it working now. Definitely much more stable running the agent off the Tegra machine. Thanks for the help.
