### ISSUE TITLE
OSX error starting local docker(env.configure step)

### ISSUE THREAD

**Issue by dgobaud** [openai/universe#71]
This is on OSX 10.12.1 with python 2.7.11 - can't use python 3.3.3 because of #51 

```
env.configure(remotes=1)
[2016-12-20 21:13:14,210] Writing logs to file: /tmp/universe-37891.log
[2016-12-20 21:13:14,281] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.14. Run the same thing by hand as: docker run -p 5900:5900 -p 15900:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.14
[2016-12-20 21:13:14,893] [0] Could not start container: 500 Server Error: Internal Server Error ("{"message":"driver failed programming external connectivity on endpoint universe-VY74mz-0 (323afc3f04d0c9579503e1801c78b023dfcadf8ac222080b8698e9cf0210008e): Error starting userland proxy: Bind for 0.0.0.0:5900 failed: port is already allocated"}")
[2016-12-20 21:13:14,894] Killing and removing container: id=e6a66178c27cdb0e2cf9be08d9f2ef3237f3efa15c76153caadb995d4ac9a130. (If this command errors, you can always kill all automanaged environments on this Docker daemon via: docker rm -f $(docker ps -q -a -f 'label=com.openai.automanaged=true')
[2016-12-20 21:13:14,929] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.14. Run the same thing by hand as: docker run -p 5901:5900 -p 15901:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.14
[2016-12-20 21:13:15,592] Remote closed: address=localhost:5901
[2016-12-20 21:13:15,593] At least one sockets was closed by the remote. Sleeping 1s...
universe-VY74mz-0 | Setting VNC and rewarder password: openai
universe-VY74mz-0 | [Wed Dec 21 05:13:15 UTC 2016] Waiting for /tmp/.X11-unix/X0 to be created (try 1/10)
universe-VY74mz-0 | [Wed Dec 21 05:13:15 UTC 2016] [/usr/local/bin/sudoable-env-setup] Disabling outbound network traffic for none
universe-VY74mz-0 | Traceback (most recent call last):
universe-VY74mz-0 |   File "/app/universe-envs/flashgames/init", line 262, in <module>
universe-VY74mz-0 |     sys.exit(main())
universe-VY74mz-0 |   File "/app/universe-envs/flashgames/init", line 243, in main
universe-VY74mz-0 |     setup_logdir(recorder_logdir)
universe-VY74mz-0 |   File "/app/universe-envs/flashgames/init", line 119, in setup_logdir
universe-VY74mz-0 |     os.makedirs(path, exist_ok=True)
universe-VY74mz-0 |   File "/usr/lib/python3.5/os.py", line 226, in makedirs
universe-VY74mz-0 |     head, tail = path.split(name)
universe-VY74mz-0 |   File "/usr/lib/python3.5/posixpath.py", line 103, in split
universe-VY74mz-0 |     i = p.rfind(sep) + 1
universe-VY74mz-0 | AttributeError: 'NoneType' object has no attribute 'rfind'
[2016-12-20 21:13:16,597] Remote closed: address=localhost:5901
[2016-12-20 21:13:16,598] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:17,601] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:18,603] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:19,605] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:20,608] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:21,610] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:22,612] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:23,613] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:24,615] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:25,617] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:26,620] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:27,622] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:28,624] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:29,626] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:30,628] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:31,633] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:32,635] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:33,645] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:34,650] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:35,656] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:36,663] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:37,665] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:38,671] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:39,672] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:40,675] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:41,678] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:42,680] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:43,686] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:44,688] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
[2016-12-20 21:13:45,690] VNC server localhost:5901 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "universe/vectorized/core.py", line 63, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 350, in _configure
    return self.env.configure(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "universe/wrappers/render.py", line 18, in _configure
    super(Render, self)._configure(**kwargs)
  File "universe/vectorized/core.py", line 63, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 350, in _configure
    return self.env.configure(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "universe/wrappers/throttle.py", line 27, in _configure
    super(Throttle, self)._configure(**kwargs)
  File "universe/vectorized/core.py", line 63, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 350, in _configure
    return self.env.configure(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 246, in configure
    self._configure(*args, **kwargs)
  File "universe/envs/vnc_env.py", line 196, in _configure
    use_recorder_ports=record,
  File "universe/remotes/build.py", line 19, in build
    n=n,
  File "universe/remotes/docker_remote.py", line 54, in __init__
    self._start()
  File "universe/remotes/docker_remote.py", line 83, in _start
    self.healthcheck(self.instances)
  File "universe/remotes/docker_remote.py", line 108, in healthcheck
    start_timeout=30,
  File "universe/remotes/healthcheck.py", line 14, in run
    healthcheck.run()
  File "universe/remotes/healthcheck.py", line 131, in run
    self._register_vnc(address)
  File "universe/remotes/healthcheck.py", line 63, in _register_vnc
    raise error.Error('VNC server {} did not come up within {}s'.format(address, self.start_timeout))
universe.error.Error: VNC server localhost:5901 did not come up within 30s```

**Comment by VerkkuUkkeli** [comment]
I have the same issue with macOS 10.12.1 and python 3.5.2. 

This problem seems to be limited to flashgames only. Games such as `gym-core.Pong-v3` and `gym-core.CartPole-v0` run just fine.

The traceback points at `"/app/universe-envs/flashgames/init"` and similar files, which do not seem to exist at my computer. Are these directories part of the flashgames docker image?

**Comment by tlbtlbtlb** [comment]
@jonathathan I think this is due to https://github.com/openai/universe-envs/commit/6a33e8976349862852b4f59a70453a9cc54c20d0#diff-673e3a6fd90e25e7f001e7b0fe61d763

**Comment by tlbtlbtlb** [comment]
Should be fixed by https://github.com/openai/universe-envs/commit/6b1404493911b4ca94b337ba1dddc5e74dd57065

**Comment by KaixiangLin** [comment]
Cannot open the link above, could you be more specific? Thanks.

**Comment by VerkkuUkkeli** [comment]
Yes, the the links show 404 page not found errors, but I did get it to work after the fix.
I ran `git pull` on the Universe directory I cloned from the github page and ran the installation script again.

**Comment by tlbtlbtlb** [comment]
@KaixiangLin sorry, that's an internal repo, but it's incorporated in the latest universe commit.

**Comment by ysj89** [comment]
I have the same issue with macOS 10.12.1 and python 3.5.2. Just installed universe. The game gym-core.Pong-v3 does work, but flashgames.DuskDrive-v0 (example code) does not.

**Comment by tlbtlbtlb** [comment]
@ysj89 Can you provide a console log using the latest commit of universe?

**Comment by dgobaud** [comment]
@tlbtlbtlb fixed it for me thanks!

**Comment by KaixiangLin** [comment]
worked on my Mac with python2.7 in anaconda, tensorflow 0.12 @tlbtlbtlb thanks.

**Comment by tlbtlbtlb** [comment]
Closing, reopen if you still have failures with the most recent code.
