### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by KaixiangLin** [openai/universe#72]
I am using python 2.7 tensorflow 0.12 installed in Anaconda env on ubuntu 14.04. 

I run the test code on the blog it gives me error like:

```
[2016-12-21 16:27:10,678] Making new env: flashgames.DuskDrive-v0
[2016-12-21 16:27:10,681] Writing logs to file: /tmp/universe-2172.log
[2016-12-21 16:27:10,690] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.14. Run the same thing by hand as: docker run -p 5900:5900 -p 15900:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.14
[2016-12-21 16:27:12,443] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
^[[36muniverse-E1PURp-0 |^[[0m Setting VNC and rewarder password: openai
^[[36muniverse-E1PURp-0 |^[[0m [Wed Dec 21 21:27:11 UTC 2016] Waiting for /tmp/.X11-unix/X0 to be created (try 1/10)
^[[36muniverse-E1PURp-0 |^[[0m [Wed Dec 21 21:27:11 UTC 2016] [/usr/local/bin/sudoable-env-setup] Disabling outbound network traffic for none
^[[36muniverse-E1PURp-0 |^[[0m Traceback (most recent call last):
^[[36muniverse-E1PURp-0 |^[[0m   File "/app/universe-envs/flashgames/init", line 262, in <module>
^[[36muniverse-E1PURp-0 |^[[0m     sys.exit(main())
^[[36muniverse-E1PURp-0 |^[[0m   File "/app/universe-envs/flashgames/init", line 243, in main
^[[36muniverse-E1PURp-0 |^[[0m     setup_logdir(recorder_logdir)
^[[36muniverse-E1PURp-0 |^[[0m   File "/app/universe-envs/flashgames/init", line 119, in setup_logdir
^[[36muniverse-E1PURp-0 |^[[0m     os.makedirs(path, exist_ok=True)
^[[36muniverse-E1PURp-0 |^[[0m   File "/usr/lib/python3.5/os.py", line 226, in makedirs
^[[36muniverse-E1PURp-0 |^[[0m     head, tail = path.split(name)
^[[36muniverse-E1PURp-0 |^[[0m   File "/usr/lib/python3.5/posixpath.py", line 103, in split
^[[36muniverse-E1PURp-0 |^[[0m     i = p.rfind(sep) + 1
^[[36muniverse-E1PURp-0 |^[[0m AttributeError: 'NoneType' object has no attribute 'rfind'

```
Detailed output and log attached. 

Any suggestions would help.  thanks a lot! 

[output.txt](https://github.com/openai/universe/files/667407/output.txt)
[universe-2172_log.txt](https://github.com/openai/universe/files/667408/universe-2172_log.txt)

**Comment by KaixiangLin** [comment]
found it duplicate to #71
