### ISSUE TITLE
Unable to start DuskDrive-v0

### ISSUE THREAD

**Issue by kvmanohar22** [openai/universe#77]
I followed all the instructions given [here](https://github.com/openai/universe#installation) and when I execute the piece of code for `flashgames.DuskDrive-vo` given [here](https://github.com/openai/universe#run-your-first-agent) using `ipython` (for `python 2.7.6`) I run into the following errors:

```
In [1]: import gym

In [2]: import universe

In [3]: env = gym.make('flashgames.DuskDrive-v0')
[2016-12-23 02:45:44,996] Making new env: flashgames.DuskDrive-v0

In [4]: env.configure(remotes=1)
[2016-12-23 02:45:49,038] Writing logs to file: /tmp/universe-26977.log
[2016-12-23 02:45:49,072] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.14. Run the same thing by hand as: docker run -p 5900:5900 -p 15900:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.14
[2016-12-23 02:45:50,080] Remote closed: address=localhost:5900
[2016-12-23 02:45:50,081] At least one sockets was closed by the remote. Sleeping 1s...
universe-zJjC2h-0 | Setting VNC and rewarder password: openai
universe-zJjC2h-0 | [Thu Dec 22 21:15:50 UTC 2016] Waiting for /tmp/.X11-unix/X0 to be created (try 1/10)
universe-zJjC2h-0 | [Thu Dec 22 21:15:50 UTC 2016] [/usr/local/bin/sudoable-env-setup] Disabling outbound network traffic for none
universe-zJjC2h-0 | Traceback (most recent call last):
universe-zJjC2h-0 |   File "/app/universe-envs/flashgames/init", line 262, in <module>
universe-zJjC2h-0 |     sys.exit(main())
universe-zJjC2h-0 |   File "/app/universe-envs/flashgames/init", line 243, in main
universe-zJjC2h-0 |     setup_logdir(recorder_logdir)
universe-zJjC2h-0 |   File "/app/universe-envs/flashgames/init", line 119, in setup_logdir
universe-zJjC2h-0 |     os.makedirs(path, exist_ok=True)
universe-zJjC2h-0 |   File "/usr/lib/python3.5/os.py", line 226, in makedirs
universe-zJjC2h-0 |     head, tail = path.split(name)
universe-zJjC2h-0 |   File "/usr/lib/python3.5/posixpath.py", line 103, in split
universe-zJjC2h-0 |     i = p.rfind(sep) + 1
universe-zJjC2h-0 | AttributeError: 'NoneType' object has no attribute 'rfind'
[2016-12-23 02:45:51,083] Remote closed: address=localhost:15900
[2016-12-23 02:45:51,083] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:45:52,084] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:45:53,086] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:45:54,087] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:45:55,089] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:45:56,090] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:45:57,092] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:45:58,094] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:45:59,096] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:00,097] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:01,099] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:02,101] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:03,103] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:04,104] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:05,106] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:06,108] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:07,111] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:08,113] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:09,114] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:10,116] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:11,117] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:12,119] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:13,120] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:14,122] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:15,124] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:16,126] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:17,127] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:18,129] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:19,131] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
[2016-12-23 02:46:20,133] Rewarder server localhost:15900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-4-ea3178828858> in <module>()
----> 1 env.configure(remotes=1)

/usr/local/lib/python2.7/dist-packages/gym/core.pyc in configure(self, *args, **kwargs)
    244 
    245         try:
--> 246             self._configure(*args, **kwargs)
    247         except TypeError as e:
    248             # It can be confusing if you have the wrong environment

/home/kv/universe/universe/vectorized/core.pyc in _configure(self, **kwargs)
     61 
     62     def _configure(self, **kwargs):
---> 63         super(Wrapper, self)._configure(**kwargs)
     64         assert self.env.n is not None, "Did not set self.env.n: self.n={} self.env={} self={}".format(self.env.n, self.env, self)
     65         self.n = self.env.n

/usr/local/lib/python2.7/dist-packages/gym/core.pyc in _configure(self, *args, **kwargs)
    348 
    349     def _configure(self, *args, **kwargs):
--> 350         return self.env.configure(*args, **kwargs)
    351 
    352     def _seed(self, seed=None):

/usr/local/lib/python2.7/dist-packages/gym/core.pyc in configure(self, *args, **kwargs)
    244 
    245         try:
--> 246             self._configure(*args, **kwargs)
    247         except TypeError as e:
    248             # It can be confusing if you have the wrong environment

/home/kv/universe/universe/wrappers/render.pyc in _configure(self, **kwargs)
     16 
     17     def _configure(self, **kwargs):
---> 18         super(Render, self)._configure(**kwargs)
     19         self.metadata = self.metadata.copy()
     20         modes = self.metadata.setdefault('render.modes', [])

/home/kv/universe/universe/vectorized/core.pyc in _configure(self, **kwargs)
     61 
     62     def _configure(self, **kwargs):
---> 63         super(Wrapper, self)._configure(**kwargs)
     64         assert self.env.n is not None, "Did not set self.env.n: self.n={} self.env={} self={}".format(self.env.n, self.env, self)
     65         self.n = self.env.n

/usr/local/lib/python2.7/dist-packages/gym/core.pyc in _configure(self, *args, **kwargs)
    348 
    349     def _configure(self, *args, **kwargs):
--> 350         return self.env.configure(*args, **kwargs)
    351 
    352     def _seed(self, seed=None):

/usr/local/lib/python2.7/dist-packages/gym/core.pyc in configure(self, *args, **kwargs)
    244 
    245         try:
--> 246             self._configure(*args, **kwargs)
    247         except TypeError as e:
    248             # It can be confusing if you have the wrong environment

/home/kv/universe/universe/wrappers/throttle.pyc in _configure(self, skip_metadata, fps, **kwargs)
     25 
     26     def _configure(self, skip_metadata=False, fps='default', **kwargs):
---> 27         super(Throttle, self)._configure(**kwargs)
     28         if fps == 'default':
     29             fps = self.metadata['video.frames_per_second']

/home/kv/universe/universe/vectorized/core.pyc in _configure(self, **kwargs)
     61 
     62     def _configure(self, **kwargs):
---> 63         super(Wrapper, self)._configure(**kwargs)
     64         assert self.env.n is not None, "Did not set self.env.n: self.n={} self.env={} self={}".format(self.env.n, self.env, self)
     65         self.n = self.env.n

/usr/local/lib/python2.7/dist-packages/gym/core.pyc in _configure(self, *args, **kwargs)
    348 
    349     def _configure(self, *args, **kwargs):
--> 350         return self.env.configure(*args, **kwargs)
    351 
    352     def _seed(self, seed=None):

/usr/local/lib/python2.7/dist-packages/gym/core.pyc in configure(self, *args, **kwargs)
    244 
    245         try:
--> 246             self._configure(*args, **kwargs)
    247         except TypeError as e:
    248             # It can be confusing if you have the wrong environment

/home/kv/universe/universe/envs/vnc_env.pyc in _configure(self, remotes, client_id, start_timeout, docker_image, ignore_clock_skew, disable_action_probes, vnc_driver, vnc_kwargs, rewarder_driver, replace_on_crash, allocate_sync, observer, api_key, record)
    194             remotes=remotes, runtime=runtime, start_timeout=start_timeout,
    195             api_key=api_key,
--> 196             use_recorder_ports=record,
    197         )
    198         self.connection_names = [None] * self.n

/home/kv/universe/universe/remotes/build.pyc in build(client_id, remotes, runtime, start_timeout, **kwargs)
     17             start_timeout=start_timeout,
     18             reuse=kwargs.get('reuse', False),
---> 19             n=n,
     20         ), n
     21     elif remotes.startswith('vnc://'):

/home/kv/universe/universe/remotes/docker_remote.pyc in __init__(self, runtime, n, reuse, start_timeout)
     52             start_timeout = 2 * self._n + 5
     53         self.start_timeout = start_timeout
---> 54         self._start()
     55 
     56     def allocate(self, handles, initial=False, params={}):

/home/kv/universe/universe/remotes/docker_remote.pyc in _start(self)
     81         [instance.start() for instance in self.instances]
     82         self.start_logging(self.instances)
---> 83         self.healthcheck(self.instances)
     84 
     85     def close(self):

/home/kv/universe/universe/remotes/docker_remote.pyc in healthcheck(self, instances)
    106             ['{}:{}'.format(instance.assigner.info['host'], instance.vnc_port) for instance in instances],
    107             ['{}:{}'.format(instance.assigner.info['host'], instance.rewarder_port) for instance in instances],
--> 108             start_timeout=30,
    109         )
    110 

/home/kv/universe/universe/remotes/healthcheck.pyc in run(vnc_addresses, rewarder_addresses, timeout, start_timeout)
     12 def run(vnc_addresses, rewarder_addresses, timeout=None, start_timeout=None):
     13     healthcheck = Healthcheck(vnc_addresses, rewarder_addresses, timeout=timeout, start_timeout=start_timeout)
---> 14     healthcheck.run()
     15 
     16 def host_port(address, default_port=None):

/home/kv/universe/universe/remotes/healthcheck.pyc in run(self)
    127                     remote_closed = True
    128                     if type == 'rewarder':
--> 129                         self._register_rewarder(address)
    130                     else:
    131                         self._register_vnc(address)

/home/kv/universe/universe/remotes/healthcheck.pyc in _register_rewarder(self, address, start_time)
     89 
     90             if time.time() - start_time > self.start_timeout:
---> 91                 raise error.Error('Rewarder server {} did not come up within {}s'.format(address, self.start_timeout))
     92 
     93         # Send a websocket handshake.

Error: Rewarder server localhost:15900 did not come up within 30s

```

I don't understand why Remote gets closed automatically as in this line, 

`[2016-12-23 02:45:50,080] Remote closed: address=localhost:5900`

**Comment by tlbtlbtlb** [comment]
This was a bug in 0.20.14 of the container. If you check out the latest universe code from github it's fixed.

**Comment by kvmanohar22** [comment]
So, do I need to checkout a different branch while installing universe ?

**Comment by tlbtlbtlb** [comment]
No, master branch.

**Comment by kvmanohar22** [comment]
Could you please elaborate on the installation process please ?
I had installed universe from [here](https://github.com/openai/universe/#installation)

**Comment by tlbtlbtlb** [comment]
Do this:
```
$ cd universe
$ git pull
```
and it should be fixed.
