### ISSUE TITLE
Installation issue on Yosemite

### ISSUE THREAD

**Issue by CharlesJQuarra** [openai/universe#85]
After installing as suggested on the `README.md`, I run the example script to test everything is running correctly

I get instead this error:

```
Traceback (most recent call last):
  File "test_uni.py", line 6, in <module>
    import universe  # register the universe environments
  File "/Users/charlesquarra/Projects/Universe/universe/universe/__init__.py", line 22, in <module>
    from universe import error, envs
  File "/Users/charlesquarra/Projects/Universe/universe/universe/envs/__init__.py", line 1, in <module>
    import universe.envs.vnc_env
  File "/Users/charlesquarra/Projects/Universe/universe/universe/envs/vnc_env.py", line 9, in <module>
    from universe import remotes as remotes_module
  File "/Users/charlesquarra/Projects/Universe/universe/universe/remotes/__init__.py", line 3, in <module>
    from universe.remotes.docker_remote import DockerManager
  File "/Users/charlesquarra/Projects/Universe/universe/universe/remotes/docker_remote.py", line 17, in <module>
    from universe.remotes.compose import container, log_printer, progress_stream
  File "/Users/charlesquarra/Projects/Universe/universe/universe/remotes/compose/log_printer.py", line 12, in <module>
    from six.moves import _thread as thread
ImportError: cannot import name _thread
```

I cannot find any module called `six` anywhere on the repository, or in `gym`. Please help?

**Comment by tlbtlbtlb** [comment]
Six is a standard Python module. You might have a very old version of it. Try
```
pip install --upgrade six
```

**Comment by CharlesJQuarra** [comment]
thanks! 
ok that fixes the missing dependency, but I get another error:

```
[2016-12-28 13:04:20,742] Making new env: flashgames.DuskDrive-v0
[2016-12-28 13:04:20,770] Writing logs to file: /tmp/universe-18162.log
Traceback (most recent call last):
  File "test_uni.py", line 11, in <module>
    env.configure(remotes=1)  # automatically creates a local docker container
  File "/Library/Python/2.7/site-packages/gym/core.py", line 226, in configure
    self._configure(*args, **kwargs)
  File "/Users/charlesquarra/Projects/Universe/universe/universe/vectorized/core.py", line 39, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/Library/Python/2.7/site-packages/gym/core.py", line 349, in _configure
    return self.env.configure(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/gym/core.py", line 226, in configure
    self._configure(*args, **kwargs)
  File "/Users/charlesquarra/Projects/Universe/universe/universe/wrappers/render.py", line 18, in _configure
    super(Render, self)._configure(**kwargs)
  File "/Users/charlesquarra/Projects/Universe/universe/universe/vectorized/core.py", line 39, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/Library/Python/2.7/site-packages/gym/core.py", line 349, in _configure
    return self.env.configure(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/gym/core.py", line 226, in configure
    self._configure(*args, **kwargs)
  File "/Users/charlesquarra/Projects/Universe/universe/universe/wrappers/throttle.py", line 27, in _configure
    super(Throttle, self)._configure(**kwargs)
  File "/Users/charlesquarra/Projects/Universe/universe/universe/vectorized/core.py", line 39, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/Library/Python/2.7/site-packages/gym/core.py", line 349, in _configure
    return self.env.configure(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/gym/core.py", line 226, in configure
    self._configure(*args, **kwargs)
  File "/Users/charlesquarra/Projects/Universe/universe/universe/envs/vnc_env.py", line 193, in _configure
    use_recorder_ports=record,
  File "/Users/charlesquarra/Projects/Universe/universe/universe/remotes/build.py", line 19, in build
    n=n,
  File "/Users/charlesquarra/Projects/Universe/universe/universe/remotes/docker_remote.py", line 43, in __init__
    self._assigner = PortAssigner(reuse=reuse)
  File "/Users/charlesquarra/Projects/Universe/universe/universe/remotes/docker_remote.py", line 149, in __init__
    self.client, self.info = get_client()
  File "/Users/charlesquarra/Projects/Universe/universe/universe/remotes/docker_remote.py", line 143, in get_client
    return docker.Client(base_url=host, version=client_api_version), info
  File "/Library/Python/2.7/site-packages/docker/client.py", line 99, in __init__
    self._version = self._retrieve_server_version()
  File "/Library/Python/2.7/site-packages/docker/client.py", line 124, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
```

**Comment by tlbtlbtlb** [comment]
Docker may not be installed or running. If you follow the instructions at https://github.com/openai/universe#install-docker, does that resolve it?

**Comment by CharlesJQuarra** [comment]
yes, starting the docker VM solved the issue. Thanks!
