### ISSUE TITLE
python 3.5.2 cannot import universe: __init__() got an unexpected keyword argument 'timestep_limit'

### ISSUE THREAD

**Issue by nojvek** [openai/universe#87]
```
universe git:(master) python3
Python 3.5.2 (default, Jun 29 2016, 13:42:46) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym
>>> import universe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/noj/Documents/dev/git/universe/universe/__init__.py", line 120, in <module>
    timestep_limit=500,
  File "/usr/local/lib/python3.5/site-packages/gym/envs/registration.py", line 124, in register
    return registry.register(id, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/gym/envs/registration.py", line 118, in register
    self.env_specs[id] = EnvSpec(id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timestep_limit'
```

**Comment by nottombrown** [comment]
Adding a fix now to preserve backwards compatibility

**Comment by nottombrown** [comment]
Closed by https://github.com/openai/gym/pull/446

**Comment by nojvek** [comment]
I just want to express my gratitude for working on making a quick fix over
holiday period. You are awesome.

**Comment by nottombrown** [comment]
Totally! Thanks for finding the bug 😊
