### ISSUE TITLE
Failed to complete WebSocket handshake

### ISSUE THREAD

**Issue by XanYder** [openai/universe#91]
When I try the example starting agent it gives me this error: 

`Waiting on rewarder: failed to complete WebSocket handshake. Retry in 1s (slept 0s/7s); connection closed uncleanly (WebSocket connection upgrade failed (502 - BadGateway)`

What do I do?

**Comment by tlbtlbtlb** [comment]
Can you tell us more about the OS and environment you're running in, and provide the logs from the session?

**Comment by XanYder** [comment]
[2017-01-03 12:13:36,226] Making new env: flashgames.SpacePunkRacer-v0
[2017-01-03 12:13:36,236] Writing logs to file: /tmp/universe-4361.log
[2017-01-03 12:13:36,281] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.15. Run the same thing by hand as: docker run -p 5900:5900 -p 15900:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.15
[2017-01-03 12:13:36,933] Remote closed: address=localhost:15900
[2017-01-03 12:13:36,934] Remote closed: address=localhost:5900
[2017-01-03 12:13:36,936] At least one sockets was closed by the remote. Sleeping 1s...
universe-7SveZO-0 | Setting VNC and rewarder password: openai
universe-7SveZO-0 | [Tue Jan  3 11:13:37 UTC 2017] Waiting for /tmp/.X11-unix/X0 to be created (try 1/10)
universe-7SveZO-0 | [Tue Jan  3 11:13:37 UTC 2017] [/usr/local/bin/sudoable-env-setup] Disabling outbound network traffic for none
universe-7SveZO-0 | [init] [2017-01-03 11:13:37,244] Launching system_diagnostics_logger.py, recorder_logdir=/tmp/demo
universe-7SveZO-0 | [init] [2017-01-03 11:13:37,247] Launching reward_recorder.py, recorder_logdir=/tmp/demo
universe-7SveZO-0 | [init] [2017-01-03 11:13:37,259] Launching vnc_recorder.py, recorder_logdir=/tmp/demo
universe-7SveZO-0 | [init] [2017-01-03 11:13:37,308] PID 54 launched with command ['sudo', '-H', '-u', 'nobody', 'DISPLAY=:0', 'DBUS_SESSION_BUS_ADDRESS=/dev/null', '/app/universe-envs/controlplane/bin/controlplane.py', '--rewarder-port=15901']
universe-7SveZO-0 | [init] [2017-01-03 11:13:37,557] init detected end of child process 58 with exit code 0, not killed by signal
[2017-01-03 12:13:37,940] Remote closed: address=localhost:5900
[2017-01-03 12:13:37,942] Remote closed: address=localhost:15900
[2017-01-03 12:13:37,943] At least one sockets was closed by the remote. Sleeping 1s...
universe-7SveZO-0 | [init] [2017-01-03 11:13:38,099] init detected end of child process 16 with exit code 0, not killed by signal
universe-7SveZO-0 | WebSocket server settings:
universe-7SveZO-0 |   - Listen on :5898
universe-7SveZO-0 |   - Flash security policy server
universe-7SveZO-0 |   - No SSL/TLS support (no cert file)
universe-7SveZO-0 |   - proxying from :5898 to localhost:5900
[2017-01-03 12:13:38,944] Using the golang VNC implementation
[2017-01-03 12:13:38,945] Using VNCSession arguments: {'subsample_level': 2, 'start_timeout': 7, 'fine_quality_level': 50, 'encoding': 'tight'}. (Customize by running "env.configure(vnc_kwargs={...})"
[2017-01-03 12:13:38,982] [0] Connecting to environment: vnc://localhost:5900 password=openai. Use the browser-based VNC client: http://localhost:15900/viewer/?password=openai
2017/01/03 12:13:38 I0103 12:13:38.984704 4361 gymvnc.go:417] [0:localhost:5900] opening connection to VNC server
2017/01/03 12:13:39 I0103 12:13:39.032292 4361 gymvnc.go:550] [0:localhost:5900] connection established
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    env.render()
  File "/home/xander/.local/lib/python2.7/site-packages/gym/core.py", line 175, in render
    return self._render(mode=mode, close=close)
  File "/home/xander/.local/lib/python2.7/site-packages/gym/core.py", line 344, in _render
    return self.env.render(mode, close)
  File "/home/xander/.local/lib/python2.7/site-packages/gym/core.py", line 175, in render
    return self._render(mode=mode, close=close)
  File "/home/xander/universe/universe/wrappers/render.py", line 49, in _render
    return self.env.render(mode=mode, *args, **kwargs)
  File "/home/xander/.local/lib/python2.7/site-packages/gym/core.py", line 175, in render
    return self._render(mode=mode, close=close)
  File "/home/xander/.local/lib/python2.7/site-packages/gym/core.py", line 344, in _render
    return self.env.render(mode, close)
  File "/home/xander/.local/lib/python2.7/site-packages/gym/core.py", line 175, in render
    return self._render(mode=mode, close=close)
  File "/home/xander/universe/universe/envs/vnc_env.py", line 537, in _render
    self.vnc_session.render(self.connection_names[0])
go_vncdriver.Error: /tmp/pip-build-bb3DYa/go-vncdriver/.build/src/github.com/openai/go-vncdriver/main.go:387: go_vncdriver was installed without OpenGL support. See https://github.com/openai/go-vncdriver for details on how debug.
[2017-01-03 12:13:39,063] Killing and removing container: id=7cb8c07ccc05f87c808e856ff959d46a38aaad7d60dfd2454b84beb6506cb526. (If this command errors, you can always kill all automanaged environments on this Docker daemon via: docker rm -f $(docker ps -q -a -f 'label=com.openai.automanaged=true')
[2017-01-03 12:13:39,098] [0:localhost:5900] Waiting on rewarder: failed to complete WebSocket handshake. Retry in 1s (slept 0s/7s): connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)

**Comment by XanYder** [comment]
import gym
import universe  # register the universe environments

env = gym.make('flashgames.SpacePunkRacer-v0')
env.configure(remotes=1)  # automatically creates a local docker container
observation_n = env.reset()

while True:
  action_n = [[('KeyEvent', 'ArrowUp', True)] for ob in observation_n]  # your agent here
  observation_n, reward_n, done_n, info = env.step(action_n)
  env.render()

**Comment by XanYder** [comment]
I noticed I had this error:

go_vncdriver was installed without OpenGL support. See https://github.com/openai/go-vncdriver for details on how debug.

So I looked at the website and I did everything it said but the error does not go away

**Comment by futurely** [comment]
go-vncdriver should list this issue in its FAQ.

https://github.com/openai/universe/wiki/Solutions-to-common-problems#universe-envrender-fails-with-libgl-error

**Comment by XanYder** [comment]
After some research I found out that it is because of an error in your code. So I looked in the log and I saw it had a problem with env.render(). Does anybody know how I can fix this?

**Comment by XanYder** [comment]
NEW CODE:

import gym
import universe
import random


#reinforcement learning step
def determine_turn(turn, observation_n, j, total_sum, prev_total_sum, reward_n):
	#for every 15 iterations, sum the total observations, and take the average
	#if lower than 0, change the direction
	#if we go 15+ iterations and get a reward each step, we're doing something right
	#thats when we turn
	if(j >= 15):
		if(total_sum/ j ) == 0:
			turn = True
		else:
			turn = False

		#reset vars
		total_sum = 0
		j = 0
		prev_total_sum = total_sum
		total_sum = 0

	else:
		turn = False
	if(observation_n != None):
		#increment counter and reward sum
		j+=1
		total_sum += reward_n
	return(turn, j, total_sum, prev_total_sum)




def main():

	#init environment
	env = gym.make('flashgames.CoasterRacer-v0')
	observation_n = env.reset()

	#init variables
	# num of game iterations
	n = 0
	j = 0
	#sum of observations
	total_sum = 0
	prev_total_sum = 0
	turn = False

	#define our turns or keyboard actions
	left = [('KeyEvent', 'ArrowUp', True) ,('KeyEvent', 'ArrowLeft', True), ('KeyEvent', 'ArrowRight', False)]
	right = [('KeyEvent', 'ArrowUp', True) ,('KeyEvent', 'ArrowLeft', False), ('KeyEvent', 'ArrowRight', True)]
	Forward = [('KeyEvent', 'ArrowUp', True) ,('KeyEvent', 'ArrowLeft', False), ('KeyEvent', 'ArrowRight', False)]


	#main logic
	while True:
		#increment a counter for number of iterations
		n+=1

		#if at least one iteration is made, check if turn is needed
		if(n > 1):
			#if at least one iteration, check if a turn
			if(observation_n[0] != None):
				#store the reward in the previous score
				prev_score = reward_n[0]

				#should we turn?
				if(turn):
					#pick a random event
					#where to turn? 
					event = random.choice([left,right])
					#perform an action
					action_n = [event for ob in observation_n]
					#set turn to false
					turn = False

		elif(~turn):
			#if no turn is needed, go straight
			action_n = [Forward for ob in observation_n]


		#if there is an obseravtion, game has started, check if turn needed
		if(observation_n[0] != None):
			turn, j, total_sum, prev_total_sum = determine_turn(turn, observation_n[0], j, total_sum, prev_total_sum, reward_n[0])

		#save new variables for each iteration
		observation_n, reward_n, done_n, info = env.step(action_n)

		env.render()

if __name__ == '__main__':
	main()

**Comment by futurely** [comment]
OpenGL was not installed on your machine. That's why go_vncdriver crashed.

You might want to open a pull request.
https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

**Comment by tlbtlbtlb** [comment]
@XanYder Could you provide enough detail to reproduce the problem you're having?
