### ISSUE TITLE
Why is there no instructions to set up the docker instance with openai-universe?

### ISSUE THREAD

**Issue by shyamalschandra** [openai/universe#94]
Why is there no instructions in the README to set up the docker instance with openai-universe?

**Comment by tlbtlbtlb** [comment]
Could you be more specific about what's missing at https://github.com/openai/universe#install-docker?

**Comment by shyamalschandra** [comment]
Well, the obvious!  There is no step-by-step for the `docker run` command in the instructions on how to setup the server that runs universe.

**Comment by tlbtlbtlb** [comment]
I still don't understand what you mean. Did you click the [Install Docker](https://docs.docker.com/engine/installation/) link and follow the instructions for your system? What didn't work?

**Comment by shyamalschandra** [comment]
Yes, I installed docker with the latest dmg.  There are no instructions specific to universe server-side.  It says the following on the instructions: "...Additionally, you can freely access the Docker images for the remotes. We'll release the source repositories for the remotes in the future, along with tools to enable users to integrate new environments. Please sign up for our beta if you'd like early access..." When will it be out of beta?  Why isn't available yet publicly?

**Comment by tlbtlbtlb** [comment]
We don't have a date for releasing the source code for the containers. We have to do some work to document the internals, and it would help us to understand what people want to do with them. Do you have a project in mind?

**Comment by shyamalschandra** [comment]
So...how can I run universe without the containers?  This is unclear as a signed up for the beta but where are the game-specific containers.  Did you release everything necessary to play or just a part of the components?  Why did OpenAI announce it in the first place when things are not finished?

**Comment by catherio** [comment]
yes, we have released all you need to play: the docs are at https://github.com/openai/universe/blob/master/doc/remotes.rst

The thing to look for in our docs, both the main README at https://github.com/openai/universe and the extra docs under "What's next?" and "Additional documentation", is the word "remotes", which we use to refer to remote environment servers. 

We have released the images/containers themselves (you can pull them from docker) but the code inside the containers is not yet a standalone github project.

**Comment by cantren** [comment]
"it would help us to understand what people want to do with them. Do you
have a project in mind?"

I applied for the beta as well.

I wanted to create a custom container to interface with a browser-based
three.js game that I made to train an agent to control a vehicle in an
autonomous submarine competition called "RoboSub <http://robosub.org>".

The simulator is here: http://cantren.github.io
Human control example: https://www.youtube.com/watch?v=Qf775rLs11c&t=620s
Some of the unlabeled test data here:
https://www.youtube.com/watch?v=Q16CAJmgFsY
Small labeled training/validation dataset here: goo.gl/QIXss4

I've looked into the official form <https://universe.openai.com/consent> for
this, but I think the game would probably need some modification prior to
integration?
Is there a process where a game can be modified by its author prior to
submission based on feedback from OpenAI?

Respectfully,
Nick Cantrell
Twitter: @envi_uuv <https://twitter.com/envi_uuv/>

**Comment by nottombrown** [comment]
Seems like the actual question here is about the `source code of universe docker images`. I've updated the title

**Comment by shyamalschandra** [comment]
@catherio, I looked and tried the following code with everything installed and dockers installed and running:

```
import gym
import universe # register the universe environments

env = gym.make('flashgames.DuskDrive-v0')
env.configure(remotes=1) # downloads and starts a flashgames runtime
observation_n = env.reset()

while True:
        action_n = [[('KeyEvent', 'ArrowUp', True)] for ob in observation_n] # your agent here
        observation_n, reward_n, done_n, info = env.step(action_n)
        env.render()
```

I am getting the following error:

```
[2017-01-08 04:34:24,521] Making new env: flashgames.DuskDrive-v0
Traceback (most recent call last):
  File "universe.py", line 2, in <module>
    import universe # register the universe environments
  File "/Users/shyamalsuhanachandra/universe.py", line 4, in <module>
    env = gym.make('flashgames.DuskDrive-v0')
  File "/usr/local/lib/python2.7/site-packages/gym/envs/registration.py", line 127, in make
    return registry.make(id)
  File "/usr/local/lib/python2.7/site-packages/gym/envs/registration.py", line 91, in make
    spec = self.spec(id)
  File "/usr/local/lib/python2.7/site-packages/gym/envs/registration.py", line 113, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: flashgames.DuskDrive-v0
```

What should I do?

**Comment by tlbtlbtlb** [comment]
Don't call your file `universe.py`. Python will see that file and import it instead of the universe module.

Rename it to something else, and delete any file `universe.pyc` in the same directory.

**Comment by shyamalschandra** [comment]
I changed the name and deleted the universe.pyc file and this is what I get:

```
iMac:~ shyamalsuhanachandra$ python universe-main.py 
[2017-01-08 14:31:52,166] Making new env: flashgames.DuskDrive-v0
[2017-01-08 14:31:52,209] Writing logs to file: /tmp/universe-1735.log
Traceback (most recent call last):
  File "universe-main.py", line 5, in <module>
    env.configure(remotes=1) # downloads and starts a flashgames runtime
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 225, in configure
    self._configure(*args, **kwargs)
  File "/Users/shyamalsuhanachandra/openai_projects/universe/universe/vectorized/core.py", line 39, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 352, in _configure
    return self.env.configure(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 225, in configure
    self._configure(*args, **kwargs)
  File "/Users/shyamalsuhanachandra/openai_projects/universe/universe/wrappers/render.py", line 18, in _configure
    super(Render, self)._configure(**kwargs)
  File "/Users/shyamalsuhanachandra/openai_projects/universe/universe/vectorized/core.py", line 39, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 352, in _configure
    return self.env.configure(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 225, in configure
    self._configure(*args, **kwargs)
  File "/Users/shyamalsuhanachandra/openai_projects/universe/universe/wrappers/throttle.py", line 27, in _configure
    super(Throttle, self)._configure(**kwargs)
  File "/Users/shyamalsuhanachandra/openai_projects/universe/universe/vectorized/core.py", line 39, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 352, in _configure
    return self.env.configure(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 225, in configure
    self._configure(*args, **kwargs)
  File "/Users/shyamalsuhanachandra/openai_projects/universe/universe/envs/vnc_env.py", line 193, in _configure
    use_recorder_ports=record,
  File "/Users/shyamalsuhanachandra/openai_projects/universe/universe/remotes/build.py", line 19, in build
    n=n,
  File "/Users/shyamalsuhanachandra/openai_projects/universe/universe/remotes/docker_remote.py", line 43, in __init__
    self._assigner = PortAssigner(reuse=reuse)
  File "/Users/shyamalsuhanachandra/openai_projects/universe/universe/remotes/docker_remote.py", line 149, in __init__
    self.client, self.info = get_client()
  File "/Users/shyamalsuhanachandra/openai_projects/universe/universe/remotes/docker_remote.py", line 143, in get_client
    return docker.Client(base_url=host, version=client_api_version), info
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 99, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 124, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', error(61, 'Connection refused'))
```

**Comment by tlbtlbtlb** [comment]
This happens when Docker isn't running. Instructions to install and set up Docker are here: https://github.com/openai/universe#install-docker

**Comment by shyamalschandra** [comment]
Okay, great.  Now, it is downloading.

**Comment by catherio** [comment]
Once you have downloaded the docker image once, it will remain on your machine and you will not have to download it again.

**Comment by aleSuglia** [comment]
I'm aware that releasing code of all the implemented Universe environments may be really labor-intensive so how about to provide us with a basic tutorial which explains how to create a new environment that can be integrated in Universe?

Thank you in advance for your answer.

Alessandro

**Comment by shashank10021997** [comment]
shashank@shashank-HP-Notebook:~/Documents/Policy_Gradients_to_beat_Pong-master$ python3 test.py
[2018-03-12 16:57:43,157] Making new env: flashgames.DuskDrive-v0
[2018-03-12 16:57:43,177] Writing logs to file: /tmp/universe-9954.log
Traceback (most recent call last):
  File "/home/shashank/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/shashank/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/shashank/.local/lib/python3.6/site-packages/docker/unixconn/unixconn.py", line 48, in request
    super(UnixHTTPConnection, self).request(method, url, **kwargs)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/shashank/.local/lib/python3.6/site-packages/docker/unixconn/unixconn.py", line 39, in connect
    sock.connect(self.base_url.replace("http+unix:/", ""))
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests-2.18.4-py3.6.egg/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/shashank/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/shashank/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/shashank/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/shashank/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/shashank/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/shashank/.local/lib/python3.6/site-packages/docker/unixconn/unixconn.py", line 48, in request
    super(UnixHTTPConnection, self).request(method, url, **kwargs)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/shashank/.local/lib/python3.6/site-packages/docker/unixconn/unixconn.py", line 39, in connect
    sock.connect(self.base_url.replace("http+unix:/", ""))
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    env.configure(remotes=1)  # automatically creates a local docker container
  File "/home/shashank/.local/lib/python3.6/site-packages/universe/universe/universe/wrappers/timer.py", line 14, in configure
    self.env.configure(**kwargs)
  File "/home/shashank/.local/lib/python3.6/site-packages/universe/universe/universe/wrappers/render.py", line 21, in configure
    self.env.configure(**kwargs)
  File "/home/shashank/.local/lib/python3.6/site-packages/universe/universe/universe/wrappers/throttle.py", line 32, in configure
    self.env.configure(**kwargs)
  File "/home/shashank/.local/lib/python3.6/site-packages/universe/universe/universe/envs/vnc_env.py", line 199, in configure
    use_recorder_ports=record,
  File "/home/shashank/.local/lib/python3.6/site-packages/universe/universe/universe/remotes/build.py", line 19, in build
    n=n,
  File "/home/shashank/.local/lib/python3.6/site-packages/universe/universe/universe/remotes/docker_remote.py", line 44, in __init__
    self._assigner = PortAssigner(reuse=reuse)
  File "/home/shashank/.local/lib/python3.6/site-packages/universe/universe/universe/remotes/docker_remote.py", line 165, in __init__
    self._refresh_ports()
  File "/home/shashank/.local/lib/python3.6/site-packages/universe/universe/universe/remotes/docker_remote.py", line 169, in _refresh_ports
    for container in self.client.containers():
  File "/home/shashank/.local/lib/python3.6/site-packages/docker/client.py", line 493, in containers
    res = self._result(self._get(u, params=params), True)
  File "/home/shashank/.local/lib/python3.6/site-packages/docker/client.py", line 76, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.6/dist-packages/requests-2.18.4-py3.6.egg/requests/sessions.py", line 526, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests-2.18.4-py3.6.egg/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests-2.18.4-py3.6.egg/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests-2.18.4-py3.6.egg/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))
what should i do please help
